In [1]:
library(dplyr)
library(tidyr)
library(pheatmap)
library(viridis)
library(tools)
library(cluster)
library(igraph)
library(tibble)

library(clusterProfiler)
library(org.Hs.eg.db)
library(dplyr)

Warning message:
“程辑包‘dplyr’是用R版本4.2.3 来建造的”

载入程辑包：‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“程辑包‘tidyr’是用R版本4.2.3 来建造的”
Warning message:
“程辑包‘viridis’是用R版本4.2.3 来建造的”
载入需要的程辑包：viridisLite

Warning message:
“程辑包‘viridisLite’是用R版本4.2.3 来建造的”
Warning message:
“程辑包‘cluster’是用R版本4.2.3 来建造的”

载入程辑包：‘igraph’


The following object is masked from ‘package:tidyr’:

    crossing


The following objects are masked from ‘package:dplyr’:

    as_data_frame, groups, union


The following objects are masked from ‘package:stats’:

    decompose, spectrum


The following object is masked from ‘package:base’:

    union



载入程辑包：‘tibble’


The following object is masked from ‘package:igraph’:

    as_data_frame


Warning message:
“程辑包‘clusterProfiler’是用R版本4.2.2 来建造的”


Registered S3 methods overwritten by 'treeio':
  method              from
  MRCA.phylo          tidytree
  MRCA.treedata       tidytree
  Nnode.treedata      tidytree
  Ntip.treedata       tidytree
  ancestor.phylo      tidytree
  ancestor.treedata   tidytree
  child.phylo         tidytree
  child.treedata      tidytree
  full_join.phylo     tidytree
  full_join.treedata  tidytree
  groupClade.phylo    tidytree
  groupClade.treedata tidytree
  groupOTU.phylo      tidytree
  groupOTU.treedata   tidytree
  is.rooted.treedata  tidytree
  nodeid.phylo        tidytree
  nodeid.treedata     tidytree
  nodelab.phylo       tidytree
  nodelab.treedata    tidytree
  offspring.phylo     tidytree
  offspring.treedata  tidytree
  parent.phylo        tidytree
  parent.treedata     tidytree
  root.treedata       tidytree
  rootnode.phylo      tidytree
  sibling.phylo       tidytree

clusterProfiler v4.6.0  For help: https://yulab-smu.top/biomedical-knowledge-mining-book/

If you use clusterProfiler in published research, please cite:
T Wu, E Hu, S Xu, M Chen, P Guo, Z Dai, T Feng, L Zhou, W Tang, L Zhan, X Fu, S Liu, X Bo, and G Yu. clusterProfiler 4.0: A universal enrichment tool for interpreting omics data. The Innovation. 2021, 2(3):100141


载入程辑包：‘clusterProfiler’


The following object is masked from ‘package:igraph’:

    simplify


The following object is masked from ‘package:stats’:

    filter


载入需要的程辑包：AnnotationDbi

载入需要的程辑包：stats4

载入需要的程辑包：BiocGenerics


载入程辑包：‘BiocGenerics’


The following objects are masked from ‘package:igraph’:

    normalize, path, union


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


载入需要的程辑包：Biobase

Warning message:
“程辑包‘Biobase’是用R版本4.2.3 来建造的”
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


载入需要的程辑包：IRanges

Warning message:
“程辑包‘IRanges’是用R版本4.2.3 来建造的”
载入需要的程辑包：S4Vectors


载入程辑包：‘S4Vectors’


The following object is masked from ‘package:clusterProfiler’:

    rename


The following object is masked from ‘package:tidyr’:

    expand


The following objects are masked from ‘package:dplyr’:

    first, rename


The following objects are masked from ‘package:base’:

    expand.grid, I, unname



载入程辑包：‘IRanges’


The following object is masked from ‘package:clusterProfiler’:

    slice


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice



载入程辑包：‘AnnotationDbi’


The following object is masked from ‘package:clusterProfiler’:

    select


The following object is masked from ‘package:dplyr’:

    select

In [2]:
# 读入
signature_Macro <- read.csv(
  "Example_refbuilder_Macro/ALL_cGEP_top_genes_Mono_Macro_wide_filt.csv",
  check.names = FALSE,
  stringsAsFactors = FALSE)
# 转成 list（核心）
cluster_genes <- lapply(signature_Macro, function(x) {
  x[!is.na(x) & x != ""]
})


gene_df <- data.frame(
  cGEP_Cluster = names(cluster_genes),  # 确保这里是 cGEP1, cGEP2...
  cGEP_signature = sapply(cluster_genes, function(x) paste(x, collapse = ",")),
  stringsAsFactors = FALSE
)
gene_df

       cGEP_Cluster
cGEP1  cGEP1
cGEP2  cGEP2
cGEP3  cGEP3
cGEP4  cGEP4
cGEP5  cGEP5
cGEP6  cGEP6
cGEP7  cGEP7
cGEP8  cGEP8
cGEP9  cGEP9
cGEP10 cGEP10
cGEP11 cGEP11
cGEP12 cGEP12
cGEP13 cGEP13
cGEP14 cGEP14
cGEP15 cGEP15
cGEP16 cGEP16
cGEP17 cGEP17
cGEP18 cGEP18
cGEP19 cGEP19
cGEP20 cGEP20
cGEP21 cGEP21
cGEP22 cGEP22
cGEP23 cGEP23
cGEP24 cGEP24
cGEP25 cGEP25
cGEP26 cGEP26
cGEP27 cGEP27
cGEP28 cGEP28
cGEP29 cGEP29
cGEP30 cGEP30
⋮      ⋮
cGEP48 cGEP48
cGEP49 cGEP49
cGEP50 cGEP50
cGEP51 cGEP51
cGEP52 cGEP52
cGEP53 cGEP53
cGEP54 cGEP54
cGEP55 cGEP55
cGEP56 cGEP56
cGEP57 cGEP57
cGEP58 cGEP58
cGEP59 cGEP59
cGEP60 cGEP60
cGEP61 cGEP61
cGEP62 cGEP62
cGEP63 cGEP63
cGEP64 cGEP64
cGEP65 cGEP65
cGEP66 cGEP66
cGEP67 cGEP67
cGEP68 cGEP68
cGEP69 cGEP69
cGEP70 cGEP70
cGEP71 cGEP71
cGEP72 cGEP72
cGEP73 cGEP73
cGEP74 cGEP74
cGEP75 cGEP75
cGEP76 cGEP76
cGEP77 cGEP77
       cGEP_signature
cGEP1  IL1B,PLAUR,C15ORF48,SRGN,SOD2,EREG,NAMPT,BCL2A1,CXCL8,CXCL2,G0S2,NFKBIA,BTG1,SAMSN1,AQP9,CXCL3,FTH1,TIMP1,OLR1,THBS1,PNRC1,CD44,IER3,NLRP3,C5AR1,CCL20,SAT1,TNFAIP3,SLC2A3,PTGS2
cGEP2  HSP90AA1,HSPA1A,HSPB1,HSPA1B,DNAJB1,HSPE1,IER5,ZFAND2A,HSPD1,HSPH1,HSPA6,DUSP1,RHOB,BAG3,DNAJB4,RGS2,UBC,MTRNR2L2,HSP90AB1,AP000769.1,ND3,CLK1,KLF2,DNAJA4,UBB,DNAJA1,CACYBP,RPS4Y1,SH3BGRL3,SHISAL2A
cGEP3  FABP7,ZIC5,RP11-408N14.1,RP1-56K13.2,FGG,SPRR1B,PRSS57,DPP10,HOXD10,RPS18,RPS6,SFTPA1,SPRR2D,SFTPA2,AP001171.1,RPS23,RPS4X,RPL3,RPS3,POU3F3,RPS12,CLDN2,RPLP0,RPS5,NPM1,FGB,RPS2,RPS7,RPL10A,RP11-817J15.2
cGEP4  DNAJB1,HSPA1B,HSPA1A,HSP90AA1,BAG3,HSPB1,HSPH1,HSP90AA2P,HSPD1,HSPA6,UBC,HSP90AB1,DNAJB1P1,JUN,DNAJA1,ZFAND2A,HSPE1,HSPA8,IER5,HSP90AA4P,DUSP1,DNAJA4,ZSCAN12P1,PCYT1B,PPP1R15A,ATF3,NR4A1,RGS2,UBB,HSPA7
cGEP5  S100A9,S100A8,LYZ,S100A12,VCAN,GAPDH,S100A6,AC020656.1,FCN1,TSPO,PLBD1,VIM,CSTA,METTL9,SELL,ATP5MPL,S100A4,TKT,LGALS1,RF00012,CD36,S100A10,RP11-1143G9.4,MGST1,RETN,SERPINB1,CES1,ATP5F1E,TALDO1,CDA
cGEP6  MTCO1P53,S100A9,RP11-240E2.2,S100A8,LYZ,FCN1,VCAN,S100A12,Metazoa-SRP,RP5-857K21.11,AC138744.2,RP4-635A23.6,AC016739.2,SELL,MNDA,S100A6,TKT,LA16C-306A4.2,RP11-417L19.5,4h.2,RP3-417G15.1,PLBD1,CSTA,CTD-2649C14.2,RP11-362F19.2,RP5-857K21.7,CTSS,TSPO,S100A4,CTB-181H17.1
cGEP7  AC079325.2,FCGR3A,LST1,C19ORF38,IFITM2,RPS19,RHOC,CNTN5,CDKN1C,C10ORF54,SMIM25,IFITM3,AC104809.2,AIF1,NDNF,C15ORF39,NAP1L1,AC104809.4,LINC01272,MS4A7,LOC100130520,TCF7L2,LINC02334,RP5-857K21.11,SERPINA1,COTL1,FCER1G,CD79B,LOC101928037,LOC100507639
cGEP8  GZMB,CLEC4C,LILRA4,CLIC3,SMPD3,PACSIN1,LRRC26,TSPAN13,PTCRA,MZB1,ITM2C,IGJ,IRF7,TLR9,JCHAIN,RP11-73G16.2,IRF4,SCT,FAM129C,LOC101928123,C12orf75,TCL1A,PPP1R14B,CXCR3,DERL3,SPIB,LOC101929219,RP1-302G2.5,TCF4,MAP1A
cGEP9  ACP5,LGALS3,CALR,CD63,PLA2G7,FTL,CTSB,CTSD,TGFBI,PRDX1,FPR3,CAPG,CTSL,S100A11,FABP5,NPC2,YBX1,PSAP,PMP22,FABP5P7,IFI30,HSP90B1,APOE,AC026366.1,PPIB,ATP6V1F,ANXA2,PCOLCE2,HLA-DQA2,HLA-DRB5
cGEP10 CCR7,FSCN1,LAMP3,BIRC3,LAD1,TXN,EBI3,CCL19,AL109741.1,MARCKSL1,IDO1,CCL22,AC007216.2,SLCO5A1,SINHCAF,HMSD,CD200,NUB1,GPR157,AOC1,TBC1D4,AC112719.2,LIMCH1,BX255923.3,RAB9A,PPA1,CSF2RA,DAPP1,BCL2L14,KIF2A
cGEP11 AC245427.1,IL32,CD3D,CD3E,PTPRCAP,TRAC,GZMA,CD2,TRBC2,CD3G,LCK,CCL5,LOC101929531,NKG7,CD7,TRBC1,GZMM,CTSW,KLRB1,CST7,SPOCK2,CD247,GZMH,CD27,AP002004.1,ETS1,GNLY,CD8A,PRF1,PCED1B-AS1
cGEP12 CTC-575D19.1,HLA-DPB1,HLA-DPA1,HLA-DRA,HLA-DQB1,HLA-DQA1,CD74,CTD-2192J16.15,HLA-DRB1,HLA-DRB6,FCER1A,CD1C,CLEC10A,AC005251.3,RPS2,RPS18,RP3-406A7.3,CTD-2014B16.2,RP11-318C24.1,CST3,RPS23,RP11-51O6.1,RPL3,RPL23A,RPL15,RP4-800G7.1,RP11-215A21.2,RP11-492M23.2,RPS6,RPL10A
cGEP13 CTSK,MMP9,CKB,SIGLEC15,SLC9B2,ACP5,AK5,NDRG4,CST3,AP000904.1,MT-RNR1,TCIRG1,THOP1,SPINK2,ANXA8L1,ATP6V0D2,S100A3,ITGB3,MYH16,RGS10,SLC22A1,HTRA3,DPP4,HSPB7,COL6A2,HYAL1,MTATP6P1,BAMBI,MT-RNR2,RP11-54O7.1
cGEP14 JUN,FOS,HSPA1B,DUSP1,SFTPC,SFTPA1,DNAJB1,RHOB,IER2,ATF3,KLF2,C1QA,C1QC,EGR1,HSPA1A,UBC,RGS1,GADD45B,ITM2B,C1QB,JUNB,ZFP36L2,NR4A2,KLF4,SEPP1,HERPUD1,HSP90AA1,GPR34,TXNIP,FCGR3A
cGEP15 NKG7,GZMB,GZMA,GNLY,FGFBP2,PRF1,CST7,CTSW,GZMH,KLRD1,SPON2,ADGRG1,CLIC3,HOPX,S1PR5,GZMM,IL2RB,CD247,XCL2,AL158071.4,TBX21,KIR2DL1,KLRF1,TRDC,CCL4,CD7,PTGDR,CD160,ZMAT4,PRSS23
cGEP16 APOE,CTSD,GPNMB,APOC1,RP11-368J21.3,LGMN,CTSB,PSAP,C1QB,PLD3,ACP5,FTL,C1QC,LIPA,CD63,C1QA,PLA2G7,CD68,FUCA1,CAPG,PRDX1,RP11-696F12.1,ASAH1,GRN,CTSZ,TREM2,HLA-DRB4,LGALS3,CTSL,CTSC
cGEP17 FO538757.3,MPIG6B,PPBP,PF4,GNG11,GP9,TUBB1,SDPR,SPARC,CAVIN2,HRAT92,CMTM5,TREML1,SPTB,CLU,C6orf25,NRGN,HIST1H2AC,AP001189.1,ITGA2B,MYL9,SEPT5,GRAP2,TUBA8,TMEM40,DMTN,CTTN,RP11-678G14.3,PDLIM1,RP11-185E8.1
cGEP18 MTRNR2L5,C1QB,NPC2,ATXN8OS,CD74,NAPSB,C1QC,TREM2,PCED1B-AS1,CTC-471J1.9,AL353644.10,B2M,PSME2P2,AC004448.5,HLA-DPA1,C1QA,HLA-DRA,TMSB4X,RP11-680H20.1,ALOX5AP,HLA-DRB1,FCER1G,HLA-DMB,UBBP4,COX6A1P2,FYB1,ATP5F1A,JPT1,VSIR,TYROBP
cGEP19 C1QA,SELENOP,C1QB,C1QC,FOLR2,AC008945.2,DAB2,GGTA1P,CYTB,LGMN,SEPP1,SLCO2B1,SLC40A1,PLTP,MS4A4A,MAF,RNR2,CD163,A2M,STAB1,FCGRT,GIMAP1-GIMAP5,GPR126,RNASE1,ATP6,MRC1,MS4A7,SDC3,CTSC,KIAA0247
cGEP20 AC109326.1,RF00012,MTATP6P1,MTND1P23,RNU1-1,AC018445.4,CCL3,CCL4,MT-TM,AC011676.5,AC087284.1,MTND2P28,CCL3L1,AC122718.1,CCL4L2,CD83,RNU1-2,ENSG00000206828,RN7SL473P,RNVU1-19,ENSG00000273727,RNVU1-15,IER3,RNU1-4,MT-RNR2,EGR1,AC104581.4,CCL3L3,RNU6-6P,KLF6
cGEP21 CTD-3252C9.4,LGALS2,RPPH1,LINC00936,DUSP6,FGL2,ATP5E,ZFP36,NEAT1,NFKBIA,IL1B,ZFP36L1,RP11-160E2.6,MARCKS,PID1,ATP5I,DUSP1,FOS,TCEB2,CPVL,FYB1,CD4,CCL3L3,LAP3,NAMPT,SAMHD1,JUND,FTH1,AHNAK,RP11-430G17.3
cGEP22 CSTB,GPNMB,FTL,AC106788.1,CTSD,CTSB,SPP1,ANXA2,CD63,LGALS3,TM4SF19,VIM,LGALS1,APOC1,CAPG,CTSL,CD68,CHI3L1,FABP5,MMP9,CYP27A1,CD9,FTH1,NUPR1,LIPA,GAPDH,FBP1,APOE,SDC2,CHIT1
cGEP23 AC090109.1,AC104964.2,TPSB2,Z84492.1,CPA3,AL357556.4,TPSAB1,HDC,RHEX,KIT,AC090236.2,SLC18A2,PRG2,MS4A2,C1ORF186,AC022960.1,HPGD,IL1RL1,GATA2,MAOB,AL645568.2,KCTD9P1,HDGFP1,CTSG,SIGLEC17P,TPSD1,SVOPL,RP11-354E11.2,ADCYAP1,AL161756.1
cGEP24 KRT6A,KRT16,KRT6B,KRT6C,KRT14,PERP,LY6D,S100A7,KRTDAP,DMKN,AQP3,SFN,SBSN,TRIML1,LGALS7B,S100A14,KRT17,SERPINB4,S100A16,SPRR1B,S100A8,SERPINB3,KRT1,GJB2,DSP,OVOL1-AS1,KRT5,LINC01527,KRT10,PI3
cGEP25 CCL3L1,GPR183,RGS1,AC016831.5,CD83,AREG,NFKBIA,SRGN,HLA-DQB1,REL,ZFP36,JUNB,CXCR4,HNRNPA1P48,NR4A3,NR4A1,RPL3,NR4A2,RACK1,OLR1,SGK1,HLA-DPB1,FAM64A,ID2,DUSP2,IL1B,HLA-DRB5,HLA-DRA,ZNF331,RPS4X
cGEP26 ISG15,GBP1,TNFSF10,IFIT3,CXCL10,IFIT1,MX1,CXCL11,IFITM3,IFIT2,IFI6,LY6E,HLA.B,EPSTI1,HLA.C,ISG20,RSAD2,IFI44L,LAP3,B2M,APOBEC3A,GBP4,CALHM6,IDO1,PPAPDC2,TYMP,IGLC1,STAT1,UBE2L6,OAS1
cGEP27 RPL26P19,RP11-20O24.4,GAPDH,RP13-258O15.1,VIM,S100A10,RPL9P9,EEF1A1P5,AC092484.1,MIF,RPL37A,AC011933.2,CSTB,TMSB4XP6,ENO1,MCEMP1,LDHA,FBP1,LGALS1,RP11-466H18.1,TPI1,S100A6,SH3BGRL3,RPL23AP74,RPS29,RPS27,RPL41,FTLP3,RP11-83J16.1,RPS28
cGEP28 BX005266.2,IGKV1-6,IGHV3-15,IGKV1D-39,IGHV3OR16-13,MZB1,LOC102723766,IGKC,IGKV1D-16,IGHG1,JCHAIN,IGKV1-17,IGHV3-23,IGHG2,IGHG4,IGHG3,IGJ,IGKV1D-17,DERL3,AC007386.4,CH17-212P11.4,TNFRSF17,OR4C13,AC107464.3,IGHGP,IGKV3-20,FKBP11,RP11-16E12.2,CD27,IGHA1
cGEP29 HLA-DPA1,CD74,HLA-DQB1,FCER1A,HLA-DPB1,PLD4,LOC100996809,HLA-DRB5,PKIB,GSN,HLA-DRA,NDRG2,CD1E,NAPSB,CD1C,CXorf36,HLA-DRB4,HLA-DRB1,ALOX5AP,CHAD,HLA-DQA2,RGS1,HLA-DQA1,HERPUD1,HLA-DMA,CDH17,PLEK2,CD207,FCGR2B,HLA-DQB2
cGEP30 IL8,RPL13,RPL32,RP11-463O12.5,RPLP2,TPT1,RPS16,RPL10,RPS24,RPL34,RPLP1,RPL28,FOSB,MIR24-2,RPS14,RPS12,RPS18,RPL18A,RPS8,RPL13A,RPL30,RPS23,RPL11,RPL37,RPL26,RPL35A,RPS15A,RPL37A,RPL9,RPS3A
⋮      ⋮
cGEP48 S100A9,SH3BGRL3,MYL6,EMP3,S100A8,ANXA2,SERF2,CD163,S100A11,S100A10,TIMP1,S100A6,FCER1G,MARCO,CFL1,LGALS1,AL445524.1,PFN1,S100A4,ACTB,SELENOT,SDF2L1,AP2S1,CD14,SLC39A8,RIPOR2,POMP,HSP90B1,CALR,NOP10
cGEP49 CCL3L3,CCL3,CCL4,IL1B,NFKBIA,CCL4L2,ZFP36,BCL2A1,CXCL3,TNF,PSME2,SOD2,CXCL2,IER3,KB-1507C5.4,PLAC8,CXCL8,SRGN,GADD45B,HLA-DRB1,HLA-DRA,GBP1,CH17-373J23.1,APOBEC3A,ATP5EP2,IFITM3,CD83,PPP1R15A,VAMP5,NCF1
cGEP50 COL3A1,COL1A2,COL1A1,DCX,RP11-166D19.1,LUM,SPARC,DCN,C8ORF4,POSTN,COL5A2,COL6A3,AC025822.2,COL5A1,COL6A2,CTHRC1,HAPLN1,CTGF,COL6A1,AEBP1,ISLR,CALD1,EGFL6,BGN,RP11-119F7.5,PCOLCE,MXRA5,WNT2,EPYC,HSPB1P1
cGEP51 CCL3L1,CCL3,CCL3L3,CCL4,IL1B,CCL4L2,TNF,NFKBIA,CD83,PPP1R15A,ZFP36,JUN,GADD45B,FOS,IER2,IER3,ATF3,TNFAIP3,JUNB,KLF6,CXCL8,FOSB,RP3-393E18.2,NR4A1,DUSP2,IL1A,NFKBIZ,SOD2,SGK1,NR4A2
cGEP52 C1QB,C1QA,C1QC,PLTP,MARCO,CST3,HAMP,CD163,RPS27L,SEPP1,CXCL12,TSPAN13,PSAP,FN1,IFI27,FOLR2,LYVE1,CD14,CTSL,SLC2A5,TMSB4X,CFD,MPC2,AIF1,MT2A,BHLHE41,VAMP5,TIMD4,CXADR,MS4A4A
cGEP53 RGS1,SNHG7,CD37,RGS10,EEF1A1,EIF4A2,KRT5,YPEL3,SCUBE2,ZFP36L2,EPB41L4A-AS1,CEBPD,NPM1,CCNI,CDKN1C,HLA-DPB1,CIRBP,EVI2B,RPL3,TXNIP,RPS4X,HERPUD1,EVI2A,RPS3,RPL31,C10orf54,PCNXL2,C10orf11,DNAJB1,EEF2
cGEP54 C1QC,C1QB,C1QA,CTSC,HLA-C,FCGR3A,SLC40A1,LGALS3BP,HLA-DRB1,B2M,IFI6,TYROBP,CD14,TMEM176B,CD74,HLA-A,STAT1,ITM2B,FCGR2A,HLA-DQA1,LY6E,FCER1G,CTSB,HLA-DMB,EPSTI1,BST2,GRN,HLA-DRA,SERPING1,TYMP
cGEP55 HBB,CA1,HBD,ESPN,HBA1,HBA2,AHSP,ALAS2,HBG1,HBM,SLC4A1,GYPA,GYPB,EPB42,MRC2,SLC25A37,SNCA,STRADB,SLC25A39,PRDX2,PDZK1IP1,BLVRB,CR2,DCAF12,FECH,SELENBP1,OSBP2,HEMGN,TMEM56,CDH1
cGEP56 DUSP1,AREG,FOS,SAMSN1,SOCS3,ZFP36,SRGN,IL1B,MAT2A,ZNF331,NAMPT,SERPINB2,RGS2,JUNB,TNFAIP3,CD55,THBS1,SLC2A3,FKBP5,CLEC4E,IL1R2,ACSL1,LITAF,MCL1,NR4A2,GK,SAT1,CDKN1A,FAM65B,LOC731424
cGEP57 DCN,FBLN1,MGP,IGFBP6,PLAC9,CCDC80,C1R,MFAP4,EFEMP1,CFD,C1S,SFRP1,DPT,SOD3,GSN,IGFBP5,ADH1B,LUM,PRELP,FGF7,WISP2,HSPB6,TIMP3,IGFBP4,OGN,PCOLCE2,SPARCL1,APOD,SERPINF1,PLD5
cGEP58 PBK,UGT3A2,MS4A1,AC025437.4,ATP2A1-AS1,RDM1,ELL3,ELOVL6,PACSIN3,IGLL1,VAT1L,GINS2,GALNT14,VPREB1,RPGRIP1L,HMGB1,CCDC81,ZNF470,PIMREG,DSCC1,IGHD,CDKN3,PTMA,HPDL,PPIA,FABP5,GINS3,ZNF771,DKK2,TUBA1B
cGEP59 CTSG,PLD4,LGALS1,DHRS3,ENHO,H2AFZ,HMGN2,ACTG1,FABP5,PDE6G,HOXB-AS3,MRPL33,PTMA,PPIA,PHACTR3,METTL7B,CXorf21,STMN1,RNASE2,DBI,MCM2,IGFBP7,ACOT7,CFL1,PHGDH,MCM6,SH3BP4,HMGN1,HLA-DQA2,HNRNPA2B1
cGEP60 TSPAN8,TFF1,AGR2,KRT19,FXYD3,ELF3,KRT8,S100P,EPCAM,MUC1,WFDC2,CEACAM6,TM4SF1,TMC5,SMIM22,KRT18,C19orf33,LMO7,AL033384.1,GPRC5A,TFF2,LGALS4,MAL2,CTSE,CLDN4,TM4SF4,SPINK1,CEACAM5,SLPI,OCIAD2
cGEP61 PRAME,TNC,TUSC3,ZNF462,IGFBP5,SCHIP1,DRGX,WWC1,TAGLN3,MEX3A,PCLO,C18orf42,STRA6,MDK,KIF26A,SNAP25,CRYBA2,CNTN2,TJP1,MAP2,GALNTL6,STMN1,largeTAntigen,SLC44A3,HPCA,RORB,SHD,CCK,PLEKHA6,ENAH
cGEP62 HSPD1,HSPH1,HSPB1,FKBP4,BAG3,HSP90AA1,HSP90AB1,HSPA1A,CHORDC1,CACYBP,HSPA8,HSPE1,MRPL18,SERPINH1,AHSA1,HLA-DPB1,SNX3,DOK2,ZFAND2A,DNAJB6,TCP1,PTGES3,DNAJA1,DNAJB1,NUDC,SNAP23,ST13,P4HA1,HSPA4L,STIP1
cGEP63 UNC80,STMN2,UBE2QL1,IFITM2,BARHL1,SLC25A37,S100A8,CSF3R,KCNJ6,MNDA,KIF5A,VNN2,NAMPT,FCGR3B,CDA,GCA,ALOX5AP,S100A9,RIPOR2,ANP32A,AL355601.1,CMTM2,RGL4,CYP4F3,S100A12,DRAIC,ACSL1,DRD1,XKR4,NCF1
cGEP64 SPARCL1,CLU,INMT,C1orf61,NTRK2,GPM6B,CPE,MT3,GFAP,PTN,PTPRZ1,ATP1B2,IL33,SLC1A2,TTYH1,TOMM20P1,ID4,ABCD2,GJA1,TRIL,CST3,ITM2C,TSC22D4,AQP4,LRRC4C,C17orf100,FBLN7,SPARC,AGT,SCG3
cGEP65 LINC01986,KRT18,KRT8,MDK,YWHAE,WFDC2,SPINT2,CD24,ELF3,KRT19,EPCAM,CD47,RPL8,MMP7,PDZK1IP1,MTCH1,LCN2,HSP90AB1,RARRES1,TM4SF1,AL512274.1,LY6E,CLPS,C6orf132,BCAM,KRT17,CD9,BEX3,LHX1,ASRGL1
cGEP66 CRABP2,CHI3L1,MMP7,COL22A1,MMP12,SPP1,TMEM114,CSTB,LPL,CHIT1,SLAMF9,SDC2,LINC02345,CD52,AC084809.2,FBP1,IFI6,PAQR5,AL117379.1,SPOCD1,AC015660.2,GPC4,AC244033.2,SLC12A8,CLVS1,MMP9,SH3BGRL3,HCST,ATP6V0D2,RAC2
cGEP67 RP11-160O5.1,FABP4,GPC4,SPOCD1,CRABP2,LPL,TM4SF19,GDF15,SPP1,HOXB6,CHI3L1,TREM2,TIMP3,COL6A2,FCGBP,TBX1,GPNMB,EPB41L1,USP2,ITGA3,PLD3,APOE,GPR150,FABP5,CTSD,LIPA,CADM1,GOLGA7B,FTL,APOC1
cGEP68 BFSP1,IGFBP7,COL5A3,SPARCL1,COL4A1,FGF1,GUCY1A1,CALD1,PLXDC1,SPARC,KCNJ8,TPPP3,THY1,CACNA1C,CAVIN3,MGP,SLC2A4,AC107294.2,PRSS23,COX4I2,NDUFA4L2,COL6A2,PRF1,SOD3,C15orf62,RGS5,CCDC102B,COL3A1,COL15A1,GJC1
cGEP69 C14orf2,MT-CO2,MT-ATP6,RPL34,MT-ND2,RPS3A,RPS27A,MT-ND4,RPL7,MT-CYB,RPL39,RPS15A,RPL26,RPL21,RPS24,MT-ND5,RPL9,RPL30,RPS27,COX7B,MT-ND3,MT-CO3,S100A12,ATP5E,COL1A1,COL1A2,SUB1,ESD,LINC00998,RPS25
cGEP70 AL935026.1,HLA-DQA1,LOR,HLA-DRB5,HLA-DQB1,IDO1,PPA1,CCR7,EDARADD,LAMP3,CST7,EBI3,FSCN1,NAPSB,TVP23A,LAD1,HLA-DPA1,CXCL9,SPIB,HLA-DRB1,CD207,HLA-DPB1,TIFAB,CD1E,BIRC3,CALHM6,CD74,PSME2,CLEC10A,AC008429.2
cGEP71 IGKC,IGHGP,LY6K,IGHG1,SNHG25,SCGB1D2,S100A1,MT-ND1,IGHG3,PCP4,IGHG4,IGLC7,MT-ND2,FBXO2,MT-CO2,CD209,MT-ATP6,PART1,MT-ND4,IGHM,OLFM3,PNMT,IGLC3,CCL13,RPS20,DSCR8,MT-ND3,TNNT1,MT-ND5,HES1
cGEP72 NDUFA4L2,WFDC1,MYLK,ACTA2,MCAM,PPP1R14A,COL4A1,RGS5,CAV1,IGFBP7,TAGLN,MYL9,TINAGL1,COL4A2,SPARCL1,PLN,COX4I2,CALD1,LURAP1L,AVPR1A,LHFP,CAP2,MYH11,LMOD1,KCNJ8,DKK3,EFHD1,COL18A1,PDLIM1,NOTCH3
cGEP73 PPP1R15A,UBC,GADD45B,KLF4,NRIP3,JUN,HSPA6,IRS2,MAP1LC3B,ANXA1,HSPA1A,RGCC,HSPA1B,PHLDA2,ZBTB43,EIF1,SLC38A2,PHLDA1,IER2,FOSB,ARC,DUSP1,UBB,HSPA8,HMOX1,DNAJB1,CITED2,SGK1,CSRNP1,HCAR3
cGEP74 CTRB2,CLPS,AC104046.1,CTRC,FTLP3,REG1A,FABP5P7,PRSS1,CPA1,PLA2G1B,CTRB1,MTND1P23,CPB1,PNLIP,CEL,CELA3A,SLC4A4,SYCN,FXYD2,FABP5P1,GP2,AC016739.1,TREM2,MTATP6P1,A2M,AMY2A,CPA2,FABP5,PNLIPRP1,CD9
cGEP75 TCF15,SPARCL1,MEOX2,IGFBP7,POSTN,PCDH17,CYP4B1,ACKR1,FMO2,GALNT18,MMRN2,FILIP1,MGP,DOC2B,VWF,C1QTNF9,CLDN5,AQP1,MATN2,C7,PALMD,CNTNAP3B,ADGRF5,GPIHBP1,IGFBP3,FAM162B,HOXD8,CCDC3,RAMP2,MMRN1
cGEP76 PODN,PLAC9,CCDC80,ADH1B,CCDC3,OGN,FBLN1,LUM,GTSE1-DT,CILP,IL32,ISM1,GREM1,PCDHGB7,OR52A1,DPT,ISLR,C7,DNER,SCGB1A1,AC108463.3,MGP,AC008555.5,ENAM,GZMA,CCL5,IL7R,CD3D,AC025271.4,CD2
cGEP77 APOBEC3A,FFAR2,IL1RN,CXCL10,RP11-525A16.4,NRN1,CCL7,CTD-2001C12.1,AP000704.5,LILRA5,ESPN,APOBEC3B,IFIT1,CXCL11,FJX1,CALY,ISG15,CCL2,ACOX2,TNFSF10,RAB36,HSPA1A,GBP1,RP11-7F18.2,FCGR3B,TRAV17,ACTB,TRAV14DV4,KIAA1107,FKBP1C

In [3]:
#Macro_gep_anno <- read.csv('./3.1.Macro_GEP_Anno/3.3.Macro_GEP77_Anno_final.csv')
Macro_gep_anno <- read.csv('/sibcb1/bioinformatics/yangyue/project/immunotherapy/7.6.cNMF_menchmark/cGEP_signature/Macrophage_cGEP77.csv')

Macro_gep_anno

   cGEP_Cluster cGEP_Anno_Name                Category
1  cGEP26       Macro_M1_ISG                  Functional
2  cGEP11       Doublet_T_Cell                Doublet
3  cGEP10       mregDC                        Lineage
4  cGEP49       Macro_M1_Inflammatory         Functional
5  cGEP13       Macro_Osteoclast-like         Lineage
6  cGEP51       Macro_M1_Early_Activation     Functional
7  cGEP16       Macro_M2_LAM                  Lineage
8  cGEP18       Macro_M2_Homeostasis          Lineage
9  cGEP44       Fibroblast                    Doublet
10 cGEP15       Doublet_NKT                   Doublet
11 cGEP50       Fibroblast                    Doublet
12 cGEP60       Epithelial_Tumor              Doublet
13 cGEP45       Epithelial_Tumor              Doublet
14 cGEP65       Epithelial_Tumor              Doublet
15 cGEP38       Macro_Cycling_G2M             Functional
16 cGEP19       Macro_M2_Resident_FOLR2       Lineage
17 cGEP22       Macro_M2_Iron                 Lineage
18 cGEP23       Mast_Cell                     Lineage
19 cGEP1        Macro_M1_Invasive             Functional
20 cGEP29       DC_cDC2                       Lineage
21 cGEP32       Macro_M2_C1Q                  Lineage
22 cGEP55       Artifact_RBC                  Artifact
23 cGEP40       B_Cell                        Doublet
24 cGEP34       Macro_M2_Scavenging           Lineage
25 cGEP41       DC_cDC1                       Lineage
26 cGEP47       Mono_CD16                     Lineage
27 cGEP48       Mono_CD14                     Lineage
28 cGEP14       Doublet_AT2_Stress            Doublet
29 cGEP57       Fibroblast                    Doublet
30 cGEP69       Fibroblast                    Doublet
⋮  ⋮            ⋮                             ⋮
48 cGEP24       Epithelial_Tumor              Doublet
49 cGEP66       Macro_M2_Remodeling           Lineage
50 cGEP36       Macro_Cycling_G1S             Functional
51 cGEP74       Acinar_Cell                   Doublet
52 cGEP56       Stress_EarlyResponse          Artifact
53 cGEP43       MHCII_Antigen_Processing      Functional
54 cGEP67       Macro_M2_Lipid                Lineage
55 cGEP7        Mono_CD16                     Lineage
56 cGEP4        Stress_HeatShock              Artifact
57 cGEP3        Tumor_Neura_Progenitor        Doublet
58 cGEP72       Myofibroblast_Smooth Muscle   Doublet
59 cGEP71       Plasma_Cell                   Doublet
60 cGEP64       Stromal_Endothelial           Doublet
61 cGEP73       Artifact_Stress_ISR           Artifact
62 cGEP28       Plasma_Cell_IgG               Doublet
63 cGEP62       Chaperone_Stress              Artifact
64 cGEP70       Macro_M1_Antigen_Presentation Lineage
65 cGEP77       Macro_M1_ISG_Feedback         Functional
66 cGEP17       Platelet                      Doublet
67 cGEP8        pDC                           Lineage
68 cGEP42       Ciliated_Cell                 Doublet
69 cGEP9        Macro_M2_Foam                 Lineage
70 cGEP2        Stress_HeatShock              Artifact
71 cGEP37       Macro_M2_Hypoxia              Functional
72 cGEP35       Tumor_Specific                Doublet
73 cGEP33       Epithelial_Prostate           Doublet
74 cGEP27       Macro_Glycolysis              Functional
75 cGEP31       Technical_High_MT             Artifact
76 cGEP30       Macro_M1_IL8_Ribosomal        Functional
77 cGEP53       Macro_Resident_State          Functional

In [4]:
final_combined_df <- Macro_gep_anno %>%
  left_join(gene_df, by = "cGEP_Cluster")
final_combined_df

   cGEP_Cluster cGEP_Anno_Name                Category
1  cGEP26       Macro_M1_ISG                  Functional
2  cGEP11       Doublet_T_Cell                Doublet
3  cGEP10       mregDC                        Lineage
4  cGEP49       Macro_M1_Inflammatory         Functional
5  cGEP13       Macro_Osteoclast-like         Lineage
6  cGEP51       Macro_M1_Early_Activation     Functional
7  cGEP16       Macro_M2_LAM                  Lineage
8  cGEP18       Macro_M2_Homeostasis          Lineage
9  cGEP44       Fibroblast                    Doublet
10 cGEP15       Doublet_NKT                   Doublet
11 cGEP50       Fibroblast                    Doublet
12 cGEP60       Epithelial_Tumor              Doublet
13 cGEP45       Epithelial_Tumor              Doublet
14 cGEP65       Epithelial_Tumor              Doublet
15 cGEP38       Macro_Cycling_G2M             Functional
16 cGEP19       Macro_M2_Resident_FOLR2       Lineage
17 cGEP22       Macro_M2_Iron                 Lineage
18 cGEP23       Mast_Cell                     Lineage
19 cGEP1        Macro_M1_Invasive             Functional
20 cGEP29       DC_cDC2                       Lineage
21 cGEP32       Macro_M2_C1Q                  Lineage
22 cGEP55       Artifact_RBC                  Artifact
23 cGEP40       B_Cell                        Doublet
24 cGEP34       Macro_M2_Scavenging           Lineage
25 cGEP41       DC_cDC1                       Lineage
26 cGEP47       Mono_CD16                     Lineage
27 cGEP48       Mono_CD14                     Lineage
28 cGEP14       Doublet_AT2_Stress            Doublet
29 cGEP57       Fibroblast                    Doublet
30 cGEP69       Fibroblast                    Doublet
⋮  ⋮            ⋮                             ⋮
48 cGEP24       Epithelial_Tumor              Doublet
49 cGEP66       Macro_M2_Remodeling           Lineage
50 cGEP36       Macro_Cycling_G1S             Functional
51 cGEP74       Acinar_Cell                   Doublet
52 cGEP56       Stress_EarlyResponse          Artifact
53 cGEP43       MHCII_Antigen_Processing      Functional
54 cGEP67       Macro_M2_Lipid                Lineage
55 cGEP7        Mono_CD16                     Lineage
56 cGEP4        Stress_HeatShock              Artifact
57 cGEP3        Tumor_Neura_Progenitor        Doublet
58 cGEP72       Myofibroblast_Smooth Muscle   Doublet
59 cGEP71       Plasma_Cell                   Doublet
60 cGEP64       Stromal_Endothelial           Doublet
61 cGEP73       Artifact_Stress_ISR           Artifact
62 cGEP28       Plasma_Cell_IgG               Doublet
63 cGEP62       Chaperone_Stress              Artifact
64 cGEP70       Macro_M1_Antigen_Presentation Lineage
65 cGEP77       Macro_M1_ISG_Feedback         Functional
66 cGEP17       Platelet                      Doublet
67 cGEP8        pDC                           Lineage
68 cGEP42       Ciliated_Cell                 Doublet
69 cGEP9        Macro_M2_Foam                 Lineage
70 cGEP2        Stress_HeatShock              Artifact
71 cGEP37       Macro_M2_Hypoxia              Functional
72 cGEP35       Tumor_Specific                Doublet
73 cGEP33       Epithelial_Prostate           Doublet
74 cGEP27       Macro_Glycolysis              Functional
75 cGEP31       Technical_High_MT             Artifact
76 cGEP30       Macro_M1_IL8_Ribosomal        Functional
77 cGEP53       Macro_Resident_State          Functional
   cGEP_signature
1  ISG15,GBP1,TNFSF10,IFIT3,CXCL10,IFIT1,MX1,CXCL11,IFITM3,IFIT2,IFI6,LY6E,HLA.B,EPSTI1,HLA.C,ISG20,RSAD2,IFI44L,LAP3,B2M,APOBEC3A,GBP4,CALHM6,IDO1,PPAPDC2,TYMP,IGLC1,STAT1,UBE2L6,OAS1
2  AC245427.1,IL32,CD3D,CD3E,PTPRCAP,TRAC,GZMA,CD2,TRBC2,CD3G,LCK,CCL5,LOC101929531,NKG7,CD7,TRBC1,GZMM,CTSW,KLRB1,CST7,SPOCK2,CD247,GZMH,CD27,AP002004.1,ETS1,GNLY,CD8A,PRF1,PCED1B-AS1
3  CCR7,FSCN1,LAMP3,BIRC3,LAD1,TXN,EBI3,CCL19,AL109741.1,MARCKSL1,IDO1,CCL22,AC007216.2,SLCO5A1,SINHCAF,HMSD,CD200,NUB1,GPR157,AOC1,TBC1D4,AC112719.2,LIMCH1,BX255923.3,RAB9A,PPA1,CSF2RA,DAPP1,BCL2L14,KIF2A
4  CCL3L3,CCL3,CCL4,IL1B,NFKBIA,CCL4L2,ZFP36,BCL2A1,CXCL3,TNF,PSME2,SOD2,CXCL2,IER3,KB-1507C5.4,PLAC8,CXCL8,SRGN,GADD45B,HLA-DRB1,HLA-DRA,GBP1,CH17-373J23.1,APOBEC3A,ATP5EP2,IFITM3,CD83,PPP1R15A,VAMP5,NCF1
5  CTSK,MMP9,CKB,SIGLEC15,SLC9B2,ACP5,AK5,NDRG4,CST3,AP000904.1,MT-RNR1,TCIRG1,THOP1,SPINK2,ANXA8L1,ATP6V0D2,S100A3,ITGB3,MYH16,RGS10,SLC22A1,HTRA3,DPP4,HSPB7,COL6A2,HYAL1,MTATP6P1,BAMBI,MT-RNR2,RP11-54O7.1
6  CCL3L1,CCL3,CCL3L3,CCL4,IL1B,CCL4L2,TNF,NFKBIA,CD83,PPP1R15A,ZFP36,JUN,GADD45B,FOS,IER2,IER3,ATF3,TNFAIP3,JUNB,KLF6,CXCL8,FOSB,RP3-393E18.2,NR4A1,DUSP2,IL1A,NFKBIZ,SOD2,SGK1,NR4A2
7  APOE,CTSD,GPNMB,APOC1,RP11-368J21.3,LGMN,CTSB,PSAP,C1QB,PLD3,ACP5,FTL,C1QC,LIPA,CD63,C1QA,PLA2G7,CD68,FUCA1,CAPG,PRDX1,RP11-696F12.1,ASAH1,GRN,CTSZ,TREM2,HLA-DRB4,LGALS3,CTSL,CTSC
8  MTRNR2L5,C1QB,NPC2,ATXN8OS,CD74,NAPSB,C1QC,TREM2,PCED1B-AS1,CTC-471J1.9,AL353644.10,B2M,PSME2P2,AC004448.5,HLA-DPA1,C1QA,HLA-DRA,TMSB4X,RP11-680H20.1,ALOX5AP,HLA-DRB1,FCER1G,HLA-DMB,UBBP4,COX6A1P2,FYB1,ATP5F1A,JPT1,VSIR,TYROBP
9  COL1A1,COL1A2,COL3A1,SPARC,LUM,RARRES2,DCN,SFRP2,AEBP1,RPS26,BGN,IGFBP7,CALD1,COL6A3,ACTA2,TIMP3,COL6A2,COMP,TAGLN,CTGF,MYL9,MGP,CCDC80,MMP11,TPM2,CTHRC1,COL6A1,NBL1,THBS2,CXCL14
10 NKG7,GZMB,GZMA,GNLY,FGFBP2,PRF1,CST7,CTSW,GZMH,KLRD1,SPON2,ADGRG1,CLIC3,HOPX,S1PR5,GZMM,IL2RB,CD247,XCL2,AL158071.4,TBX21,KIR2DL1,KLRF1,TRDC,CCL4,CD7,PTGDR,CD160,ZMAT4,PRSS23
11 COL3A1,COL1A2,COL1A1,DCX,RP11-166D19.1,LUM,SPARC,DCN,C8ORF4,POSTN,COL5A2,COL6A3,AC025822.2,COL5A1,COL6A2,CTHRC1,HAPLN1,CTGF,COL6A1,AEBP1,ISLR,CALD1,EGFL6,BGN,RP11-119F7.5,PCOLCE,MXRA5,WNT2,EPYC,HSPB1P1
12 TSPAN8,TFF1,AGR2,KRT19,FXYD3,ELF3,KRT8,S100P,EPCAM,MUC1,WFDC2,CEACAM6,TM4SF1,TMC5,SMIM22,KRT18,C19orf33,LMO7,AL033384.1,GPRC5A,TFF2,LGALS4,MAL2,CTSE,CLDN4,TM4SF4,SPINK1,CEACAM5,SLPI,OCIAD2
13 FXYD3,AKR1C2,PERP,S100A2,GPX2,KRT19,KRT6A,SFN,AKR1C1,AKR1C3,TACSTD2,KRT8,KRT18,CLDN4,AKR1B10,SOX2,NQO1,TM4SF1,KLF5,GAGE2A,S100A16,LY6D,KRT5,MAL2,GSTP1,DSP,AL162376.1,LIM2,C19orf33,EPCAM
14 LINC01986,KRT18,KRT8,MDK,YWHAE,WFDC2,SPINT2,CD24,ELF3,KRT19,EPCAM,CD47,RPL8,MMP7,PDZK1IP1,MTCH1,LCN2,HSP90AB1,RARRES1,TM4SF1,AL512274.1,LY6E,CLPS,C6orf132,BCAM,KRT17,CD9,BEX3,LHX1,ASRGL1
15 TOP2A,MKI67,UBE2C,TUBB,STMN1,AC091133.2,NUSAP1,KIAA0101,HIST1H4C,GSTM2P1,TUBA1B,CDC20,CENPF,BIRC5,HMMR,TPX2,CDKN3,HMGB2,TYMS,CDK1,H2AFZ,AURKB,HMGB1,ASPM,DLGAP5,CKS1B,GTSE1,CEP55,RRM2,CCNB2
16 C1QA,SELENOP,C1QB,C1QC,FOLR2,AC008945.2,DAB2,GGTA1P,CYTB,LGMN,SEPP1,SLCO2B1,SLC40A1,PLTP,MS4A4A,MAF,RNR2,CD163,A2M,STAB1,FCGRT,GIMAP1-GIMAP5,GPR126,RNASE1,ATP6,MRC1,MS4A7,SDC3,CTSC,KIAA0247
17 CSTB,GPNMB,FTL,AC106788.1,CTSD,CTSB,SPP1,ANXA2,CD63,LGALS3,TM4SF19,VIM,LGALS1,APOC1,CAPG,CTSL,CD68,CHI3L1,FABP5,MMP9,CYP27A1,CD9,FTH1,NUPR1,LIPA,GAPDH,FBP1,APOE,SDC2,CHIT1
18 AC090109.1,AC104964.2,TPSB2,Z84492.1,CPA3,AL357556.4,TPSAB1,HDC,RHEX,KIT,AC090236.2,SLC18A2,PRG2,MS4A2,C1ORF186,AC022960.1,HPGD,IL1RL1,GATA2,MAOB,AL645568.2,KCTD9P1,HDGFP1,CTSG,SIGLEC17P,TPSD1,SVOPL,RP11-354E11.2,ADCYAP1,AL161756.1
19 IL1B,PLAUR,C15ORF48,SRGN,SOD2,EREG,NAMPT,BCL2A1,CXCL8,CXCL2,G0S2,NFKBIA,BTG1,SAMSN1,AQP9,CXCL3,FTH1,TIMP1,OLR1,THBS1,PNRC1,CD44,IER3,NLRP3,C5AR1,CCL20,SAT1,TNFAIP3,SLC2A3,PTGS2
20 HLA-DPA1,CD74,HLA-DQB1,FCER1A,HLA-DPB1,PLD4,LOC100996809,HLA-DRB5,PKIB,GSN,HLA-DRA,NDRG2,CD1E,NAPSB,CD1C,CXorf36,HLA-DRB4,HLA-DRB1,ALOX5AP,CHAD,HLA-DQA2,RGS1,HLA-DQA1,HERPUD1,HLA-DMA,CDH17,PLEK2,CD207,FCGR2B,HLA-DQB2
21 C1QB,C1QA,C1QC,C3,PLTP,A2M,FCGBP,OLR1,RNASET2,SCIN,NR4A3,CTSB,SLC11A1,ATP1B3,SLC16A3,PADI2,ACSL1,SPP1,SLC2A5,LAPTM5,HIF1A,SLC7A5,GPR183,SCGB2A1,C1ORF54,TNFRSF1B,PLAUR,CD83,SNAP47-AS1,C5AR1
22 HBB,CA1,HBD,ESPN,HBA1,HBA2,AHSP,ALAS2,HBG1,HBM,SLC4A1,GYPA,GYPB,EPB42,MRC2,SLC25A37,SNCA,STRADB,SLC25A39,PRDX2,PDZK1IP1,BLVRB,CR2,DCAF12,FECH,SELENBP1,OSBP2,HEMGN,TMEM56,CDH1
23 LINC02397,CD79A,MS4A1,TCL1A,IGHM,FAM129C,LINC00926,FCRLA,IGHD,BLK,TNFRSF13C,EBF1,IGKC,VPREB3,FCER2,POU2AF1,CD19,FCRL1,TNFRSF13B,LINC01013,CD79B,BANK1,AL139020.1,PAX5,IGHV5-51,CD22,COBLL1,FAM30A,FCMR,PLEKHG1
24 GeneID:645079,LOC101928215,LOC101929371,MARCO,RBP4,FBP1,LOC100505592,GPD1,FABP4,RP11-77A13.1,GCHFR,MCEMP1,AOC3,ALDH2,LPL,AL109754.1,S100A11,FN1,LGALS3,PCOLCE2,LTA4H,CD52,VSIG4,GRN,CES1,APOC1,FTLP3,SERPINA1,C1QB,IGFBP2
25 RHEX,LINC02206,CLEC9A,LINC01724,AL118508.1,DNASE1L3,IDO1,CLNK,C1orf54,CADM1,CCND1,BFSP2,WDFY4,NAPSB,XCR1,CPNE3,GCSAM,SNX3,HLA-DOB,AL161645.1,PPY,RAB7B,AC080038.1,LINC01976,HLA-DPB1,AC060234.2,IRF8,AC016205.1,CNGB3,CPVL
26 FABP6,TRIM55,KCNK9,TSPY10,FCGR3A,MEG3,SPAG6,BMP4,LINC01781,PCGF2,RHOC,GRIK4,MIR99AHG,FRZB,RP11-1008C21.1,IGF1,LINC02362,KCNJ3,STEAP1,LINC01272,FAM27C,AL139002.1,CDKN1C,RPS19,HES4,NAP1L1,TMEM45A,AC109809.1,MS4A7,RP11-221J22.2
27 S100A9,SH3BGRL3,MYL6,EMP3,S100A8,ANXA2,SERF2,CD163,S100A11,S100A10,TIMP1,S100A6,FCER1G,MARCO,CFL1,LGALS1,AL445524.1,PFN1,S100A4,ACTB,SELENOT,SDF2L1,AP2S1,CD14,SLC39A8,RIPOR2,POMP,HSP90B1,CALR,NOP10
28 JUN,FOS,HSPA1B,DUSP1,SFTPC,SFTPA1,DNAJB1,RHOB,IER2,ATF3,KLF2,C1QA,C1QC,EGR1,HSPA1A,UBC,RGS1,GADD45B,ITM2B,C1QB,JUNB,ZFP36L2,NR4A2,KLF4,SEPP1,HERPUD1,HSP90AA1,GPR34,TXNIP,FCGR3A
29 DCN,FBLN1,MGP,IGFBP6,PLAC9,CCDC80,C1R,MFAP4,EFEMP1,CFD,C1S,SFRP1,DPT,SOD3,GSN,IGFBP5,ADH1B,LUM,PRELP,FGF7,WISP2,HSPB6,TIMP3,IGFBP4,OGN,PCOLCE2,SPARCL1,APOD,SERPINF1,PLD5
30 C14orf2,MT-CO2,MT-ATP6,RPL34,MT-ND2,RPS3A,RPS27A,MT-ND4,RPL7,MT-CYB,RPL39,RPS15A,RPL26,RPL21,RPS24,MT-ND5,RPL9,RPL30,RPS27,COX7B,MT-ND3,MT-CO3,S100A12,ATP5E,COL1A1,COL1A2,SUB1,ESD,LINC00998,RPS25
⋮  ⋮
48 KRT6A,KRT16,KRT6B,KRT6C,KRT14,PERP,LY6D,S100A7,KRTDAP,DMKN,AQP3,SFN,SBSN,TRIML1,LGALS7B,S100A14,KRT17,SERPINB4,S100A16,SPRR1B,S100A8,SERPINB3,KRT1,GJB2,DSP,OVOL1-AS1,KRT5,LINC01527,KRT10,PI3
49 CRABP2,CHI3L1,MMP7,COL22A1,MMP12,SPP1,TMEM114,CSTB,LPL,CHIT1,SLAMF9,SDC2,LINC02345,CD52,AC084809.2,FBP1,IFI6,PAQR5,AL117379.1,SPOCD1,AC015660.2,GPC4,AC244033.2,SLC12A8,CLVS1,MMP9,SH3BGRL3,HCST,ATP6V0D2,RAC2
50 MCM10,TYMS,TK1,C2orf48,PCNA,CDC45,FAM111B,PCLAF,CLSPN,CDT1,DTL,HELLS,GINS2,H2AFZ,FEN1,MCM6,RRM2,DUT,CENPU,ATAD2,PKMYT1,CENPM,TUBB,CCNE2,MYBL2,ZWINT,CDC6,MCM4,DHFR,MCM3
51 CTRB2,CLPS,AC104046.1,CTRC,FTLP3,REG1A,FABP5P7,PRSS1,CPA1,PLA2G1B,CTRB1,MTND1P23,CPB1,PNLIP,CEL,CELA3A,SLC4A4,SYCN,FXYD2,FABP5P1,GP2,AC016739.1,TREM2,MTATP6P1,A2M,AMY2A,CPA2,FABP5,PNLIPRP1,CD9
52 DUSP1,AREG,FOS,SAMSN1,SOCS3,ZFP36,SRGN,IL1B,MAT2A,ZNF331,NAMPT,SERPINB2,RGS2,JUNB,TNFAIP3,CD55,THBS1,SLC2A3,FKBP5,CLEC4E,IL1R2,ACSL1,LITAF,MCL1,NR4A2,GK,SAT1,CDKN1A,FAM65B,LOC731424
53 HLA-DRB4,LOC100996809,PSME2,TMSB10,YWHAH,S100A11,HLA-DRB3,FAM26F,ACTB,PFN1,GSN,CD74,CFL1,ATP5G3,ANXA2,VCX2,OTULINL,ANGPTL8,TYMP,CRP,PSMB3,PSMB9,CTSH,TPI1,HLA-DQB1,VAMP8,CLEC10A,HLA-DMA,ANKRD22,PPIB
54 RP11-160O5.1,FABP4,GPC4,SPOCD1,CRABP2,LPL,TM4SF19,GDF15,SPP1,HOXB6,CHI3L1,TREM2,TIMP3,COL6A2,FCGBP,TBX1,GPNMB,EPB41L1,USP2,ITGA3,PLD3,APOE,GPR150,FABP5,CTSD,LIPA,CADM1,GOLGA7B,FTL,APOC1
55 AC079325.2,FCGR3A,LST1,C19ORF38,IFITM2,RPS19,RHOC,CNTN5,CDKN1C,C10ORF54,SMIM25,IFITM3,AC104809.2,AIF1,NDNF,C15ORF39,NAP1L1,AC104809.4,LINC01272,MS4A7,LOC100130520,TCF7L2,LINC02334,RP5-857K21.11,SERPINA1,COTL1,FCER1G,CD79B,LOC101928037,LOC100507639
56 DNAJB1,HSPA1B,HSPA1A,HSP90AA1,BAG3,HSPB1,HSPH1,HSP90AA2P,HSPD1,HSPA6,UBC,HSP90AB1,DNAJB1P1,JUN,DNAJA1,ZFAND2A,HSPE1,HSPA8,IER5,HSP90AA4P,DUSP1,DNAJA4,ZSCAN12P1,PCYT1B,PPP1R15A,ATF3,NR4A1,RGS2,UBB,HSPA7
57 FABP7,ZIC5,RP11-408N14.1,RP1-56K13.2,FGG,SPRR1B,PRSS57,DPP10,HOXD10,RPS18,RPS6,SFTPA1,SPRR2D,SFTPA2,AP001171.1,RPS23,RPS4X,RPL3,RPS3,POU3F3,RPS12,CLDN2,RPLP0,RPS5,NPM1,FGB,RPS2,RPS7,RPL10A,RP11-817J15.2
58 NDUFA4L2,WFDC1,MYLK,ACTA2,MCAM,PPP1R14A,COL4A1,RGS5,CAV1,IGFBP7,TAGLN,MYL9,TINAGL1,COL4A2,SPARCL1,PLN,COX4I2,CALD1,LURAP1L,AVPR1A,LHFP,CAP2,MYH11,LMOD1,KCNJ8,DKK3,EFHD1,COL18A1,PDLIM1,NOTCH3
59 IGKC,IGHGP,LY6K,IGHG1,SNHG25,SCGB1D2,S100A1,MT-ND1,IGHG3,PCP4,IGHG4,IGLC7,MT-ND2,FBXO2,MT-CO2,CD209,MT-ATP6,PART1,MT-ND4,IGHM,OLFM3,PNMT,IGLC3,CCL13,RPS20,DSCR8,MT-ND3,TNNT1,MT-ND5,HES1
60 SPARCL1,CLU,INMT,C1orf61,NTRK2,GPM6B,CPE,MT3,GFAP,PTN,PTPRZ1,ATP1B2,IL33,SLC1A2,TTYH1,TOMM20P1,ID4,ABCD2,GJA1,TRIL,CST3,ITM2C,TSC22D4,AQP4,LRRC4C,C17orf100,FBLN7,SPARC,AGT,SCG3
61 PPP1R15A,UBC,GADD45B,KLF4,NRIP3,JUN,HSPA6,IRS2,MAP1LC3B,ANXA1,HSPA1A,RGCC,HSPA1B,PHLDA2,ZBTB43,EIF1,SLC38A2,PHLDA1,IER2,FOSB,ARC,DUSP1,UBB,HSPA8,HMOX1,DNAJB1,CITED2,SGK1,CSRNP1,HCAR3
62 BX005266.2,IGKV1-6,IGHV3-15,IGKV1D-39,IGHV3OR16-13,MZB1,LOC102723766,IGKC,IGKV1D-16,IGHG1,JCHAIN,IGKV1-17,IGHV3-23,IGHG2,IGHG4,IGHG3,IGJ,IGKV1D-17,DERL3,AC007386.4,CH17-212P11.4,TNFRSF17,OR4C13,AC107464.3,IGHGP,IGKV3-20,FKBP11,RP11-16E12.2,CD27,IGHA1
63 HSPD1,HSPH1,HSPB1,FKBP4,BAG3,HSP90AA1,HSP90AB1,HSPA1A,CHORDC1,CACYBP,HSPA8,HSPE1,MRPL18,SERPINH1,AHSA1,HLA-DPB1,SNX3,DOK2,ZFAND2A,DNAJB6,TCP1,PTGES3,DNAJA1,DNAJB1,NUDC,SNAP23,ST13,P4HA1,HSPA4L,STIP1
64 AL935026.1,HLA-DQA1,LOR,HLA-DRB5,HLA-DQB1,IDO1,PPA1,CCR7,EDARADD,LAMP3,CST7,EBI3,FSCN1,NAPSB,TVP23A,LAD1,HLA-DPA1,CXCL9,SPIB,HLA-DRB1,CD207,HLA-DPB1,TIFAB,CD1E,BIRC3,CALHM6,CD74,PSME2,CLEC10A,AC008429.2
65 APOBEC3A,FFAR2,IL1RN,CXCL10,RP11-525A16.4,NRN1,CCL7,CTD-2001C12.1,AP000704.5,LILRA5,ESPN,APOBEC3B,IFIT1,CXCL11,FJX1,CALY,ISG15,CCL2,ACOX2,TNFSF10,RAB36,HSPA1A,GBP1,RP11-7F18.2,FCGR3B,TRAV17,ACTB,TRAV14DV4,KIAA1107,FKBP1C
66 FO538757.3,MPIG6B,PPBP,PF4,GNG11,GP9,TUBB1,SDPR,SPARC,CAVIN2,HRAT92,CMTM5,TREML1,SPTB,CLU,C6orf25,NRGN,HIST1H2AC,AP001189.1,ITGA2B,MYL9,SEPT5,GRAP2,TUBA8,TMEM40,DMTN,CTTN,RP11-678G14.3,PDLIM1,RP11-185E8.1
67 GZMB,CLEC4C,LILRA4,CLIC3,SMPD3,PACSIN1,LRRC26,TSPAN13,PTCRA,MZB1,ITM2C,IGJ,IRF7,TLR9,JCHAIN,RP11-73G16.2,IRF4,SCT,FAM129C,LOC101928123,C12orf75,TCL1A,PPP1R14B,CXCR3,DERL3,SPIB,LOC101929219,RP1-302G2.5,TCF4,MAP1A
68 CAPS,C9orf24,TSPAN19,CCDC160,SNTN,RP4-666F24.3,TMEM190,C20orf85,ACSBG1,FAM183A,CAPSL,C1orf194,PIFO,CFAP53,C5orf49,RSPH1,C11orf70,TPPP3,C10orf67,C9orf135,RSPH4A,AGR3,FAM216B,SLC23A1,RP4-625H18.2,HHLA2,SYT8,SLC6A14,ANKK1,PRMT8
69 ACP5,LGALS3,CALR,CD63,PLA2G7,FTL,CTSB,CTSD,TGFBI,PRDX1,FPR3,CAPG,CTSL,S100A11,FABP5,NPC2,YBX1,PSAP,PMP22,FABP5P7,IFI30,HSP90B1,APOE,AC026366.1,PPIB,ATP6V1F,ANXA2,PCOLCE2,HLA-DQA2,HLA-DRB5
70 HSP90AA1,HSPA1A,HSPB1,HSPA1B,DNAJB1,HSPE1,IER5,ZFAND2A,HSPD1,HSPH1,HSPA6,DUSP1,RHOB,BAG3,DNAJB4,RGS2,UBC,MTRNR2L2,HSP90AB1,AP000769.1,ND3,CLK1,KLF2,DNAJA4,UBB,DNAJA1,CACYBP,RPS4Y1,SH3BGRL3,SHISAL2A
71 HSP90AA2P,PLIN2,HSPE1-MOB4,ADM,CSTB,GAPDH,LDHA,HK2,HSP90AA1,DNAJB1,HSP90AA4P,SLC2A1,NUPR1,HSPH1,BNIP3,HSPA1A,SLC2A3,HILPDA,BAG3,FTH1,VIM,HSP90AB3P,ERO1A,HSPB1,ENO1,MIF,FTH1P8,NDRG1,HSPA1B,HSPB1P1
72 FAM212A,CCDC176,RP1-34B20.21,LINC00863,TMEM40,RP11-879F14.1,RP11-88H9.2,RAB27B,C10orf10,PTCRA,ACRBP,RP11-367G6.3,RP11-879F14.2,RGS18,FAM212B-AS1,TSC22D1,HIST1H2BJ,HEMGN,RGCC,HRAT92,NT5C3A,HIST1H2AC,PRUNE,SMOX,PCP2,CLDN5,LAT,LGALSL,RP11-501J20.5,SDPR
73 KLK2,KLK3,RDH11,ACPP,TMPRSS2,STEAP2,KL,SLC45A3,AZGP1,CPE,MME,MSMB,DHCR24,ORM1,DHRS7,BMPR1B-AS1,NKX3-1,STEAP1,FOXA1,NCAPD3,PLPP1,DSP,CDH1,SLC30A4,SLC44A4,SYT7,RAB3B,FXYD3,MLPH,LIFR
74 RPL26P19,RP11-20O24.4,GAPDH,RP13-258O15.1,VIM,S100A10,RPL9P9,EEF1A1P5,AC092484.1,MIF,RPL37A,AC011933.2,CSTB,TMSB4XP6,ENO1,MCEMP1,LDHA,FBP1,LGALS1,RP11-466H18.1,TPI1,S100A6,SH3BGRL3,RPL23AP74,RPS29,RPS27,RPL41,FTLP3,RP11-83J16.1,RPS28
75 MT-CO2,MT-CYB,MT-ATP6,MT-ND1,MT-ND4,MT-CO3,MT-CO1,MT-ND3,MT-ND5,MT-ND2,ND4L,ATP8,ND3,CYTB,COX3,MT-ND4L,XIST,COX2,COX1,ND1,ND5,ATP6,MALAT1,RNR2,RNA45S5,MTRNR2L12,ND6,LOC101928412,ND4,ND2
76 IL8,RPL13,RPL32,RP11-463O12.5,RPLP2,TPT1,RPS16,RPL10,RPS24,RPL34,RPLP1,RPL28,FOSB,MIR24-2,RPS14,RPS12,RPS18,RPL18A,RPS8,RPL13A,RPL30,RPS23,RPL11,RPL37,RPL26,RPL35A,RPS15A,RPL37A,RPL9,RPS3A
77 RGS1,SNHG7,CD37,RGS10,EEF1A1,EIF4A2,KRT5,YPEL3,SCUBE2,ZFP36L2,EPB41L4A-AS1,CEBPD,NPM1,CCNI,CDKN1C,HLA-DPB1,CIRBP,EVI2B,RPL3,TXNIP,RPS4X,HERPUD1,EVI2A,RPS3,RPL31,C10orf54,PCNXL2,C10orf11,DNAJB1,EEF2

In [5]:
#OUT_FILE <- "./3.1.Macro_GEP_Anno//3.3.Macro_cGEP_Anno_Complete_With_Genes.csv"
OUT_FILE <- '/sibcb1/bioinformatics/yangyue/project/immunotherapy/7.6.cNMF_menchmark/cGEP_signature/Macro_cGEP77_signature.csv'

write.csv(final_combined_df, OUT_FILE, row.names = FALSE)