In [4]:
import pandas as pd
import io

# =============================
# 1. 参数设置
# =============================
INPUT_FILE = "./3.cGEP_topgene/test/ALL_cGEP_top_genes_long_wide_by_cGEP1_70.csv"
OUT_FILE = "./3.cGEP_topgene/test/cGEP1_70_function_CD8_Spectra52_annotation.csv"

# =============================
# 2. 定义 52 个 Spectra GEP 参考集
# (直接使用字符串解析，方便复制粘贴)
# =============================
spectra_ref_text = """
CD4-CM	LIMS1, PASK, ITM2A, CORO1B, AB_CD278, TMSB4X, AB_CD126, AB_CD279, FYB1, AB_CD45RO, AB_CD109, AB_CD95, AB_CD28, KLRB1, TBC1D4, MAF, ARID5B, AQP3, TRIB2, RNASET2
CD4-Naive	CCR7, SELL, LEF1, AB_CD27-2, TCF7, ACTN1, AB_CD27-1, RPS13, AB_GP130, AB_CD109, GLTSCR2, FHIT, NOSIP, TXK, RPS3A, CHRM3-AS2, FAM65B, AB_CD7, RPL32, RPS8
CD8-EM	CMC1, GZMK, AB_CD244, CST7, CCL5, AB_TIGIT, EOMES, CD8A, AB_CD8a, CD8B, AB_KLRG1_MAFA, GZMM, SH2D1A, AB_CD8, DUSP2, DTHD1, KLRG1, CRTAM, LYST, CD160
CD8-Naive	LINC02446, CD8B, AB_CD8, S100B, NELL2, AB_CD8a, AB_CD73, AB_CD45RA, YBX3, CD248, REG4, ACTN1, AB_CD55, AIF1, NT5E, CLEC11A, CD8A, AB_CD314, LEF1, CCR7
CD8-Trm	LINC02446, ZNF683, AB_CD8a, CD8B, CD8A, HOPX, ITGA1, KLRC1, KLRC2, CCL5, CD7, LINC01871, AB_CD244, XCL1, CTSW, CD63, KLRD1, CLIC3, CD9, CD52
MAIT	SLC4A10, AB_TCR-V-7.2, KLRB1, NCR3, AB_CD161, CEBPD, AB_CD26, AB_CD195, IL23R, LTK, TLE1, CA2, ME1, AB_CD26-2, RORC, IL4I1, PRSS35, TRAV1-2, ZBTB16, CXCR6
TEMRA	KIR2DL3, KLRC2, TYROBP, KIR3DL2, KLRC3, KIR3DL1, KIR2DL1, AB_CD158b, SH2D1B, KIR2DL4, KLRF1, NCR1, AB_CD158, LAT2, AB_CD158e1, TRDV1, AB_CD56-1, TRDC, NCAM1, FCER1G
Tfh-1	TOX2, SMCO4, KSR2, PEG10, CXCR5, ANKRD34B, PVALB, PARD3, IL6ST, NTRK3, SLC7A10, LIMS2, POU2AF1, FZD3, EDN3, TSPAN12, SCGB3A1, CHI3L2, MAP7, GNG4
Tfh-2	LHFP, CD200, LINC01991, GNG4, LHFPL6, LINC01480, NMB, CXCL13, ICA1, IGFL2, SERPINE2, CPM, KSR2, DOK5, BTLA, MAP7, NEBL, LINC01281, MS4A6A, PGM2L1
Th1-Like	LYAR, GZMK, IFNG-AS1, IL7R, CXCR3, NSG1, PTGER2, TXNIP, AB_CXCR3, IGFBP3, ZFP36L2, MS4A1, CCL5, AB_CD127, GBP5, ITGA4, AB_CD49d, FXYD2, AB_CD49a, HOPX
Th17-Resting	CCR6, CTSH, TTC39C-AS1, PTPN13, PDE4D, AQP3, AB_CD196, TNFRSF4, LTB, CMTM6, IL7R, TNFSF13B, AB_CD26, AB_CD127, TNFRSF18, USP10, LGALS3, AB_mouseCD49f, RORC, TIMP1
Th2-Resting	NEFL, KRT1, PTGDR2, AB_CD49a, CDO1, GATA3, EDN3, AB_CD82, ZP1, GATA3-AS1, NRIP3, AB_CD102, TMPRSS11E, AB_CD99, FXYD7, TNFRSF4, C1orf162, FXYD5, CAPG, PKP2
Th22	CCR10, S100A10, LGALS1, LMNA, S100A6, S100A4, VIM, AIRE, PI16, LGALS3, S100A11, ANXA2, FUT7, AB_CD82, CRIP1, PLP2, CAPG, AB_CD194, TMSB10, AB_CD99
Tph	LAG3, LAIR2, SLC27A2, PDCD1, LINC01943, CD4, CTLA4, SRGN, CD7, AB_CD279, TNFRSF18, PTMS, HAVCR2, SMOX, RDH10, TIMP1, ZBED2, PLPP1, SPOCK2, BST2
Treg	FOXP3, AB_CD25, RTKN2, AB_CD39, IL2RA, FANK1, AB_CD95, IKZF2, CTLA4, TIGIT, STAM, HACD1, AB_CD194, HPGD, IL32, DUSP4, F5, ICA1, LAYN, TBC1D4
gdT	TRDV2, TRDC, AB_TCR-Vd2, TRGV9, KLRC1, TRGC1, AB_CD94, AB_TCR-V-9, AB_CD3-1, AB_CD3-2, TYROBP, KLRD1, AB_CD226-1, AB_CD43, ZBTB16, HOPX, KLRG1, KLRB1, AB_CD102, AB_CD119
BCL2/FAM13A	BCL2, FAM13A, CISH, PIM1, CDK6, MAL, SLC40A1, SOCS2, EDA, USP10, PTGER2, ADTRP, DACT1, LTB, TRAT1, DPP4, MDFIC, CD55, DST, PCED1B
CD172a/MERTK	TXNIP, AB_CD172a, AB_MERTK, AB_CD138-1, AB_CD324, CXCR4, AB_Siglec-8, AB_CD68, AB_Rat-IgG1-2, H1FX, AB_CD202b, PLP2, RPL30, AB_CD370, H3F3B, AB_Rat-IgG1-1, AB_CD275-1, RPS4Y1, AB_CD338, AB_CD45-2
CD40LG/TXNIP	CD40LG, TXNIP, FKBP5, CH25H, CRYBG1, AIM1, ZFP36L2, TNFSF8, IL7R, NR3C1, IL6ST, FYB1, ADAM19, CMTM8, DDIT4, ICOS, BTG1, SARAF, SOCS1, ITK
CTLA4/CD38	LGMN, AB_CD278, AB_CD38-1, CD59, LAG3, POU2AF1, RASGRP4, MAF, AB_CD275-1, TNFRSF1B, ZBTB32, MIR4435-2HG, CTLA4, LIMS1, PTMS, CD38, AB_CD223, KRT24, LINC01943, PLS3
CellCycle-G2M	CDC20, CCNB2, DLGAP5, PLK1, UBE2C, CCNB1, HMMR, BIRC5, CENPF, ASPM, TPX2, TOP2A, TROAP, KIF14, CENPA, CDKN3, MKI67, KIF20A, CEP55, CENPE
CellCycle-Late-S	HIST1H1B, HIST1H4C, HIST1H3G, HIST1H3B, RRM2, SPC25, CDCA5, NUSAP1, HIST1H2AJ, HJURP, TOP2A, HIST1H3F, TYMS, KIF15, PKMYT1, ESCO2, CDK1, E2F8, KIFC1, UBE2C
CellCycle-S	GINS2, TK1, TYMS, DTL, UHRF1, PCLAF, CLSPN, CDC45, MCM10, FAM111B, CDT1, CDC6, E2F1, PCNA, RRM2, MCM4, ASF1B, MCM2, CENPU, STMN1
Cytoskeleton	ACTB, ACTG1, PFN1, CFL1, CORO1A, MYL6, ARPC1B, CLIC1, ARPC2, TPM4, TMSB10, S100A4, TMSB4X, SH3BGRL3, LCP1, CNN2, MYL12A, COTL1, RAC2, ACTR3
Cytotoxic	FGFBP2, GZMH, NKG7, PRF1, PRSS23, CX3CR1, GZMB, ADGRG1, GNLY, SPON2, FCGR3A, PLEK, KLRD1, S1PR5, CST7, EFHD2, C1orf21, AB_CD57, FCRL6, ASCL2
Exhaustion	LAG3, HAVCR2, TIMD4, TMEM155, PTMS, GZMB, CADM1, SLC27A2, CD27, CD38, VCAM1, PRF1, GZMA, RAB38, NKG7, CD200R1, TSC22D1, APBB2, RDH10, SEMA4A
HLA	HLA-DRA, HLA-DRB1, CD74, HLA-DQA1, HLA-DQB1, HLA-DPA1, HLA-DRB5, AB_HLA-DR, HLA-DPB1, HLA-DMA, HLA-DQA2, HLA-DMB, MSC, AB_CD95, COTL1, CDCA7, GZMA, ANXA5, DUSP4, CD70
Heatshock	HSPA1A, HSP90AA1, HSPA1B, DNAJB1, HSPH1, HSPD1, HSPE1, HSP90AB1, CACYBP, HSPA8, DNAJA1, DNAJA4, HSPB1, ZFAND2A, HSPA6, UBB, MRPL18, FKBP4, CHORDC1, AHSA1
ICOS/CD38	AB_CD278, ACTG1, AB_CD71, AB_CD38-2, GAPDH, MIR4435-2HG, MXD4, NEAT1, AB_CD38-1, GBP2, SLC25A5, COTL1, TMSB10, TMSB4X, UCP2, CYTOR, CD52, S1PR4, MT1E, ACTB
IL10/IL19	CAV1, PTPN3, FXYD2, AB_CD38-2, IL19, MYB, IL10, TIMD4, SLC9A2, HAVCR2, HMOX1, PHF21B, ZBTB32, MIR4422HG, POU2AF1, COL19A1, AB_CD38-1, TMEM155, CD38, BTNL8
ISG	ISG15, MX1, IFIT3, IFI6, IFIT1, IFI44L, OAS1, RSAD2, XAF1, STAT1, LY6E, EPSTI1, OASL, IFIT2, HERC5, CMPK2, EIF2AK2, USP18, IFI44, MX2
Metallothionein	MT1X, MT2A, MT1E, MT1G, MT1H, MT1F, MT1M, CCNA1, SLC30A1, GRHL3, MT1A, TRAJ4, GNG4, FAXC, AB_CD71, IGSF3, CFAP58, CAVIN3, AB_HLA-DR, H2AZ1
Multi-Cytokine	CCL4, CCL4L2, CCL3, IFNG, XCL2, TNF, CCL3L3, XCL1, CCL3L1, TNFSF9, NFKBID, EGR2, IFIT2, FASLG, NR4A2, NR4A3, ZFP36L1, AB_CD57, CRTAM, PMAIP1
NME1/FABP5	NME1, FABP5, HSP90AB1, C1QBP, PAICS, HSPD1, ENO1, RAN, CCT5, NPM1, HSPE1, SRM, LDHA, PRDX1, DCTPP1, PPP1R14B, YBX1, CCT6A, NCL, IMPDH2
OX40/EBI3	EBI3, TNFRSF4, TNFRSF18, PRKCDBP, PKM, CCL22, PTP4A3, TNFRSF8, CAVIN3, DNPH1, NINJ1, LTA, CD82, XIRP1, SDC4, LINC01229, BHLHE40-AS1, VDR, SMS, SYNGR2
RGCC/MYADM	MYADM, ANXA1, LMNA, RGCC, TAGLN2, CRIP1, KLF6, S100A10, VIM, AHNAK, ATP2B1, CFAP20, TSC22D3, EZR, S100A11, JUND, ARL4A, TUBA1A, ADGRE5, PPP1R15A
SOX4/TOX2	SOX4, PRDM16, SERTAD4-AS1, MME, CASC15, SMIM24, CHST2, IGFBP2, GNG4, SPIB, VSIG4, TOX2, RAB32, LINC01222, AB_CD38-1, CD79A, VPREB1, DBN1, SLC12A8, TRDC
TIMD4/TIM3	TIMD4, HAVCR2, GZMB, LIM2, GZMA, LAG3, AB_CD38-1, CLIC3, APOBEC3H, SERPINE1, GNLY, IFI27, CD38, CCR5, AB_CD86, CCL5, MIR4435-2HG, OTOF, CD70, SLC27A2
Th17-Activated	IL26, IL17A, NMU, CREB3L3, COL5A3, IL17F, PKHD1, C2CD4B, CTSH, ADAM12, IL22, RORC, LCN6, AB_CD71, PTPRD, SMCO4, AB_CD146, PTPN13, TMPRSS3, CA10
Th2-Activated	HPGDS, IL17RB, CHDH, PTGDR2, LINC01229, GATA3-AS1, FSTL4, GAP43, BACE2, PKIB, CACNA1D, IL5, GATA3, SCN2A, CCR3, ZP1, ZG16B, CRLF2, KLRB1, LAT2
Translation	RPS18, RPS6, RPS12, RPL3, RPS3, RPS4X, RPL13, RPS3A, EEF1A1, RPLP1, RPS2, RPL10, RPS27A, RPL21, RPS14, RPS8, EEF1B2, RPL13A, RPL18A, RPS5
IEG	JUN, FOS, FOSB, IER2, DUSP1, EGR1, PPP1R15A, JUNB, BTG2, NFKBIA, GADD45B, ZFP36, CD69, NR4A1, H3-3B, DUSP2, SERTAD1, KLF6, H3F3B, EIF1
IEG2	JUNB, ZFP36, ZNF331, ZFP36L2, NR4A2, CXCR4, TNFAIP3, CREM, FTH1, SRGN, BTG1, DDIT4, TENT5C, DUSP2, SLC2A3, AREG, JUND, PIK3R1, DUSP5, BTG2
IEG3	YPEL5, JUNB, NR4A2, EIF1, PPP1R15A, ARL4A, TSC22D3, ZNF331, RNF139, AREG, DUSP1, BCAS2, FTH1, CYCS, CXCR4, NSMCE3, CSRNP1, AB_CD62L, JUND, TUBA1A
Mito	MT-CO2, MT-CYB, MT-CO3, MT-ATP6, MT-CO1, MT-ND3, MT-ND4, MT-ND5, MT-ND1, MT-ND2, MT-ND4L, MT-ATP8, MT-ND6, MALAT1, MTRNR2L12, NEAT1, LUC7L3, NKTR, AB_CD138-1, DDX17
Poor-Quality	LINC-PINT, MALAT1, SYNE2, MACF1, AHNAK, MYH9, SNHG14, GOLGB1, KIAA1551, SYNE1, PTPRC, HNRNPU, NEAT1, UTRN, SLFN5, ITGA4, RNF213, LCP1, DDX17, HNRNPA2B1
Doublet-Bcell	BANK1, CD22, IGHD, FCRL5, TCL1A, MEF2C, IGHM, ARHGAP24, IGKC, CD24, MS4A1, OSBPL10-AS1, FCRL1, CD19, COL19A1, FCRLA, MARCKS, CD79A, PAX5, BCL11A
Doublet-Fibroblast	LUM, COL1A2, COL3A1, DCN, FN1, MGP, SPARC, COL1A1, TIMP3, IGFBP7, PLA2G2A, SPARCL1, AB_CD196, CALD1, CTGF, C1S, PRG4, MMP2, CST3, CRTAC1
Doublet-Myeloid	S100A8, S100A9, LYZ, S100A12, VCAN, CST3, MNDA, FCN1, AB_CLEC12A, AB_CD33, AB_CD35, FCER1G, AB_Iglightchaink, IFI30, AB_CD11b-1, AB_CD32, AB_CD64, CD14, NEAT1, CSF3R
Doublet-Plasmablast	JCHAIN, IGKC, IGKV3-20, IGHG1, IGHG3, IGKV1-5, IGKV4-1, IGHA1, IGHV3-30, IGHV3-23, IGLV2-14, MZB1, IGHV4-39, IGKV3-11, IGHG4, IGLV3-1, IGLC2, IGLV3-21, IGHV5-51, IGHV3-7
Doublet-Platelet	PPBP, NRGN, TREML1, SPARC, TUBB1, CAVIN2, PF4, GNG11, MYL9, GP9, ITGA2B, F13A1, MPIG6B, CMTM5, CLU, PF4V1, AB_CD41, PTGS1, GP1BB, PRKAR2B
Doublet-RBC	HBA2, HBA1, HBB, HBM, AB_CD235ab, ALAS2, HBQ1, HBD, AHSP, CA1, MYL4, AB_CD71, SLC25A37, SLC4A1, SELENBP1, SNCA, PDZK1IP1, GYPA, AB_CD235a, HBG2
"""

# 将文本解析为字典
marker_dict = {}
for line in spectra_ref_text.strip().split('\n'):
    if not line.strip(): continue
    # 假设是用制表符或空格分割名字和基因列表
    parts = line.strip().split(maxsplit=1) 
    if len(parts) == 2:
        name = parts[0].strip()
        genes_str = parts[1].strip()
        # 清理基因名称，去除空格，构建集合
        gene_set = {g.strip() for g in genes_str.split(',')}
        marker_dict[name] = gene_set

print(f"✅ 成功加载 {len(marker_dict)} 个 Spectra 参考类型。")

# =============================
# 3. 读取 wide cGEP 表
# =============================
df = pd.read_csv(INPUT_FILE)

# =============================
# 4. 注释函数 (使用 Jaccard Index)
# =============================
def annotate_cgep_spectra(gene_list):
    input_genes = set(gene_list)
    
    # 初始化最高分
    best_score = 0
    best_match = "Unknown"
    overlap_count = 0
    overlap_genes = []
    
    for ref_name, ref_genes in marker_dict.items():
        # 计算交集
        intersection = input_genes & ref_genes
        if not intersection:
            continue
            
        # 计算 Jaccard Index (交集 / 并集)
        # Jaccard 比单纯看数量更准确，因为它考虑了参考集的大小
        # 比如 CellCycle 有很多基因，如果只看数量容易误判
        score = len(intersection) / len(input_genes | ref_genes)
        
        if score > best_score:
            best_score = score
            best_match = ref_name
            overlap_count = len(intersection)
            overlap_genes = list(intersection)
            
    # 如果完全没有匹配
    if best_match == "Unknown":
        return {
            "Spectra_Label": "Unknown",
            "Overlap_Count": 0,
            "Jaccard_Score": 0,
            "Key_Markers": ""
        }
        
    return {
        "Spectra_Label": best_match,
        "Overlap_Count": overlap_count,
        "Jaccard_Score": round(best_score, 4),
        "Key_Markers": ",".join(overlap_genes[:5]) # 仅展示前5个重叠基因
    }

# =============================
# 5. 执行注释
# =============================
results = []

for cgep in df.columns:
    # 获取当前 cGEP 的非空基因列表
    genes = (
        df[cgep]
        .dropna()
        .astype(str)
        .tolist()
    )
    
    # 运行注释
    anno = annotate_cgep_spectra(genes)
    
    results.append({
        "cGEP": cgep,
        "Spectra_Label": anno["Spectra_Label"],   # 52个分类名称
        "Overlap_Count": anno["Overlap_Count"],   # 命中几个基因
        "Jaccard_Score": anno["Jaccard_Score"],   # 相似度打分
        "Key_Markers": anno["Key_Markers"],       # 具体的重叠基因
        "Top_genes_in_cGEP": ",".join(genes[:10]) # cGEP里原本的前10个基因
    })

# =============================
# 6. 输出结果
# =============================
out_df = pd.DataFrame(results)

# 将结果按 Score 降序查看一下（可选）
# out_df = out_df.sort_values(by="Jaccard_Score", ascending=False)

out_df.to_csv(OUT_FILE, index=False)

print("✅ 注释完成")
print(f"输出文件: {OUT_FILE}")
print(out_df[["cGEP", "Spectra_Label", "Overlap_Count"]].head()) # 打印前几行预览

✅ 成功加载 52 个 Spectra 参考类型。
✅ 注释完成
输出文件: ./3.cGEP_topgene/test/cGEP1_70_function_CD8_Spectra52_annotation.csv
    cGEP Spectra_Label  Overlap_Count
0  cGEP1   Translation             10
1  cGEP2           ISG             20
2  cGEP3          Mito             11
3  cGEP4   Translation             12
4  cGEP5          Mito             12

In [31]:
df

,cGEP,Spectra_Label,Overlap_Count,Jaccard_Score,Key_Markers,Top_genes_in_cGEP
0,cGEP1,Translation,10,0.2500,"RPS6,EEF1A1,RPS18,RPL18A,RPL13","TotalSeqC0953,RP11-864N7.2,RP11-234A1.1,RP11-4..."
1,cGEP2,ISG,20,0.6667,"XAF1,IFI6,LY6E,MX1,OAS1","ISG15,MX1,IFI6,IFIT3,IFIT1,RSAD2,OAS1,IFI44L,I..."
2,cGEP3,Mito,11,0.2821,"MT-ND2,MT-CO3,MT-CO1,MT-ND5,MT-CO2","CYTB,ATP6,COX3,ND4L,COX2,ND1,ND5,ND2,ATP8,RPS14P3"
3,cGEP4,Translation,12,0.3158,"RPS6,RPL3,EEF1A1,RPS18,RPL13","RPL13P12,TotalSeqC0952,EEF1A1,TotalSeqC0955,RP..."
4,cGEP5,Mito,12,0.3158,"MT-ND2,MT-CO3,MT-CO1,MT-ND5,MT-CO2","MT-ND4,MT-CO2,MT-CO3,MT-ATP6,MT-CYB,MT-CO1,MT-..."
...,...,...,...,...,...,...
65,cGEP66,CD172a/MERTK,3,0.0638,"RPS4Y1,H1FX,H3F3B","MTRNR2L8,RPS4Y1,DDX3Y,H3F3B,MALAT1,CCNL1,NR4A2..."
66,cGEP67,Th2-Activated,1,0.0204,PKIB,"LINC01531,SEMA3B,PANK1,GPR37,ADSSL1,RP11-176H8..."
67,cGEP68,Cytotoxic,6,0.1364,"GZMB,GNLY,FCGR3A,NKG7,FGFBP2","HLA-H,CYTB,ND4,HLA-A,ND4L,ATP6,ATP8,ND2,ND1,NKG7"
68,cGEP69,Translation,3,0.0638,"EEF1A1,RPS8,RPS18","IGHGP,ID4,LY6K,TUBB,RPS20,RPL29,RAB13,TM4SF1,E..."
69,cGEP70,SOX4/TOX2,1,0.0204,SLC12A8,"AFF3,ZFP41,MT.ND3,BEND6,EVI5,PLEKHG6,UBD,MT.ND..."

In [8]:
out_df2 = out_df.sort_values(by="Jaccard_Score", ascending=False)
#out_df2.to_csv("./3.cGEP_topgene/cGEP1_70_function_CD8_Spectra52_annotation_sort.csv", index=False)

In [16]:
out_df2

,cGEP,Spectra_Label,Overlap_Count,Jaccard_Score,Key_Markers,Top_genes_in_cGEP
1,cGEP2,ISG,20,0.6667,"IFIT1,EPSTI1,MX2,IFI6,OASL","ISG15,MX1,IFI6,IFIT3,IFIT1,RSAD2,OAS1,IFI44L,I..."
35,cGEP36,Translation,16,0.4706,"RPS4X,EEF1B2,RPS18,RPS2,RPS5","RPS2,RPL13,RPS12,RPS18,RPL10A,RPS14,RPL32,RPS4..."
22,cGEP23,Cytoskeleton,15,0.4286,"S100A4,PFN1,ACTG1,SH3BGRL3,TMSB4X","TMSB4XP4,ACTB,S100A4,PFN1,CD52,ACTG1,TMSB4X,SH..."
6,cGEP7,Heatshock,15,0.4286,"HSPE1,CACYBP,DNAJA1,UBB,HSPA8","RP11-1033A18.1,DNAJB1,HSP90AA1,HSPA1A,RP11-485..."
8,cGEP9,Doublet-RBC,15,0.4286,"CA1,HBD,HBA1,HBG2,HBB","HBB,HBD,AHSP,SNCA,CA1,HBA2,ALAS2,HBA1,SLC4A1,S..."
...,...,...,...,...,...,...
17,cGEP18,Treg,1,0.0204,HPGD,"CPA3,TPSAB1,TPSB2,AP000781.2,MS4A2,HPGDS,SLC18..."
50,cGEP51,Th22,1,0.0204,S100A11,"KRT7,LINC01681,SPATA22,SLPI,TMC5,PADI2,SALL2,S..."
15,cGEP16,CD8-Trm,1,0.0204,CD52,"ONECUT2,DMBT1,KRT20,HRCT1,ALDOB,OLFM4,MEP1A,FA..."
66,cGEP67,Th2-Activated,1,0.0204,PKIB,"LINC01531,SEMA3B,PANK1,GPR37,ADSSL1,RP11-176H8..."
69,cGEP70,SOX4/TOX2,1,0.0204,SLC12A8,"AFF3,ZFP41,MT.ND3,BEND6,EVI5,PLEKHG6,UBD,MT.ND..."

In [15]:
#len(out_df2.value_counts('Spectra_Label'))#37个
out_df2.value_counts('Spectra_Label')

Spectra_Label
Translation            7
Doublet-Myeloid        5
Mito                   5
CD8-Trm                5
HLA                    4
Cytoskeleton           3
IEG2                   2
Th22                   2
CD40LG/TXNIP           2
CD8-EM                 2
SOX4/TOX2              2
IEG                    2
Exhaustion             2
CellCycle-S            2
Cytotoxic              2
Treg                   2
BCL2/FAM13A            1
CD172a/MERTK           1
CD4-Naive              1
Doublet-Bcell          1
CTLA4/CD38             1
Heatshock              1
Doublet-Fibroblast     1
Doublet-Plasmablast    1
Doublet-RBC            1
CellCycle-Late-S       1
CellCycle-G2M          1
ISG                    1
IL10/IL19              1
RGCC/MYADM             1
Multi-Cytokine         1
Metallothionein        1
MAIT                   1
Th2-Activated          1
Th17-Resting           1
TEMRA                  1
Tph                    1
Name: count, dtype: int64

In [ ]:
#？GEP 注释到同一个Spectra_Label 要如何合并

In [2]:
import pandas as pd

# 假设 df 是你上一步生成的包含 'Spectra_Label' 的 DataFrame
df = pd.read_csv("./3.cGEP_topgene/cGEP1_70_function_CD8_Spectra52_annotation.csv")

# ==========================================
# 定义 细分类型 -> 宏观类别 的映射字典
# ==========================================
category_map = {
    # --- 1. Naive, Memory & Residency (分化与记忆) ---
    "CD8-Naive": "Naive/Memory",
    "CD8-EM": "Naive/Memory",
    "CD8-Trm": "Naive/Memory",
    "BCL2/FAM13A": "Naive/Memory",  # 存活/记忆相关
    
    # --- 2. Exhaustion & Dysfunction (耗竭) ---
    "Exhaustion": "Exhaustion",
    "Progenitor_exhausted": "Exhaustion", # 如果有的话
    "TIMD4/TIM3": "Exhaustion",
    "SOX4/TOX2": "Exhaustion",
    "CTLA4/CD38": "Exhaustion",
    "CD172a/MERTK": "Exhaustion",
    "ICOS/CD38": "Exhaustion",
    "CD40LG/TXNIP": "Exhaustion", # 也是一种激活/功能障碍状态
    "OX40/EBI3": "Exhaustion",     # 激活/耗竭伴随

    # --- 3. Cytotoxicity & Effector (杀伤与效应) ---
    "Cytotoxic": "Cytotoxicity",
    "TEMRA": "Cytotoxicity",
    "MAIT": "Cytotoxicity",
    "gdT": "Cytotoxicity",
    "Th1-Like": "Cytotoxicity", # CD8里也有Th1-like特征
    "Multi-Cytokine": "Cytotoxicity",
    "HLA": "Cytotoxicity", # 抗原呈递/激活
    "RGCC/MYADM": "Cytotoxicity", # 组织迁移/效应

    # --- 4. CD4 Helper & Treg (CD4 辅助/调节) ---
    # (如果是纯 CD8 数据，这些可能代表亚群污染或特殊的 CD8 状态)
    "Treg": "Treg/Helper",
    "Tfh-1": "Treg/Helper",
    "Tfh-2": "Treg/Helper",
    "Th17-Resting": "Treg/Helper",
    "Th17-Activated": "Treg/Helper",
    "Th2-Resting": "Treg/Helper",
    "Th2-Activated": "Treg/Helper",
    "Th22": "Treg/Helper",
    "Tph": "Treg/Helper",

    # --- 5. Cell Cycle (细胞周期) ---
    "CellCycle-G2M": "Cell Cycle",
    "CellCycle-S": "Cell Cycle",
    "CellCycle-Late-S": "Cell Cycle",

    # --- 6. Interferon & Inflammation (干扰素/炎症) ---
    "ISG": "Interferon/Inflammation",
    "IEG": "Interferon/Inflammation", # 早期响应基因
    "IEG2": "Interferon/Inflammation",
    "IEG3": "Interferon/Inflammation",
    "IFN_response": "Interferon/Inflammation",

    # --- 7. Metabolism & Stress (代谢与应激) ---
    "Translation": "Metabolism & Stress",
    "Ribosome": "Metabolism & Stress",
    "Heatshock": "Metabolism & Stress",
    "Mito": "Metabolism & Stress",
    "Metallothionein": "Metabolism & Stress",
    "NME1/FABP5": "Metabolism & Stress", # 代谢活跃
    "Cytoskeleton": "Metabolism & Stress",
    "IL10/IL19": "Metabolism & Stress", # 抑制性因子/应激

    # --- 8. Artifacts/QC (双细胞/低质量) ---
    "Doublet-Bcell": "Artifacts",
    "Doublet-Fibroblast": "Artifacts",
    "Doublet-Myeloid": "Artifacts",
    "Doublet-Plasmablast": "Artifacts",
    "Doublet-Platelet": "Artifacts",
    "Doublet-RBC": "Artifacts",
    "Poor-Quality": "Artifacts",
    
    # 兜底
    "Unknown": "Unknown"
}

# ==========================================
# 执行合并
# ==========================================

# 1. 映射新列
df["Broad_Category"] = df["Spectra_Label"].map(category_map)

# 2. 检查是否有没映射上的（防止拼写错误）
missing = df[df["Broad_Category"].isna()]["Spectra_Label"].unique()
if len(missing) > 0:
    print(f"⚠️ 警告: 以下标签未在字典中找到映射关系: {missing}")
    # 填充空值为 'Other'
    df["Broad_Category"] = df["Broad_Category"].fillna("Other")

# 3. 统计一下每个大类的数量
print("\n📊 合并后的类别统计:")
print(df["Broad_Category"].value_counts())

# 4. 保存结果
df.to_csv("./3.cGEP_topgene/cGEP_Annotated_Merged.csv", index=False)

⚠️ 警告: 以下标签未在字典中找到映射关系: ['CD4-Naive']

📊 合并后的类别统计:
Broad_Category
Metabolism & Stress        18
Cytotoxicity               10
Artifacts                   9
Exhaustion                  8
Naive/Memory                8
Treg/Helper                 7
Interferon/Inflammation     5
Cell Cycle                  4
Other                       1
Name: count, dtype: int64

In [3]:
df

,cGEP,Spectra_Label,Overlap_Count,Jaccard_Score,Key_Markers,Top_genes_in_cGEP,Broad_Category
0,cGEP1,Translation,10,0.2500,"RPL18A,RPS18,RPS8,RPS12,RPS3A","TotalSeqC0953,RP11-864N7.2,RP11-234A1.1,RP11-4...",Metabolism & Stress
1,cGEP2,ISG,20,0.6667,"IFIT1,EPSTI1,MX2,IFI6,OASL","ISG15,MX1,IFI6,IFIT3,IFIT1,RSAD2,OAS1,IFI44L,I...",Interferon/Inflammation
2,cGEP3,Mito,11,0.2821,"MT-ND5,MT-ND4L,MT-ND2,MT-CYB,MT-ND4","CYTB,ATP6,COX3,ND4L,COX2,ND1,ND5,ND2,ATP8,RPS14P3",Metabolism & Stress
3,cGEP4,Translation,12,0.3158,"RPS4X,RPS18,RPS8,RPS12,RPLP1","RPL13P12,TotalSeqC0952,EEF1A1,TotalSeqC0955,RP...",Metabolism & Stress
4,cGEP5,Mito,12,0.3158,"MT-ND5,MT-ND4L,MT-ND2,MT-CYB,MT-ND4","MT-ND4,MT-CO2,MT-CO3,MT-ATP6,MT-CYB,MT-CO1,MT-...",Metabolism & Stress
...,...,...,...,...,...,...,...
65,cGEP66,CD172a/MERTK,3,0.0638,"H1FX,H3F3B,RPS4Y1","MTRNR2L8,RPS4Y1,DDX3Y,H3F3B,MALAT1,CCNL1,NR4A2...",Exhaustion
66,cGEP67,Th2-Activated,1,0.0204,PKIB,"LINC01531,SEMA3B,PANK1,GPR37,ADSSL1,RP11-176H8...",Treg/Helper
67,cGEP68,Cytotoxic,6,0.1364,"FGFBP2,NKG7,GZMH,FCGR3A,GNLY","HLA-H,CYTB,ND4,HLA-A,ND4L,ATP6,ATP8,ND2,ND1,NKG7",Cytotoxicity
68,cGEP69,Translation,3,0.0638,"RPS18,EEF1A1,RPS8","IGHGP,ID4,LY6K,TUBB,RPS20,RPL29,RAB13,TM4SF1,E...",Metabolism & Stress
69,cGEP70,SOX4/TOX2,1,0.0204,SLC12A8,"AFF3,ZFP41,MT.ND3,BEND6,EVI5,PLEKHG6,UBD,MT.ND...",Exhaustion

# 合并细胞评分矩阵 (Usage Matrix

In [6]:
import pandas as pd

# 1. 读取注释结果
df = pd.read_csv("./3.cGEP_topgene/test/cGEP1_70_function_CD8_Spectra52_annotation.csv")

# 2. 这里的输入数据应该是长格式或者你刚才生成的包含 Top_genes 字符串的表
# 假设 df 里有一列 'Top_genes_in_cGEP' (逗号分隔的字符串)

merged_rows = []

# 按 Spectra_Label 分组 (这就是你的 37 个类)
for label, group in df.groupby("Spectra_Label"):
    
    # 获取这个 label 下所有 cGEP 的 Top 基因
    all_genes = []
    cgep_sources = []
    
    for _, row in group.iterrows():
        # 把字符串 "A,B,C" 变成列表 ['A','B','C']
        genes = row['Top_genes_in_cGEP'].split(',')
        all_genes.extend(genes)
        cgep_sources.append(row['cGEP'])
    
    # 去重 (set)，然后再转回列表
    unique_genes = list(set(all_genes))
    
    # 也可以按出现频率排序（可选）：越是多个模块共有的基因越重要
    # 这里简单处理，直接去重
    
    merged_rows.append({
        "Spectra_Label": label,
        "Merged_Top_Genes": ",".join(unique_genes),
        "Num_Genes": len(unique_genes),
        "Source_cGEPs": ",".join(cgep_sources), # 记录一下是由哪些 cGEP 合并来的
        "Num_Modules_Merged": len(cgep_sources)
    })

# 3. 输出合并后的 37 个类
out_df = pd.DataFrame(merged_rows)
#out_df.to_csv("./3.cGEP_topgene/Spectra37_Merged_GeneList.csv", index=False)

print("✅ 基因列表合并完成！")
print(out_df[["Spectra_Label", "Num_Modules_Merged"]].head())

✅ 基因列表合并完成！
  Spectra_Label  Num_Modules_Merged
0   BCL2/FAM13A                   1
1  CD172a/MERTK                   1
2     CD4-Naive                   1
3  CD40LG/TXNIP                   2
4        CD8-EM                   2

In [7]:
out_df

,Spectra_Label,Merged_Top_Genes,Num_Genes,Source_cGEPs,Num_Modules_Merged
0,BCL2/FAM13A,"AK4,MYC,LDHA,ENO1,PGK1,MIF,ALDOA,IL9R,DNTT,PKM",10,cGEP58,1
1,CD172a/MERTK,"RPS4Y1,DDX3Y,MTRNR2L8,NR4A2,MALAT1,CCNL1,SRSF7...",10,cGEP66,1
2,CD4-Naive,"TSHZ2,CTB-133G6.1,LHFPL6,GLTSCR2,SPON1,IGFL2,S...",10,cGEP41,1
3,CD40LG/TXNIP,"CD97,ELOB,ATP5MD,ATP5MG,RIPOR2,AC007349.2,TRIR...",20,"cGEP25,cGEP31",2
4,CD8-EM,"RPS7,RPL23A,ATP5E,GZMK,RARRES3,CCL5,RPL28,CD8A...",20,"cGEP20,cGEP29",2
5,CD8-Trm,"KIR2DL4,GABARAPL1,FOSL2,CREM,GZMB,LRRC34,LOC10...",43,"cGEP16,cGEP40,cGEP45,cGEP59,cGEP62",5
6,CTLA4/CD38,"SLC52A3,FGFR3,SLC2A5,AGR2,PDLIM3,LINC01297,VAN...",10,cGEP63,1
7,CellCycle-G2M,"KIAA0101,FGGY,KIF15,DEPDC1,KIF14,TUBA1B,AC2535...",10,cGEP56,1
8,CellCycle-Late-S,"PCLAF,TOP2A,STMN1,BIRC5,TUBB,MKI67,RRM2,C15ORF...",10,cGEP21,1
9,CellCycle-S,"KIAA0101,GATA2,TYMS,MS4A2,PCLAF,HPGDS,STMN1,RR...",20,"cGEP37,cGEP65",2
10,Cytoskeleton,"TRAV8-1,ATP5E,GNLY,S100A6,TMSB4X,TMSB10,TMSB4X...",24,"cGEP8,cGEP12,cGEP23",3
11,Cytotoxic,"GNLY,ATP6,AC245427.1,ATP8,GPR56,FCGR3A,ND4,SPO...",19,"cGEP27,cGEP68",2
12,Doublet-Bcell,"AL096701.2,MEF2C,CD79A,VPREB3,TCL1A,MS4A1,CD74...",10,cGEP14,1
13,Doublet-Fibroblast,"LUM,POSTN,COL1A2,COL6A1,CAPN6,DCN,COL3A1,SGCD,...",10,cGEP61,1
14,Doublet-Myeloid,"C1QA,KRT19,KRT13,CST3,S100A8,SPI1,CST6,S100A6,...",44,"cGEP13,cGEP38,cGEP39,cGEP48,cGEP53",5
15,Doublet-Plasmablast,"IGKV1OR2-108,IGHG1,IGKC,MZB1,IGHV5-10-1,JCHAIN...",10,cGEP24,1
16,Doublet-RBC,"AHSP,HBD,HBA2,SELENBP1,HBA1,CA1,HBB,SNCA,SLC4A...",10,cGEP9,1
17,Exhaustion,"HMOX1,AC069363.1,SNAP47,IFI6,CD27,CTLA4,CST7,P...",17,"cGEP22,cGEP35",2
18,HLA,"HLA-DRB5,CST3,GNLY,ZNF683,CD74,PRMT9,LOC101929...",31,"cGEP26,cGEP32,cGEP52,cGEP54",4
19,Heatshock,"HSPH1,DNAJB1,HSPD1,HSPE1,HSP90AA1,RP11-1033A18...",10,cGEP7,1
20,IEG,"JUN,DNAJB1,NR4A1,PPP1R15A,FOS,JUNB,HSPA1A,TSC2...",18,"cGEP11,cGEP33",2
21,IEG2,"BRE-AS1,CREM,FTH1,24h.2,CST7,8h.2,ZFP36L2,FYN,...",17,"cGEP34,cGEP44",2
22,IL10/IL19,"TRBV12-4,NPW,ST8SIA3,PTPN3,CD81,RP11-522I20.3,...",10,cGEP55,1
23,ISG,"IFI6,IFIT1,LY6E,MX1,OAS1,RSAD2,IFIT3,ISG15,ISG...",10,cGEP2,1
24,MAIT,"KLRB1,AMICA1,SLC4A10,IL7R,CCR6,NCR3,LTB,DUSP1,...",10,cGEP10,1
25,Metallothionein,"MRAP2,LCN2,TLCD2,PLA2G4F,AKR1B10,RAET1L,CRCT1,...",10,cGEP60,1
26,Mito,"ATP6,ATP8,RARRES2,JUND,MT-CO1,COX2,ND4,ND5,CYT...",31,"cGEP3,cGEP5,cGEP30,cGEP47,cGEP57",5
27,Multi-Cytokine,"GZMK,CD27,CCL4L2,TMEM155,CCL3L3,TNS3,TRAV19,FX...",10,cGEP28,1
28,RGCC/MYADM,"MYADM,S100A10,S100A11,ANXA1,RGCC,CRIP1,ADGRE5,...",10,cGEP46,1
29,SOX4/TOX2,"MT.ND3,GZMB,DNASE1L3,BHLHB9,IL3RA,ASIP,AFF3,BE...",20,"cGEP43,cGEP70",2
30,TEMRA,"CRISPLD1,NTM,HDC,GNLY,XCL2,RP11-354E11.2,SPTSS...",10,cGEP17,1
31,Th17-Resting,"KLRB1,PTPN13,CCR6,S100A6,CTSH,LGALS3,SPOCK2,S1...",10,cGEP49,1
32,Th2-Activated,"S100A1,EMILIN1,RP11-176H8.1,SEMA3B,ZNF202,LINC...",10,cGEP67,1
33,Th22,"SLPI,PADI2,LTB,SPATA22,S100A10,HIST1H4C,TMC5,K...",20,"cGEP50,cGEP51",2
34,Tph,"GZMB,LAYN,ENTPD1,GAPDH,TNFRSF18,KRT86,TIGIT,AC...",10,cGEP6,1
35,Translation,"RPL31,AL162511.1,RPL32,RP11-234A1.1,RPS18,ZG16...",58,"cGEP1,cGEP4,cGEP15,cGEP36,cGEP42,cGEP64,cGEP69",7
36,Treg,"SLC18A2,GATA2,AP000781.2,AC004791.2,MS4A2,IL1R...",20,"cGEP18,cGEP19",2

In [11]:
gep_52info = pd.read_csv('gep_52info_class.csv')
gep_52info

,cGep_Name,Old_Short_Name,Long_Name,Short_Name,Shortest_Name,Class
0,COMBAT_Cytoskeleton,Cytoskeleton,Actin Cytoskeleton,Cytoskeleton,Cytosk.,Functional
1,CD8_EM,CD8-EM,CD8 Effector Memory,CD8-EM,CD8-EM,Lineage
2,CellCycle-G2M,CellCycle-G2M,Cell Cycle G2M Phase,CellCycle-G2M,G2M-phase,Functional
3,CellCycle-S,CellCycle-S,Cell Cycle S Phase,CellCycle-S,S-phase,Functional
4,Cytotoxic,Cytotoxic,Cytotoxic,Cytotoxic,Cytotoxic,Functional
5,Doublet-RBC,Doublet-RBC,Doublet RBC,Doublet-RBC,Dbt-RBC,Doublet Lineage
6,ISG,ISG,Interferon Stimulated Genes,ISG,ISG,Functional
7,MAIT,MAIT,MAIT,MAIT,MAIT,Lineage
8,Treg,Treg,Treg,Treg,Treg,Lineage
9,CD4-Naive_TBRU,CD4-Naive,CD4 Naive,CD4-Naive,CD4-Naive,Lineage
10,CellCycle-Histone,CellCycle-Late-S,Cell Cycle Late S-phase,CellCycle-Late-S,Late-S-phase,Functional
11,HLA,HLA,HLA,HLA,HLA,Functional
12,HeatShock2,Early-Activation,NME1/FABP5,NME1/FABP5,NME1/FABP5,Functional
13,IEG_IEG-Blood_IEG-Tissue,IEG,Immediate Early Gene,IEG,IEG,Artifact
14,MALAT1_TBRU,MALAT1,Poor Quality,Poor-Quality,Poor-Quality,Artifact
15,CD4-Naive_Translation,Translation,Translation,Translation,Translation,Functional
16,KLRC2/GNLY_gdT,NK-like,TEMRA,TEMRA,TEMRA,Lineage
17,CD4 TCM_Tfh,CD4-CM,CD4 T Central Memory,CD4-CM,CD4-CM,Lineage
18,Doublet-Platelet,Doublet-Platelet,Doublet Platelet,Doublet-Platelet,Dbt-Platelet,Doublet Lineage
19,IL10/CD38,IL10/IL19-Secretion,IL10/IL19,IL10/IL19,IL10/IL19,Functional
20,RGCC/MYADM_S100A10/LMNA,RGCC/MYADM,RGCC/MYADM,RGCC/MYADM,RGCC/MYADM,Functional
21,MALAT1_Mito,Mito,Mitochondrial Genes,Mito,Mito,Artifact
22,AMP-RA_Doublet-Plasma,Doublet-Plasmablast,Doublet Plasmablast,Doublet-Plasmablast,Dbt-Plasmablast,Doublet Lineage
23,gdT-Blood,gdT-Blood,Gamma Delta T,gdT,gdT,Lineage
24,Metallothionein,Metallothionein,Metallothionein,Metallothionein,Metallothionein,Functional
25,IEG_YPEL5/CREM_1,IEG2,Immediate Early Gene 2,IEG2,IEG2,Artifact
26,High-Cytokine,Multi-Cytokine,Multi-Cytokine,Multi-Cytokine,Multi-Cytokine,Functional
27,S100A10/LMNA,CCR10-Migration,Th22,Th22,Th22,Lineage
28,Th17,Th17,Th17 Resting,Th17-Resting,Th17-Rest.,Lineage
29,Th2,Th2-1,Th2 Resting,Th2-Resting,Th2-Rest.,Lineage
30,BCL2/CDK6,BCL2-Survival,BCL2/FAM13A Pro-survival,BCL2/FAM13A,BCL2/FAM13A,Functional
31,CD4 TEM,CD4-EM,Th1-Like,Th1-Like,Th1-Like,Lineage
32,CD8-Naive,CD8-Naive,CD8 Naive,CD8-Naive,CD8-Naive,Lineage
33,CD8/KLRC2,CD8-Trm-Like,CD8 Tissue Resident Memory,CD8-Trm,CD8-Trm,Lineage
34,CTLA4+CD38+_IL26/CTSH,CTLA4+/CD38+-Activation,CTLA4/CD38 Activation,CTLA4/CD38,CTLA4/CD38,Functional
35,Doublet-Bcell,Doublet-Bcell,Doublet Bcell,Doublet-Bcell,Dbt-Bcell,Doublet Lineage
36,Doublet-Myeloid,Doublet-Myeloid,Doublet Myeloid,Doublet-Myeloid,Dbt-Myeloid,Doublet Lineage
37,HeatShock1,HeatShock,Heatshock,Heatshock,Heatshock,Functional
38,AMP-RA_Tfh,Tfh-2,T follicular helper 2,Tfh-2,Tfh-2,Lineage
39,CCR3+-Th2,Th2-2,Th2-Activated,Th2-Activated,Th2-Act.,Functional
40,EBI3-Activation,OX40/EBI3-Activation,OX40/EBI3 Activation,OX40/EBI3,OX40/EBI3,Functional
41,ICOS/ACTG1,ICOS/CD38-Activation,ICOS/CD38 Activation,ICOS/CD38,ICOS/CD38,Functional
42,IL26/CTSH,Th17-2,Th17-Activated,Th17-Activated,Th17-Act.,Functional
43,SOX4/MME,SOX4/TOX2,SOX4/TOX2,SOX4/TOX2,SOX4/TOX2,Functional
44,TIMD4/CD38,TIMD4/TIM3-Activation,TIMD4/TIM3,TIMD4/TIM3,TIMD4/TIM3,Functional
45,AMP-RA_Pan-Cancer,Doublet-Fibroblast,Doublet Fibroblast,Doublet-Fibroblast,Dbt-Fibroblast,Doublet Lineage
46,CH25H/DDIT4_Pan-Cancer,CD40LG/TXNIP,CD40LG/TXNIP,CD40LG/TXNIP,CD40LG/TXNIP,Functional
47,HIV-Vaccine,TXNIP/H1FX,CD172a/MERTK,CD172a/MERTK,CD172a/MERTK,Functional
48,IEG_YPEL5/CREM_2,YPEL5/JUNB,Immediate Early Gene 3,IEG3,IEG3,Artifact
49,AMP-RA:Tph_Single,Tph,T peripheral helper,Tph,Tph,Lineage
50,Pan-Cancer:Tfh_Single,Tfh-1,T follicular helper 1,Tfh-1,Tfh-1,Lineage
51,Pan-Cancer:Tph_Single,Exhaustion,Exhaustion,Exhaustion,Exhaustion,Functional

In [20]:
# 1。构造映射字典 Shortest_Name -> Class
short_to_class = dict(zip(gep_52info["Short_Name"], gep_52info["Class"]))

# 2. 基于子字符串查找 class
out_df["Class"] = out_df["Spectra_Label"].apply(
    lambda text: next(
        (cls for short, cls in short_to_class.items() if short in text),
        None  # 如果没有匹配项，返回 None
    )
)


Artifact
可能是伪影/噪声细胞或质量较差的细胞，通常会在质控阶段被移除或标记。

Doublet Lineage 
可能是双重体（Doublets），即两个细胞被错误地捕获在一个液滴中，常见于10x Genomics等平台。

Functional
可能指功能性细胞，比如具有特定功能状态的细胞，如激活状态、代谢状态等。

Lineage 
可能指谱系细胞，如某种细胞类型或分化路径中的细胞，如免疫细胞谱系、神经谱系等

In [30]:
out_df
out_df.to_csv('./3.cGEP_topgene/gep_anno_class.csv', index=False)

In [24]:
out_df['Class'].value_counts()

Class
Functional         20
Lineage             9
Doublet Lineage     5
Artifact            3
Name: count, dtype: int64

In [28]:
out_df[out_df['Class'] == 'Lineage']

,Spectra_Label,Merged_Top_Genes,Num_Genes,Source_cGEPs,Num_Modules_Merged,Class
2,CD4-Naive,"TSHZ2,CTB-133G6.1,LHFPL6,GLTSCR2,SPON1,IGFL2,S...",10,cGEP41,1,Lineage
4,CD8-EM,"RPS7,RPL23A,ATP5E,GZMK,RARRES3,CCL5,RPL28,CD8A...",20,"cGEP20,cGEP29",2,Lineage
5,CD8-Trm,"KIR2DL4,GABARAPL1,FOSL2,CREM,GZMB,LRRC34,LOC10...",43,"cGEP16,cGEP40,cGEP45,cGEP59,cGEP62",5,Lineage
24,MAIT,"KLRB1,AMICA1,SLC4A10,IL7R,CCR6,NCR3,LTB,DUSP1,...",10,cGEP10,1,Lineage
30,TEMRA,"CRISPLD1,NTM,HDC,GNLY,XCL2,RP11-354E11.2,SPTSS...",10,cGEP17,1,Lineage
31,Th17-Resting,"KLRB1,PTPN13,CCR6,S100A6,CTSH,LGALS3,SPOCK2,S1...",10,cGEP49,1,Lineage
33,Th22,"SLPI,PADI2,LTB,SPATA22,S100A10,HIST1H4C,TMC5,K...",20,"cGEP50,cGEP51",2,Lineage
34,Tph,"GZMB,LAYN,ENTPD1,GAPDH,TNFRSF18,KRT86,TIGIT,AC...",10,cGEP6,1,Lineage
36,Treg,"SLC18A2,GATA2,AP000781.2,AC004791.2,MS4A2,IL1R...",20,"cGEP18,cGEP19",2,Lineage

In [29]:
out_df[out_df['Class'] == 'Functional']['Spectra_Label']

0          BCL2/FAM13A
1         CD172a/MERTK
3         CD40LG/TXNIP
6           CTLA4/CD38
7        CellCycle-G2M
8     CellCycle-Late-S
9          CellCycle-S
10        Cytoskeleton
11           Cytotoxic
17          Exhaustion
18                 HLA
19           Heatshock
22           IL10/IL19
23                 ISG
25     Metallothionein
27      Multi-Cytokine
28          RGCC/MYADM
29           SOX4/TOX2
32       Th2-Activated
35         Translation
Name: Spectra_Label, dtype: object

In [26]:
out_df[out_df['Class'] == 'Functional']

,Spectra_Label,Merged_Top_Genes,Num_Genes,Source_cGEPs,Num_Modules_Merged,Class
0,BCL2/FAM13A,"AK4,MYC,LDHA,ENO1,PGK1,MIF,ALDOA,IL9R,DNTT,PKM",10,cGEP58,1,Functional
1,CD172a/MERTK,"RPS4Y1,DDX3Y,MTRNR2L8,NR4A2,MALAT1,CCNL1,SRSF7...",10,cGEP66,1,Functional
3,CD40LG/TXNIP,"CD97,ELOB,ATP5MD,ATP5MG,RIPOR2,AC007349.2,TRIR...",20,"cGEP25,cGEP31",2,Functional
6,CTLA4/CD38,"SLC52A3,FGFR3,SLC2A5,AGR2,PDLIM3,LINC01297,VAN...",10,cGEP63,1,Functional
7,CellCycle-G2M,"KIAA0101,FGGY,KIF15,DEPDC1,KIF14,TUBA1B,AC2535...",10,cGEP56,1,Functional
8,CellCycle-Late-S,"PCLAF,TOP2A,STMN1,BIRC5,TUBB,MKI67,RRM2,C15ORF...",10,cGEP21,1,Functional
9,CellCycle-S,"KIAA0101,GATA2,TYMS,MS4A2,PCLAF,HPGDS,STMN1,RR...",20,"cGEP37,cGEP65",2,Functional
10,Cytoskeleton,"TRAV8-1,ATP5E,GNLY,S100A6,TMSB4X,TMSB10,TMSB4X...",24,"cGEP8,cGEP12,cGEP23",3,Functional
11,Cytotoxic,"GNLY,ATP6,AC245427.1,ATP8,GPR56,FCGR3A,ND4,SPO...",19,"cGEP27,cGEP68",2,Functional
17,Exhaustion,"HMOX1,AC069363.1,SNAP47,IFI6,CD27,CTLA4,CST7,P...",17,"cGEP22,cGEP35",2,Functional
18,HLA,"HLA-DRB5,CST3,GNLY,ZNF683,CD74,PRMT9,LOC101929...",31,"cGEP26,cGEP32,cGEP52,cGEP54",4,Functional
19,Heatshock,"HSPH1,DNAJB1,HSPD1,HSPE1,HSP90AA1,RP11-1033A18...",10,cGEP7,1,Functional
22,IL10/IL19,"TRBV12-4,NPW,ST8SIA3,PTPN3,CD81,RP11-522I20.3,...",10,cGEP55,1,Functional
23,ISG,"IFI6,IFIT1,LY6E,MX1,OAS1,RSAD2,IFIT3,ISG15,ISG...",10,cGEP2,1,Functional
25,Metallothionein,"MRAP2,LCN2,TLCD2,PLA2G4F,AKR1B10,RAET1L,CRCT1,...",10,cGEP60,1,Functional
27,Multi-Cytokine,"GZMK,CD27,CCL4L2,TMEM155,CCL3L3,TNS3,TRAV19,FX...",10,cGEP28,1,Functional
28,RGCC/MYADM,"MYADM,S100A10,S100A11,ANXA1,RGCC,CRIP1,ADGRE5,...",10,cGEP46,1,Functional
29,SOX4/TOX2,"MT.ND3,GZMB,DNASE1L3,BHLHB9,IL3RA,ASIP,AFF3,BE...",20,"cGEP43,cGEP70",2,Functional
32,Th2-Activated,"S100A1,EMILIN1,RP11-176H8.1,SEMA3B,ZNF202,LINC...",10,cGEP67,1,Functional
35,Translation,"RPL31,AL162511.1,RPL32,RP11-234A1.1,RPS18,ZG16...",58,"cGEP1,cGEP4,cGEP15,cGEP36,cGEP42,cGEP64,cGEP69",7,Functional

# 鉴定到的亚群。
1) CD4-Naive（初始 CD4⁺ T 细胞）

定义：未经历抗原激活的 CD4⁺ T 细胞，在外周循环和淋巴组织中巡游，具备广泛的分化潜能。
功能：接触抗原后可分化为不同的效应/辅助 T 细胞亚群（如 Th1、Th2、Th17、Th22、Treg 等），负责协调免疫应答、激活 B 细胞和 CD8⁺ T 细胞。
免疫角色：代表免疫应答的“预备力量”，是 adaptive immunity 的基础。 ￼

⸻

2) CD8-EM（CD8⁺ Effector Memory T Cells / CD8⁺ 效应记忆 T 细胞）

定义：属于记忆性 CD8⁺ T 细胞，在初次抗原遇到后产生，表达记忆标志（如 CD45RO⁺ CCR7⁻）但不再为新手细胞。
功能：快速应答病原体再次出现，能迅速分泌细胞毒性因子并杀伤感染细胞。
免疫角色：不仅提供快速免疫保护，还在长期抗原清除和免疫监视中发挥重要作用。 ￼

⸻

3) CD8-Trm（Tissue-Resident Memory T Cells / 组织驻留记忆 T 细胞）

定义：一类不循环于血液，而长期驻留在组织（皮肤、肺、黏膜等）的 CD8⁺ 記憶 T 细胞。
功能：在组织中检测再感染，并快速释放效应分子（如 IFN-γ、TNF-α、穿孔素等），提供局部免疫防护。
免疫角色：第一道防线，防止病原体入侵组织并快速激活局部免疫。 ￼

⸻

4) MAIT（Mucosal-Associated Invariant T Cells / 黏膜相关不变 T 细胞）

定义：一类表达有限 TCR 的特殊 T 细胞亚群，响应由 MR1 分子呈递的微生物维生素代谢中间产物。
功能：能快速分泌炎性细胞因子（如 IFN-γ、TNF-α）并直接杀灭感染细胞，同时桥接先天免疫和适应性免疫系统。
免疫角色：在黏膜、血液等部位对细菌和真菌感染的快速防御尤为重要，还可能参与自身免疫疾病的病理过程。 ￼

⸻

5) TEMRA（Terminally Differentiated Effector Memory RA⁺ Cells）

定义：一种极度成熟的记忆 T 细胞，通常是 CD45RA⁺（类似 naive 标记）但 CCR7⁻ 且具有强效应功能。
功能：高表达细胞毒性分子、可能具备更强的杀伤力，但也常表现出衰老/终末分化特征。
免疫角色：经常在慢性感染、反复抗原刺激或老年人中增多，代表免疫经历多次抗原刺激的“老兵”细胞。 ￼

⸻

6) Th17-Resting（休眠态 Th17 细胞）

定义：来源于 naïve CD4⁺ T 细胞的一类辅助性 T 细胞，以产生 IL-17/IL-22 为特点。
功能：介导 对细菌与真菌的保护性免疫，特别是在黏膜/上皮屏障处；异常活化可导致自身免疫和炎症性疾病。
免疫角色：平衡组织防御与炎症，参与免疫病理过程。 ￼

⸻

7) Th22（Th22 细胞）

定义：CD4⁺ T 细胞的另一种效应亚群，独特之处在于主要生产 IL-22 而不是其他 Th1/Th2/Th17 类细胞因子。
功能：IL-22 对上皮细胞的完整性、屏障功能及组织修复很重要。
免疫角色：在上皮免疫防御、慢性炎症（如皮肤炎症）及屏障组织保护中发挥作用。 ￼

⸻

8) Tph（T Peripheral Helper 细胞）

定义：一种新发现的 CD4⁺ T 细胞亚群，类似于 T follicular helper（Tfh）但不驻留于淋巴滤泡。
功能：在外围组织中帮助 B 细胞成熟与抗体产生，表达 PD-1⁺ CXCL13⁺，并能参与炎症局部免疫调节。
免疫角色：在组织炎症、类风湿关节炎和自身免疫环境中非常重要，与 B 细胞合作生成局部抗体反应。 ￼

⸻

9) Treg（调节性 T 细胞）

定义：一类表达 FOXP3、CD25 的 CD4⁺ T 细胞，具有免疫抑制功能。
功能：通过分泌 IL-10、TGF-β 等抑制性因子，以及细胞接触抑制等机制，抑制活化 T 细胞扩增与效应功能。
免疫角色：维持免疫耐受、防止自身免疫、限制过度炎症反应，对肿瘤免疫和疫苗应答也有重要调控作用。

# 鉴定到的免疫相关功能类别
免疫细胞程序/功能类别定义与免疫学意义

1. 细胞周期相关程序

这些程序反映细胞周期进程，对免疫细胞的增殖与扩增至关重要。
	•	CellCycle-G2M / CellCycle-Late-S / CellCycle-S
定义：分别代表细胞处于细胞周期的 S 期（DNA 合成阶段）、晚期 S 期（DNA 复制接近完成）和 G2/M 期（准备有丝分裂）阶段。
功能：表示细胞正在进行 DNA 复制或即将分裂，反映细胞增殖活性。
免疫意义：免疫细胞在遇到抗原刺激后需要迅速克隆扩增以放大效应反应，这些程序是这种克隆扩增的分子标志。
生物学背景：免疫应答过程中，特别是 T/B 细胞活化时会显著增加细胞周期相关基因表达。

⸻

2. 细胞结构相关程序
	•	Cytoskeleton
定义：与细胞骨架构成及调节相关的基因集合。
功能：维持细胞形态、动力学调整、细胞迁移以及免疫突触形成等。
免疫意义：免疫细胞的迁移、趋化和与抗原呈递细胞的接触都依赖细胞骨架的重构；例如，T 细胞与 APC 形成免疫突触、穿越组织屏障等。
背景：细胞骨架蛋白如 actin、tubulin 调控免疫细胞的快速移动与形态变化，影响效应功能释放。

⸻

3. 细胞应激与保护相关程序
	•	Heatshock / Metallothionein
定义：热休克蛋白、金属鲁蛋白等应激响应相关基因集合。
功能：在蛋白质折叠、抗氧化、金属离子平衡等细胞压力应对中起保护作用。
免疫意义：在炎症、感染以及氧化应激条件下，这些程序被上调以维持细胞稳态，并与免疫细胞的耐受性及存活性相关。

⸻

4. 蛋白质合成相关程序
	•	Translation
定义：蛋白质合成过程相关基因集合。
功能：反映细胞的翻译水平和代谢活性。
免疫意义：免疫细胞需要大量蛋白质合成来产生效应因子（细胞因子、受体等）和能量，因此翻译相关程序往往与活跃免疫状态相关。

⸻

免疫特异性程序与免疫细胞功能

1. 免疫细胞表面与调控分子

这些类别通常反映免疫信号传导、共刺激或抑制受体的表达。
	•	CD172a / MERTK
功能：CD172a（SIRPα）是负向调节吞噬的受体，与 “别吃我” 信号相关；MERTK 是识别并清除凋亡细胞的受体。
免疫意义：在巨噬细胞及其他免疫细胞中，这些受体调节自体 vs 非自体识别，影响清除和耐受反应。
	•	CD40LG / TXNIP
功能：CD40L 是活化 T 细胞的标志，与 APC/B 细胞共刺激相关；TXNIP 调节氧化应激。
免疫意义：CD40L-CD40 轴促进 B 细胞成熟和抗体生成，增强抗原呈递功能。
	•	CTLA4 / CD38 / HLA
功能：CTLA4 是抑制性免疫检查点受体；CD38 是活化标志及 NAD+ 代谢调节因素；HLA 是抗原呈递的核心分子。
免疫意义：CTLA4 与其他免疫检查点一起调节免疫反应阈值；HLA 分子呈递肽给 TCR 激活适应性免疫。

⸻

2. 细胞毒性功能
	•	Cytotoxic
定义：与细胞毒性效应相关的程序。
功能：CTL 和 NK 等细胞通过穿孔素（perforin）、颗粒酶（granzymes）和 FasL 等机制诱导靶细胞死亡，从而清除感染细胞或肿瘤细胞。
免疫意义：细胞介导免疫对抗病毒和肿瘤的关键机制。(turn0search25￼)

⸻

3. 免疫调节性细胞因子程序
	•	IL10 / IL19 / Multi-Cytokine
定义：与抗炎或免疫调节性细胞因子表达相关的程序。
功能：IL-10 是重要的抗炎细胞因子，调节免疫反应强度；IL-19 属于同一家族，也参与调控免疫。
免疫意义：这些程序通常与抑制性免疫反应及免疫稳态维持相关；多细胞因子程序代表细胞能同时产生多种信号分子。

⸻

4. T 细胞耗竭状态
	•	Exhaustion
定义：长期抗原刺激导致 T 细胞逐渐丧失效应功能的一种表型，常伴随表达 PD-1、TIM-3、LAG-3 等检查点受体。
功能：耗竭状态减弱免疫杀伤力但避免过度免疫损伤。
免疫意义：在肿瘤免疫微环境和慢性感染中，这种状态常见，是免疫逃逸的重要机制。

⸻

5. 免疫细胞亚群程序

这些类别对应具体的辅助 T 细胞谱系或状态群体，其定义依赖其特异性细胞因子或表面标志物。
	•	Th2-Activated
定义：活化的 Th2 类辅助性 T 细胞。
功能：分泌 IL-4、IL-5、IL-13 等细胞因子，促进 B 细胞抗体生成及调节性炎症反应。
免疫意义：在过敏反应和抗寄生虫免疫中尤为重要，对体液免疫有推动作用。(turn0search7￼)

⸻

6. 干扰素响应程序
	•	ISG（Interferon Stimulated Genes）
定义：被干扰素信号显著诱导的一类基因。
功能：形成抗病毒状态，调节多个抗原呈递和杀伤路径。
免疫意义：干扰素通路是抗病毒天然与适应免疫的重要桥梁，ISG 上调往往与活跃的抗病毒或抗肿瘤免疫状态相关。(turn0search0￼)

⸻

特殊基因组合及其意义

这些基因组合常见于某些细胞状态或分化程序。
	•	BCL2 / FAM13A：相关凋亡或存活调节，影响免疫细胞寿命。
	•	SOX4 / TOX2：关键转录因子，在 T 细胞发育和记忆态维持中发挥调控作用。
	•	RGCC / MYADM：与细胞应激响应和迁移状态相关，可能反映某些激活态或炎症调节。

⸻

临床与免疫学应用意义
	1.	肿瘤免疫治疗
	•	Exhaustion 和检查点分子（如 PD-1、CTLA-4）是免疫检查点抑制剂的核心靶点。
	•	Cytotoxic 程序的活跃性常与免疫治疗反应强度相关。
	2.	自身免疫与过敏
	•	Th2-Activated 程序与二型炎症、过敏反应相关。
	•	IL-10/IL-19 程序与抗炎调节及抑制自身免疫反应相关。
	3.	感染免疫与监测
	•	ISG 程序的上调是抗病毒免疫的标志，可用于监测感染状态或干扰素疗法效果。
	•	CellCycle 相关程序可评估免疫细胞克隆扩增与活性水平。