In [1]:
library(dplyr)
library(tidyr)
library(pheatmap)
library(viridis)
library(tools)
library(cluster)
library(igraph)
library(tibble)

library(clusterProfiler)
library(org.Hs.eg.db)
library(dplyr)

Warning message:
“程辑包‘dplyr’是用R版本4.2.3 来建造的”

载入程辑包：‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“程辑包‘tidyr’是用R版本4.2.3 来建造的”
Warning message:
“程辑包‘viridis’是用R版本4.2.3 来建造的”
载入需要的程辑包：viridisLite

Warning message:
“程辑包‘viridisLite’是用R版本4.2.3 来建造的”
Warning message:
“程辑包‘cluster’是用R版本4.2.3 来建造的”

载入程辑包：‘igraph’


The following object is masked from ‘package:tidyr’:

    crossing


The following objects are masked from ‘package:dplyr’:

    as_data_frame, groups, union


The following objects are masked from ‘package:stats’:

    decompose, spectrum


The following object is masked from ‘package:base’:

    union



载入程辑包：‘tibble’


The following object is masked from ‘package:igraph’:

    as_data_frame


Warning message:
“程辑包‘clusterProfiler’是用R版本4.2.2 来建造的”


Registered S3 methods overwritten by 'treeio':
  method              from
  MRCA.phylo          tidytree
  MRCA.treedata       tidytree
  Nnode.treedata      tidytree
  Ntip.treedata       tidytree
  ancestor.phylo      tidytree
  ancestor.treedata   tidytree
  child.phylo         tidytree
  child.treedata      tidytree
  full_join.phylo     tidytree
  full_join.treedata  tidytree
  groupClade.phylo    tidytree
  groupClade.treedata tidytree
  groupOTU.phylo      tidytree
  groupOTU.treedata   tidytree
  is.rooted.treedata  tidytree
  nodeid.phylo        tidytree
  nodeid.treedata     tidytree
  nodelab.phylo       tidytree
  nodelab.treedata    tidytree
  offspring.phylo     tidytree
  offspring.treedata  tidytree
  parent.phylo        tidytree
  parent.treedata     tidytree
  root.treedata       tidytree
  rootnode.phylo      tidytree
  sibling.phylo       tidytree

clusterProfiler v4.6.0  For help: https://yulab-smu.top/biomedical-knowledge-mining-book/

If you use clusterProfiler in published research, please cite:
T Wu, E Hu, S Xu, M Chen, P Guo, Z Dai, T Feng, L Zhou, W Tang, L Zhan, X Fu, S Liu, X Bo, and G Yu. clusterProfiler 4.0: A universal enrichment tool for interpreting omics data. The Innovation. 2021, 2(3):100141


载入程辑包：‘clusterProfiler’


The following object is masked from ‘package:igraph’:

    simplify


The following object is masked from ‘package:stats’:

    filter


载入需要的程辑包：AnnotationDbi

载入需要的程辑包：stats4

载入需要的程辑包：BiocGenerics


载入程辑包：‘BiocGenerics’


The following objects are masked from ‘package:igraph’:

    normalize, path, union


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


载入需要的程辑包：Biobase

Warning message:
“程辑包‘Biobase’是用R版本4.2.3 来建造的”
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


载入需要的程辑包：IRanges

Warning message:
“程辑包‘IRanges’是用R版本4.2.3 来建造的”
载入需要的程辑包：S4Vectors


载入程辑包：‘S4Vectors’


The following object is masked from ‘package:clusterProfiler’:

    rename


The following object is masked from ‘package:tidyr’:

    expand


The following objects are masked from ‘package:dplyr’:

    first, rename


The following objects are masked from ‘package:base’:

    expand.grid, I, unname



载入程辑包：‘IRanges’


The following object is masked from ‘package:clusterProfiler’:

    slice


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice



载入程辑包：‘AnnotationDbi’


The following object is masked from ‘package:clusterProfiler’:

    select


The following object is masked from ‘package:dplyr’:

    select

In [2]:
# 读入
signature_CD8T <- read.csv(
  "3.cGEP_topgene/ALL_cGEP_top_genes_long_wide_by_cGEP1_70.csv",
  check.names = FALSE,
  stringsAsFactors = FALSE)
# 转成 list（核心）
cluster_genes <- lapply(signature_CD8T, function(x) {
  x[!is.na(x) & x != ""]
})


gene_df <- data.frame(
  cGEP_Cluster = names(cluster_genes),  # 确保这里是 cGEP1, cGEP2...
  cGEP_signature = sapply(cluster_genes, function(x) paste(x, collapse = ",")),
  stringsAsFactors = FALSE
)
gene_df

       cGEP_Cluster
cGEP1  cGEP1
cGEP2  cGEP2
cGEP3  cGEP3
cGEP4  cGEP4
cGEP5  cGEP5
cGEP6  cGEP6
cGEP7  cGEP7
cGEP8  cGEP8
cGEP9  cGEP9
cGEP10 cGEP10
cGEP11 cGEP11
cGEP12 cGEP12
cGEP13 cGEP13
cGEP14 cGEP14
cGEP15 cGEP15
cGEP16 cGEP16
cGEP17 cGEP17
cGEP18 cGEP18
cGEP19 cGEP19
cGEP20 cGEP20
cGEP21 cGEP21
cGEP22 cGEP22
cGEP23 cGEP23
cGEP24 cGEP24
cGEP25 cGEP25
cGEP26 cGEP26
cGEP27 cGEP27
cGEP28 cGEP28
cGEP29 cGEP29
cGEP30 cGEP30
⋮      ⋮
cGEP41 cGEP41
cGEP42 cGEP42
cGEP43 cGEP43
cGEP44 cGEP44
cGEP45 cGEP45
cGEP46 cGEP46
cGEP47 cGEP47
cGEP48 cGEP48
cGEP49 cGEP49
cGEP50 cGEP50
cGEP51 cGEP51
cGEP52 cGEP52
cGEP53 cGEP53
cGEP54 cGEP54
cGEP55 cGEP55
cGEP56 cGEP56
cGEP57 cGEP57
cGEP58 cGEP58
cGEP59 cGEP59
cGEP60 cGEP60
cGEP61 cGEP61
cGEP62 cGEP62
cGEP63 cGEP63
cGEP64 cGEP64
cGEP65 cGEP65
cGEP66 cGEP66
cGEP67 cGEP67
cGEP68 cGEP68
cGEP69 cGEP69
cGEP70 cGEP70
       cGEP_signature
cGEP1  TotalSeqC0953,RP11-864N7.2,RP11-234A1.1,RP11-425L10.1,RPL13P12,RPS12,TotalseqC0251,RPL13,RPL32,AC024293.1,EEF1A1,RPL34,AC016739.2,RPS18,RPS28,RPS3A,RPL18AP3,RPL39,RPL10,RPL11,RPS14,RPS8,RPL30,RPS23,RPS6,RPS13,RPL19,RPL37,RPL18A,RPS27
cGEP2  ISG15,MX1,IFI6,IFIT3,IFIT1,RSAD2,OAS1,IFI44L,ISG20,LY6E,IFITM1,CMPK2,HERC5,IRF7,OAS3,MX2,EPSTI1,PLSCR1,STAT1,MT2A,USP18,IFIT2,IFI35,EIF2AK2,XAF1,IFI44,SAMD9L,TNFSF10,OASL,LAMP3
cGEP3  CYTB,ATP6,COX3,ND4L,COX2,ND1,ND5,ND2,ATP8,RPS14P3,ND3,MT-ND1,GAS5,MT-CO3,MT-CO2,ND4,HLA-H,MT-ND2,MT-ND3,MT-ATP6,LOC100507217,MT-CYB,MT-ND4,MT-ND4L,MT-ND5,MT-CO1,ND6,MT-RNR2,AC026366.1,CRISP3
cGEP4  RPL13P12,TotalSeqC0952,EEF1A1,TotalSeqC0955,RPL13,RPL34,TPT1,RPL32,RPS12,AC010343.1,RPLP1,AL365357.1,IL7R,RPS4XP22,RPS8,AC016739.1,RPS6,RPL10,RPL11,RPS4X,RPS18,AL590867.2,RPS14,RPS13,CCR7,FTH1,RPS3A,RPL30,RPL3,RPL19
cGEP5  MT-ND4,MT-CO2,MT-CO3,MT-ATP6,MT-CYB,MT-CO1,MT-ND2,MT-ND1,MT-ND3,MT-ND5,SLIT1,PVRL4,MT-ND4L,MTATP6P1,MT-RNR1,TMPRSS11F,ANKRD30A,MTRNR2L10,RFX6,MT-TH,MT-RNR2,WARS2-IT1,PABPC4L,KCNN2,RNF225,SCGB1D2,MTRNR2L9,TMSB4XP8,MT-ATP8,MTRNR2L8
cGEP6  GAPDH,KRT86,GZMB,ENTPD1,TNFRSF9,TIGIT,TNFRSF18,CD7,LAYN,AC092580.4,LOC101929531,SNX9,ALOX5AP,TPI1,CXCL13,TNS3,PGAM1,PKM,HAVCR2,AC002331.1,RBPJ,PDLIM4,LAG3,CTSD,ITGAE,CTLA4,GOLIM4,IFITM10,MYO1E,CD82
cGEP7  RP11-1033A18.1,DNAJB1,HSP90AA1,HSPA1A,RP11-485G4.2,HSPA1B,HSPH1,HSP90AB1,HSPE1,HSPD1,HSPA8,DNAJA1,RP11-153M3.1,CACYBP,HSP90AA2P,GOT2P2,UBB,HSPB1,BAG3,ZFAND2A,TIMM8AP1,HSPA6,GGNBP1,PPP1R15A,UBC,RP11-142L4.2,HSP90AB3P,MIRLET7D,SERPINH1,LOC101928304
cGEP8  GNLY,S100A4,TMSB10,TRBV7-6,IFITM2,RPL39,S100A6,TRAV8-1,ATP5E,SH3BGRL3,SERF2,FXYD5,MT-ND3,RPL41,MYL12A,S100A11,TMSB4X,RPS4Y1,GZMB,RPL36A,TMA7,HSPA1A,RPS18,OST4,RPS21,S100A10,TRAV10,HCST,PFN1,IFITM1
cGEP9  HBB,HBD,AHSP,SNCA,CA1,HBA2,ALAS2,HBA1,SLC4A1,SELENBP1,SLC25A37,PDZK1IP1,TRIM58,HBM,HBQ1,GMPR,HEMGN,KLHL33,KLF1,SLC25A39,HBG2,STRADB,EPB42,PLEK2,BLVRB,NFIX,NFE2,TNS1,BNIP3L,IGF2BP2
cGEP10 KLRB1,SLC4A10,NCR3,AMICA1,CEBPD,IL7R,LTB,S100A4,DUSP1,CCR6,LTK,ZBTB16,AQP3,NFKBIA,IL23R,IL4I1,TSPAN15,RP11-693N9.2,ME1,RORC,LST1,CD69,RORA,CTD-3014M21.1,IL18RAP,IL22,CCL20,IL26,CTSH,PHACTR2
cGEP11 FOS,JUN,DUSP1,FOSB,COX1,KLF6,CD69,JUNB,ZFP36,TSC22D3,ND4,TNFAIP3,NFKBIA,PPP1R15A,NR4A2,CYTB,RNR2,COX2,ND4L,IER2,ZFP36L2,COX3,CXCR4,BTG2,ATP6,H3F3B,ND1,EGR1,CCL4,NR4A1
cGEP12 TotalSeqC0954,LOC100996919,NKG7,GZMH,TotalseqC0252,GZMA,CCL5,ACTB,PFN1,SH3BGRL3,TMSB4X,LOC100996809,CFL1,LOC101060038,CORO1A,PLAAT4,HCST,HLA-DPA1,CLIC1,ACTG1,HLA-DRB1,HLA-DPB1,B2M,HLA-C,CD8A,GZMB,IL32,LOC102723461,CST7,CD3D
cGEP13 LYZ,LINC01272,S100A9,LOC100130520,FCN1,CST3,S100A8,SERPINA1,SPI1,TYROBP,CSTA,VCAN,CYBB,FPR1,CD14,LOC100507639,MAFB,TNFAIP2,MNDA,CLEC7A,TMEM176B,RP11-1143G9.4,LOC102723715,CXCL8,TNFSF13,SLC7A7,LILRB2,CSF3R,LILRB4,RBP7
cGEP14 HLA-DRA,CD74,CD79A,AL096701.2,MS4A1,VPREB1,BANK1,MEF2C,TCL1A,VPREB3,HLA-DPA1,CD22,HNRNPA1P32,HLA-DRB1,HLA-DQA1,HLA-DQB1,HMGB1P13,CD79B,NAPSB,MARCH1,AL121821.2,HLA-DPB1,HLA-DRB6,ARHGAP24,SPIB,CD19,RALGPS2,CD24,SWAP70,FCER2
cGEP15 RP11.295G20.2,CPEB1.AS1,RPL27A,CTD.2012K14.8,RPL31,RPS17,RPL13A,SCGB3A2,RPS29,RPL21,SGMS1.AS1,SFTPC,RP11.378A13.2,RP11-347P5.1,RPS20,RPLP2,RPL7,CCL18,RPS10,RPS27,MALAT1,ATP5EP2,RPL26,TMSB4X,RPL23A,RPL41,FABP4,MARCO,RPL36A,RP5.1042K10.10
cGEP16 ONECUT2,DMBT1,KRT20,HRCT1,ALDOB,OLFM4,MEP1A,FABP2,EPCAM,TRIM54,TRAV9-2,CD52,HLA-C,A1CF,FAM3D,S100A14,AKR7A3,SI,CLRN3,B2M,CX3CR1,HAAO,S100A4,TM6SF2,GDF15,PART1,CCL25,TRAC,TBX3,GP2
cGEP17 RP11-354E11.2,CRISPLD1,NTM,HDC,GNLY,TYROBP,XCL1,XCL2,FCER1G,SPTSSB,KLRC1,ALKAL2,RP11-245G13.2,CPA3,CTD-2165H16.3,PPM1H,TPSB2,TNFRSF18,KLRF1,IFITM3,KIR2DL4,IL2RB,SELL,IGFBP7,CTSW,NCAM1,CAPG,FLJ21408,DACH1,CNRIP1
cGEP18 CPA3,TPSAB1,TPSB2,AP000781.2,MS4A2,HPGDS,SLC18A2,RP11-354E11.2,GATA2,AC004791.2,HDC,CTSG,KIT,AL157895.1,TMEM220-AS1,MBL1P,FLJ40194,RP11-76E17.3,RHEX,ADCYAP1,AL731557.1,AC015689.2,HPGD,SLC45A3,RPS23P6,IL1RL1,TPSD1,AC046143.2,RGS13,LTC4S
cGEP19 TNFRSF18,FOXP3,TNFRSF4,IL2RA,LINC01943,BATF,CTLA4,HNRNPA1P21,TIGIT,IL1R2,TBC1D4,IL32,AL034345.2,AC017002.3,LAYN,DNPH1,CARD16,ICOS,LAIR2,PKM,S100A4,MAGEH1,CCR8,CD177,TNFRSF1B,TNFRSF9,FANK1,RTKN2,CORO1B,CD27
cGEP20 TotalSeqC0951,CCL5,CCL4,NKG7,CST7,DUSP2,TRBV7-9,CCL4L2,CD8A,TRBV7-4,GZMA,GZMH,CRTAM,CMC1,TRBV7-2,HLA-DRB1,CXCR4,GZMK,CCL3,HLA-A,CEMIP2,CD160,PIK3R1,FYN,GZMM,APOBEC3G,TUBA4A,CD74,PTPRC,HCST
cGEP21 UBE2C,C15ORF53,RRM2,TOP2A,STMN1,PCLAF,TUBA1B,TUBB,MKI67,BIRC5,AURKB,DLGAP5,HJURP,TYMS,HIST1H4C,PLK1,NUSAP1,ASPM,CCNB2,CCNA2,CDCA5,GTSE1,HMGB2,KIF2C,TPX2,CENPF,CDK1,SPC25,KIFC1,KIF15
cGEP22 HAVCR2,PRF1,AC069363.1,CTLA4,LAG3,VCAM1,CST7,SNAP47,HMOX1,LYST,AC243829.4,FAM3C,CADM1,SNX9,TNIP3,IGFLR1,PTMS,CBLB,RDH10,AD000671.6,DUSP4,TNFRSF9,RP11-492E3.2,CD7,TIGIT,PHLDA1,LAYN,SHFM1,ADGRG1,TGIF1
cGEP23 TMSB4XP4,ACTB,S100A4,PFN1,CD52,ACTG1,TMSB4X,SH3BGRL3,IL32,S100A6,VIM,S100A11,LGALS1,S100A10,GAPDH,CFL1,TMSB10,ARPC1B,MYL6,CORO1A,ANXA2,COTL1,CLIC1,LTB,CRIP1,EMP3,MYL12A,KRT84,RAC2,ARHGDIB
cGEP24 IGHV1-69-2,RP11-16E12.2,IGKV1OR2-108,IGHV5-10-1,IGHV1-69,IGHG1,IGKC,MZB1,DERL3,JCHAIN,IGHG3,IGHG4,IGLV2-14,IGHG2,IGKV1-39,IGHV4-59,IGHGP,IGKV1D-33,FCRL5,IGLC2,TNFRSF17,IGLV6-57,IGKV1-6,IGHA1,IGKV1D-39,IGKV1-16,IGKV3D-15,IGLV9-49,AC104971.3,AC104699.1
cGEP25 RACK1,ATP5F1E,ATP5MG,FYB1,NOP53,ATP5MC2,RIPOR2,TRIR,ELOB,ATP5MD,ATP5ME,ATP5IF1,ATP5MPL,ATP5MC3,MT-CYB,NSD3,PAXX,ATP5F1B,ATP5PF,ATP5MF,SELENOW,ATP5F1A,SELENOH,COPS9,ATP5PB,ATP5PD,TXNIP,MT-ND3,SELENOF,OGA
cGEP26 HLA-DQA1,HLA-DRB5,HLA-DRB1,CD74,HLA-DRA,AP003557.1,FXYD6,HLA-DQA2,HLA-DPA1,CXCL13,HLA-DQB1,CLDN16,PDLIM4,HLA-DPB1,CRTAM,RASSF4,UNQ6494,MIR155HG,PKM,TNFRSF9,LHFPL6,CAV1,MYOD1,PON3,MS4A6A,RP11-655C2.3,CD82,ZADH2,HOXB8,GUCY1B1
cGEP27 AC245427.1,NKG7,FCGR3A,PRF1,GPR56,FGFBP2,KLRF1,GNLY,TYROBP,SPON2,GZMB,KLRD1,FCER1G,CTSW,S1PR5,CST7,PLAC8,LOC101928429,CX3CR1,CLIC3,SH2D1B,ITGB2,FGR,AKR1C3,ADGRG1,CD247,PLEK,HOPX,LOC101060789,TRDC
cGEP28 FXYD2,TMEM155,TNFRSF9,CD27,CCL4L2,LOC100129931,CCL3L3,TRAV19,TNS3,GZMK,ETV1,CCL3,XCL1,CD82,HSPA12A,VCAM1,EMR1,MIR155HG,GEM,TTN,DSCAML1,NR5A2,CCL4,LOC101928983,EGR2,AL391056.1,LYST,DUSP4,XCL2,LINC00158
cGEP29 RPS15A,GZMK,RARRES3,RPL28,RPS27,RPL7A,RPL23A,ATP5E,RPS7,CMC1,CST7,RPS24,RPL30,RPS15,RPS25,AL627171.2,GNB2L1,RPL10,RPL13,NKG7,GIMAP4,RPS28,ATP5G2,RPS12,RPL35A,RPS14,ATP5L,RPL39,RPL36,CCL5
cGEP30 ATP8,MALAT1,ATP6,ND4,ND4L,CYTB,ND2,COX1,ND3,RNR2,ND1,COX3,ND6,ND5,PTPRC,RNR1,RP11-463O12.5,NEAT1,MT-ATP6,MT-ND3,DDX17,SYNE2,NKTR,MT-RNR1,KIAA1551,MBNL1,RPL5P4,MT-ND5,COX2,MT-ND2
⋮      ⋮
cGEP41 SESN3,CTB-133G6.1,SELL,ASCL1,PASK,SPON1,LHFPL6,TSHZ2,GLTSCR2,IGFL2,RPS8,CCR7,FKBP5,NR3C1,RPL11,IL6ST,LEF1,CYSLTR1,FAM65B,AC004585.1,MAL,NMB,AJ009632.2,TCF7,GNB2L1,CPM,METTL8,RP11-712B9.2,RPL37,RPL39
cGEP42 CSN3,RPL13A,FDCSP,RPL27A,MALAT1,ITM2C,SMR3B,ZG16B,SLPI,RPS20,PCED1B-AS1,RPS2,TMSB4X,C2ORF82,RPS26,AQP5,RPS19,KIAA1551,RP11-18H21.1,TPT1,RP11-291B21.2,XIST,RPL37A,PNRC1,C12ORF75,MYH9,RPS16,CPNE7,RPL13,RPL23
cGEP43 ASIP,LILRA4,PTGDS,PLD4,IL3RA,IRF8,FLT3,IRF7,DNASE1L3,GZMB,SERPINF1,SLC32A1,SMIM5,LAMP5,RGS2,PPP1R14B,LRRC26,CLEC4C,DERL3,TCF4,LINC00996,SPIB,KCNK17,PLAC8,TCL1A,CYP46A1,FCER1G,EGLN3,C12orf75,SOX4
cGEP44 RAB5IF,SRGN,CST7,CREM,NKG7,FTH1,RPS26,LITAF,CXCR4,FYN,RPL10,RPS3,SARAF,PIK3R1,DUSP2,C1ORF21,RPL23A,GZMM,BTG1,HLA-B,RPS15A,FGFBP2,LEPROTL1,MT1G,SH2D2A,SYAP1,RPL3,SYTL3,ATP5MPL,FAM177A1
cGEP45 METRNL,SLC7A5,CREM,FOSL2,GABARAPL1,ZFP36L2,LINC02446,AC020916.1,RUNX3,ATP1B3,CCL5,CCL4,JUND,TENT5C,KLRC1,SRGN,BTG1,AC092580.4,PTPN22,AUTS2,LINC01871,RANBP2,SYTL3,TGFB1,ITGAD,RNF125,PGK1,CD8A,PARD6G,CD7
cGEP46 LMNA,VIM,MYADM,TAGLN2,S100A10,ADGRE5,S100A11,CRIP1,RGCC,ANXA1,RP11-124N14.3,CRIP2,AHNAK,ANXA2,CD44,GPAT3,EZR,MT-ND2,LRRFIP1,GPR183,CTD-3252C9.4,MT-ND1,AL022718.1,AAED1,RPL23AP42,IDS,AC016739.1,IL7R,AL590867.2,KLF6
cGEP47 COL1A1,MT-ATP6,MT-CYB,RARRES2,MT-CO3,MT-ND1,MT-CO1,MT-ND4,MT-CO2,TIMP3,BGN,LUM,MT-ND2,LGALS1,MT-ND3,COMP,MT-ND5,FN1,MYL9,MT-ND4L,DCN,SFRP2,COL1A2,CXCL14,INHBA,NNMT,UBE2L5P,CHRDL2,ATP5F1,MTRNR2L8
cGEP48 TFF2,CA9,FXYD4,DNAH3,AC106900.2,KRT13,KRT19,GP2,S100A6,AGR2,IFI27,WFDC2,SOX21-AS1,LINC01843,KRT8,CRYBA2,FXYD3,KISS1,CXCL17,LYZ,LINC00261,LGALS4,MAB21L4,CNNM1,EPCAM,S100A14,AC010745.1,CST3,TFF1,LINC02182
cGEP49 KLRB1,CTSH,S100A4,IL26,CCR6,S100A6,SPOCK2,LGALS3,FURIN,PTPN13,CAPG,JAML,ADAM12,CD40LG,SLC1A4,RORA,PKIG,TNFRSF25,OSTF1,ALOX5AP,CXCR6,AHR,LMO4,ADAM19,SH3BGRL3,NBAS,BATF,GNA15,KDSR,C10orf128
cGEP50 VIM,CRIP1,GATA3,S100A4,LTB,S100A10,ANXA1,HIST1H4C,LGALS1,PLP2,SEMA3G,ANXA2,LMNA,KRT1,RPL13AP20,SEMA5A,S100A6,BIRC3,SPC25,AHNAK,ANXA2P3,S100A11,MAP3K1,ARID5B,CCR10,TOB1,TSHR,IL7R,ITGB1,CRIP2
cGEP51 KRT7,LINC01681,SPATA22,SLPI,TMC5,PADI2,SALL2,S100A2,FXYD3,S100A9,LMO1,KRT17,MGST1,LCN2,MTND2P28,S100A11,MEI4,CP,SFN,TSPAN1,AGR2,PRSS2,TACSTD2,TFF3,AC139143.1,SERPINB3,SOWAHB,S100A16,SLC34A2,SFTPB
cGEP52 AC020916.1,HLA-DRB1,HLA-DRA,HLA-DRB5,PRMT9,CCL5,CD74,GZMA,GNLY,ZNF683,TMSB4X,HLA-DPA1,CYTOR,ITGB1,TRG-AS1,HLA-DPB1,HLA-DQA1,KRT86,ITGA1,KIR2DL1,CCL3,CCL4,KIR2DS4,CD63,AC114760.2,ITM2C,CCL3L1,CTSW,AL627171.1,TBCD
cGEP53 FTL,PSAP,CD68,SAT1,FTH1,TYROBP,LILRB2,FCER1G,PLAUR,APOE,S100A11,LST1,CXCL16,APOC1,SMIM25,NPC2,AIF1,C5AR1,CST3,CLEC7A,LRRC25,SPI1,TIMP1,ASAH1,FCN1,LILRA5,LGALS1,HLA-DRA,GRN,CTSD
cGEP54 FAM3B,CST3,LYZ,CPVL,HLA-DRA,HLA-DPB1,CLEC9A,HLA-DPA1,NAPSA,DCLK2,CD74,SPI1,AC096667.1,HLA-DQA1,HLA-DRB1,HLA-DRB5,HCK,LGALS2,C1orf54,IDO1,WDFY4,HLA-DQB1,ZNF366,MPEG1,DNASE1L3,RAB32,C15orf48,CDC25C,HIPK4,KIAA0226L
cGEP55 TRBV12-4,NRIP3,RASL10A,RP11-522I20.3,PTPN3,NPW,ATP5G3,HMGA1,ST8SIA3,CD81,FXYD2,CHAC1,CCNA2,SMCO4,FABP5,HN1,FST,ZNF704,KITLG,PLK1,SH3BP4,LGALS3,EFNA1,SKA1,HES1,ESPL1,STAC3,MYO7B,SGOL2,IL10
cGEP56 AC253572.1,CDC25C,KIF14,HN1,KIF15,MTFR2,KIAA0101,TUBA1B,FGGY,DEPDC1,HNRNPA1P48,UBE2C,HMGB2,CKS2,TPX2,TMSB4X,PTTG1,AC009299.3,ISG15,HMMR,MND1,TOP2A,PFN1,CFL1,BIRC5,CENPE,TUBB,CCNB2,CKS1B,SGOL1
cGEP57 MT-ATP6,MT-CO2,JUND,MT-CYB,MT-ND4,MT-CO3,MT-CO1,NEAT1,ARL4C,MT-ND3,MT-ND1,LINC00513,MT-ND5,TNFAIP3,CALM1,NCL,HSP90AB1,LCP1,KLK3,AC020916.1,DDX24,CD81,MT-ND4L,CRYBG1,KLK2,MBNL1,HNRNPAB,GRK2,METRNL,MT-ND6
cGEP58 AK4,DNTT,LDHA,ENO1,PKM,IL9R,MIF,PGK1,MYC,ALDOA,TAGLN2,IL32,RPLP0,LDHB,TPI1,PIM1,PABPC1,GAPDH,SOCS3,HSPA8,CISH,IL17RB,GPI,CSF2,TMEM123,EEF2,SELL,LTB,PIM2,PGAM1
cGEP59 GZMB,CD7,GNLY,CRX,SPINK2,KLRD1,CAPG,LGALS1,LRRC34,KLRC1,RP11-291B21.2,RP11-356J5.12,PGK1,LGALS3,CD63,PLEKHA6,PRF1,ADAMTS2,VIM,HOPX,GAPDH,IL12RB2,GPR25,IFITM2,LRAT,XCL1,CTSA,S100A6,GLUL,RP11-305L7.1
cGEP60 AKR1B10,MRAP2,CXCL5,RAET1L,HOXC8,TLCD2,CRCT1,PLA2G4F,LCN2,VSTM5,S100P,KLK13,LINC00973,ESRP1,LINC01612,LY6K,EVA1A,TFF1,SPINK1,LINP1,KRT18,KRT8,KRT13,FRAS1,MT1G,SLPI,TSPAN8,GPX2,AL365356.5,SIX4
cGEP61 COL3A1,POSTN,COL1A1,COL1A2,COL6A1,COL6A3,CAPN6,LUM,SGCD,DCN,COL6A2,OAF,ANGPT1,BOC,ADGRA2,SEZ6L2,LHFPL2,EMILIN1,SPARC,DLK1,IGF2,RUNX1T1,EGFR,TMEM130,NR2F1,DCX,GAS1,PALM,COL4A1,MGP
cGEP62 CD7,KLRC2,KRT81,KRT86,KLRC3,LOC101060038,ZNF683,CD9,ND4L,CTSW,XCL1,TXK,KLRD1,CAPG,ND1,SRGAP3,LINC02446,AMICA1,KIR3DL2,CYTB,ND2,SPRY2,SPINT2,HOPX,IL2,NCR3,CD69,ND4,LILRP2,EPAS1
cGEP63 LINC01297,STON1,SLC52A3,FGFR3,MSMB,SLC2A5,PPARGC1A,AGR2,VANGL2,PDLIM3,RP11-115D19.1,MACROD2,ARHGAP6,WNT4,KLK2,ZNF350-AS1,MOGAT2,CDK14,CDC42EP5,ACPP,PRRG1,CCK,PLS3,CADPS2,VEGFA,IRX4,CLDN11,ORM1,ACSS3,KLK3
cGEP64 SFTPC,SFTPA2,SFTPA1,SCGB3A2,KRT8,FTH1,AL162511.1,KRT18,LINC01986,RPL7,RPS4X,NFKBIA,CXCL2,RPLP0,SFTPB,MMP7,RPL3,RPSA,ACTB,SPINT2,B2M,LCN2,MDK,RPS6,CD9,HLA-DRB1,JUNB,RACK1,ELF3,LDHB
cGEP65 TPSAB1,CNRIP1,GATA2,RP11-354E11.2,PRSS57,PNMT,HPGDS,MS4A2,CPA3,TPSB2,RUNDC3A,DPP10,RASGRP4,KRT1,SVOPL,TK1,KEL,EFHC2,GVQW1,KIAA0101,TYMS,TPSD1,LGALS12,DHRS9,GLUL,CXCL2,PDE6G,EXD3,PHACTR1,EMID1
cGEP66 MTRNR2L8,RPS4Y1,DDX3Y,H3F3B,MALAT1,CCNL1,NR4A2,SRSF7,CLK1,EIF1,RBM39,JUN,UTY,TTTY15,SBDS,SRSF5,AC245014.3,BTG1,HSPA5,DDX24,HLA-B,HIST1H1E,MIDN,SSBP3,H1FX,RPL27A,IFRD1,ITGAM,TRA2B,YPEL5
cGEP67 LINC01531,SEMA3B,PANK1,GPR37,ADSSL1,RP11-176H8.1,EMILIN1,LINC00839,S100A1,ZNF202,HSPB2,ADIRF,VN1R1,SMO,FABP3,ECHDC3,PPP1R3C,CKMT2-AS1,TM4SF4,PCSK4,PRDM5,GSTP1,RP11-172H24.4,GPX3,PPFIBP2,S100A16,SOD3,S100A14,GAS1,PKIB
cGEP68 HLA-H,CYTB,ND4,HLA-A,ND4L,ATP6,ATP8,ND2,ND1,NKG7,RNR2,FGFBP2,GZMH,COX2,ND3,S100A4,COX1,LGALS1,SH3BGRL3,ACTB,PFN1,CTSW,GZMB,CD8A,ITGB2,HLA-DRB5,COX3,ND5,FCGR3A,GNLY
cGEP69 IGHGP,ID4,LY6K,TUBB,RPS20,RPL29,RAB13,TM4SF1,EEF1A1,HES1,C1QB,TPPP3,RPL35A,MT-ND1,RPL8,HSP90AB1,RPS8,PSAT1,RPL7,PCP4,SNCG,RPL12,PART1,HSPA6,IGKC,RPS18,SELENBP1,IGLC7,RBP1,RPL31
cGEP70 AFF3,ZFP41,MT.ND3,BEND6,EVI5,PLEKHG6,UBD,MT.ND2,C2orf88,BHLHB9,RNU12,CTSK,C16orf59,SLC44A3,MT.ND1,OSBPL10.AS1,RALY.AS1,COL17A1,CTA.221G9.12,RP11.344P13.6,MT.CO3,RP11.102N12.3,RP11.297B17.3,FCER2,SLC12A8,TM4SF1,MT.ATP6,ASAP3,ATP2A1,LA16c.306E5.2

In [3]:
#CD8T_gep_anno <- read.csv('./3.cGEP_topgene/3.3.CD8T_GEP70_Anno_final.csv')
CD8T_gep_anno <- read.csv('/sibcb1/bioinformatics/yangyue/project/immunotherapy/7.6.cNMF_menchmark/cGEP_signature/CD8T_cGEP70.csv')
CD8T_gep_anno

   cGEP_Cluster cGEP_Anno_Name    Category
1  cGEP1        Ribo_Bio          Functional
2  cGEP10       MAIT              Lineage
3  cGEP11       Activ_IEG         Functional
4  cGEP12       Cyto_Synapse      Functional
5  cGEP13       Myeloid_Inflam    Doublet
6  cGEP14       Bcell_APC         Doublet
7  cGEP15       Transl_Protein    Functional
8  cGEP16       CD8-Trm_Metab     Lineage
9  cGEP17       CD8_GNLY_NKlike   Lineage
10 cGEP18       Mast_PG           Doublet
11 cGEP19       CD8-Treg          Lineage
12 cGEP2        Type1_IFN         Functional
13 cGEP20       CD8-EM_GZMK       Lineage
14 cGEP21       Cycle_G2M         Functional
15 cGEP22       CD8-Tex_Activ     Lineage
16 cGEP23       Cyto_Actin        Functional
17 cGEP24       Plasma_IgG        Doublet
18 cGEP25       Metab_Mito        Functional
19 cGEP26       APC_MHCII         Functional
20 cGEP27       CD8-Cyto_FGFBP2   Lineage
21 cGEP28       CD8-EM_Chemo      Lineage
22 cGEP29       CD8-EM_Transl     Lineage
23 cGEP3        Metab_OXPHOS      Functional
24 cGEP30       Metab_lncRNA      Functional
25 cGEP31       State_Quiescent   Functional
26 cGEP32       Activ_TCR         Functional
27 cGEP33       Stress_Acute      Functional
28 cGEP34       Stress_Hypoxia    Functional
29 cGEP35       CD8-Tex_IFN       Lineage
30 cGEP36       Transl_Ribo       Functional
⋮  ⋮            ⋮                 ⋮
41 cGEP46       Cyto_Stiff        Functional
42 cGEP47       Stromal_Fib       Doublet
43 cGEP48       Epi_EMT           Doublet
44 cGEP49       CD8-Tc17          Lineage
45 cGEP5        Metab_Resp        Functional
46 cGEP50       CD8-Tc22          Lineage
47 cGEP51       Epi_Antimicro     Doublet
48 cGEP52       CD8-Cyto_MHCII    Lineage
49 cGEP53       Myeloid_Phago     Doublet
50 cGEP54       APC_Prof          Functional
51 cGEP55       Prolif_Sup        Functional
52 cGEP56       Cycle_Mito        Functional
53 cGEP57       Stress_NEAT1      Functional
54 cGEP58       Metab_Glyco       Functional
55 cGEP59       CD8-Cyto_Resident Lineage
56 cGEP6        CD8-Tex_Term      Lineage
57 cGEP60       Epi_Stress        Doublet
58 cGEP61       Fib_ECM           Doublet
59 cGEP62       CD8-Trm_ZNF683    Lineage
60 cGEP63       Struct_Adhesion   Doublet
61 cGEP64       Epi_Alveolar      Doublet
62 cGEP65       Mast_Prolif       Doublet
63 cGEP66       APC_Splicing      Functional
64 cGEP67       Stress_ROS        Functional
65 cGEP68       CD8-Cyto_Term     Lineage
66 cGEP69       Transl_Lineage    Functional
67 cGEP7        Stress_HSP        Functional
68 cGEP70       Stromal_Matrix    Doublet
69 cGEP8        Cyto_Motility     Functional
70 cGEP9        Artifact_RBC      Artifact

In [4]:
final_combined_df <- CD8T_gep_anno %>%
  left_join(gene_df, by = "cGEP_Cluster")
final_combined_df

   cGEP_Cluster cGEP_Anno_Name    Category
1  cGEP1        Ribo_Bio          Functional
2  cGEP10       MAIT              Lineage
3  cGEP11       Activ_IEG         Functional
4  cGEP12       Cyto_Synapse      Functional
5  cGEP13       Myeloid_Inflam    Doublet
6  cGEP14       Bcell_APC         Doublet
7  cGEP15       Transl_Protein    Functional
8  cGEP16       CD8-Trm_Metab     Lineage
9  cGEP17       CD8_GNLY_NKlike   Lineage
10 cGEP18       Mast_PG           Doublet
11 cGEP19       CD8-Treg          Lineage
12 cGEP2        Type1_IFN         Functional
13 cGEP20       CD8-EM_GZMK       Lineage
14 cGEP21       Cycle_G2M         Functional
15 cGEP22       CD8-Tex_Activ     Lineage
16 cGEP23       Cyto_Actin        Functional
17 cGEP24       Plasma_IgG        Doublet
18 cGEP25       Metab_Mito        Functional
19 cGEP26       APC_MHCII         Functional
20 cGEP27       CD8-Cyto_FGFBP2   Lineage
21 cGEP28       CD8-EM_Chemo      Lineage
22 cGEP29       CD8-EM_Transl     Lineage
23 cGEP3        Metab_OXPHOS      Functional
24 cGEP30       Metab_lncRNA      Functional
25 cGEP31       State_Quiescent   Functional
26 cGEP32       Activ_TCR         Functional
27 cGEP33       Stress_Acute      Functional
28 cGEP34       Stress_Hypoxia    Functional
29 cGEP35       CD8-Tex_IFN       Lineage
30 cGEP36       Transl_Ribo       Functional
⋮  ⋮            ⋮                 ⋮
41 cGEP46       Cyto_Stiff        Functional
42 cGEP47       Stromal_Fib       Doublet
43 cGEP48       Epi_EMT           Doublet
44 cGEP49       CD8-Tc17          Lineage
45 cGEP5        Metab_Resp        Functional
46 cGEP50       CD8-Tc22          Lineage
47 cGEP51       Epi_Antimicro     Doublet
48 cGEP52       CD8-Cyto_MHCII    Lineage
49 cGEP53       Myeloid_Phago     Doublet
50 cGEP54       APC_Prof          Functional
51 cGEP55       Prolif_Sup        Functional
52 cGEP56       Cycle_Mito        Functional
53 cGEP57       Stress_NEAT1      Functional
54 cGEP58       Metab_Glyco       Functional
55 cGEP59       CD8-Cyto_Resident Lineage
56 cGEP6        CD8-Tex_Term      Lineage
57 cGEP60       Epi_Stress        Doublet
58 cGEP61       Fib_ECM           Doublet
59 cGEP62       CD8-Trm_ZNF683    Lineage
60 cGEP63       Struct_Adhesion   Doublet
61 cGEP64       Epi_Alveolar      Doublet
62 cGEP65       Mast_Prolif       Doublet
63 cGEP66       APC_Splicing      Functional
64 cGEP67       Stress_ROS        Functional
65 cGEP68       CD8-Cyto_Term     Lineage
66 cGEP69       Transl_Lineage    Functional
67 cGEP7        Stress_HSP        Functional
68 cGEP70       Stromal_Matrix    Doublet
69 cGEP8        Cyto_Motility     Functional
70 cGEP9        Artifact_RBC      Artifact
   cGEP_signature
1  TotalSeqC0953,RP11-864N7.2,RP11-234A1.1,RP11-425L10.1,RPL13P12,RPS12,TotalseqC0251,RPL13,RPL32,AC024293.1,EEF1A1,RPL34,AC016739.2,RPS18,RPS28,RPS3A,RPL18AP3,RPL39,RPL10,RPL11,RPS14,RPS8,RPL30,RPS23,RPS6,RPS13,RPL19,RPL37,RPL18A,RPS27
2  KLRB1,SLC4A10,NCR3,AMICA1,CEBPD,IL7R,LTB,S100A4,DUSP1,CCR6,LTK,ZBTB16,AQP3,NFKBIA,IL23R,IL4I1,TSPAN15,RP11-693N9.2,ME1,RORC,LST1,CD69,RORA,CTD-3014M21.1,IL18RAP,IL22,CCL20,IL26,CTSH,PHACTR2
3  FOS,JUN,DUSP1,FOSB,COX1,KLF6,CD69,JUNB,ZFP36,TSC22D3,ND4,TNFAIP3,NFKBIA,PPP1R15A,NR4A2,CYTB,RNR2,COX2,ND4L,IER2,ZFP36L2,COX3,CXCR4,BTG2,ATP6,H3F3B,ND1,EGR1,CCL4,NR4A1
4  TotalSeqC0954,LOC100996919,NKG7,GZMH,TotalseqC0252,GZMA,CCL5,ACTB,PFN1,SH3BGRL3,TMSB4X,LOC100996809,CFL1,LOC101060038,CORO1A,PLAAT4,HCST,HLA-DPA1,CLIC1,ACTG1,HLA-DRB1,HLA-DPB1,B2M,HLA-C,CD8A,GZMB,IL32,LOC102723461,CST7,CD3D
5  LYZ,LINC01272,S100A9,LOC100130520,FCN1,CST3,S100A8,SERPINA1,SPI1,TYROBP,CSTA,VCAN,CYBB,FPR1,CD14,LOC100507639,MAFB,TNFAIP2,MNDA,CLEC7A,TMEM176B,RP11-1143G9.4,LOC102723715,CXCL8,TNFSF13,SLC7A7,LILRB2,CSF3R,LILRB4,RBP7
6  HLA-DRA,CD74,CD79A,AL096701.2,MS4A1,VPREB1,BANK1,MEF2C,TCL1A,VPREB3,HLA-DPA1,CD22,HNRNPA1P32,HLA-DRB1,HLA-DQA1,HLA-DQB1,HMGB1P13,CD79B,NAPSB,MARCH1,AL121821.2,HLA-DPB1,HLA-DRB6,ARHGAP24,SPIB,CD19,RALGPS2,CD24,SWAP70,FCER2
7  RP11.295G20.2,CPEB1.AS1,RPL27A,CTD.2012K14.8,RPL31,RPS17,RPL13A,SCGB3A2,RPS29,RPL21,SGMS1.AS1,SFTPC,RP11.378A13.2,RP11-347P5.1,RPS20,RPLP2,RPL7,CCL18,RPS10,RPS27,MALAT1,ATP5EP2,RPL26,TMSB4X,RPL23A,RPL41,FABP4,MARCO,RPL36A,RP5.1042K10.10
8  ONECUT2,DMBT1,KRT20,HRCT1,ALDOB,OLFM4,MEP1A,FABP2,EPCAM,TRIM54,TRAV9-2,CD52,HLA-C,A1CF,FAM3D,S100A14,AKR7A3,SI,CLRN3,B2M,CX3CR1,HAAO,S100A4,TM6SF2,GDF15,PART1,CCL25,TRAC,TBX3,GP2
9  RP11-354E11.2,CRISPLD1,NTM,HDC,GNLY,TYROBP,XCL1,XCL2,FCER1G,SPTSSB,KLRC1,ALKAL2,RP11-245G13.2,CPA3,CTD-2165H16.3,PPM1H,TPSB2,TNFRSF18,KLRF1,IFITM3,KIR2DL4,IL2RB,SELL,IGFBP7,CTSW,NCAM1,CAPG,FLJ21408,DACH1,CNRIP1
10 CPA3,TPSAB1,TPSB2,AP000781.2,MS4A2,HPGDS,SLC18A2,RP11-354E11.2,GATA2,AC004791.2,HDC,CTSG,KIT,AL157895.1,TMEM220-AS1,MBL1P,FLJ40194,RP11-76E17.3,RHEX,ADCYAP1,AL731557.1,AC015689.2,HPGD,SLC45A3,RPS23P6,IL1RL1,TPSD1,AC046143.2,RGS13,LTC4S
11 TNFRSF18,FOXP3,TNFRSF4,IL2RA,LINC01943,BATF,CTLA4,HNRNPA1P21,TIGIT,IL1R2,TBC1D4,IL32,AL034345.2,AC017002.3,LAYN,DNPH1,CARD16,ICOS,LAIR2,PKM,S100A4,MAGEH1,CCR8,CD177,TNFRSF1B,TNFRSF9,FANK1,RTKN2,CORO1B,CD27
12 ISG15,MX1,IFI6,IFIT3,IFIT1,RSAD2,OAS1,IFI44L,ISG20,LY6E,IFITM1,CMPK2,HERC5,IRF7,OAS3,MX2,EPSTI1,PLSCR1,STAT1,MT2A,USP18,IFIT2,IFI35,EIF2AK2,XAF1,IFI44,SAMD9L,TNFSF10,OASL,LAMP3
13 TotalSeqC0951,CCL5,CCL4,NKG7,CST7,DUSP2,TRBV7-9,CCL4L2,CD8A,TRBV7-4,GZMA,GZMH,CRTAM,CMC1,TRBV7-2,HLA-DRB1,CXCR4,GZMK,CCL3,HLA-A,CEMIP2,CD160,PIK3R1,FYN,GZMM,APOBEC3G,TUBA4A,CD74,PTPRC,HCST
14 UBE2C,C15ORF53,RRM2,TOP2A,STMN1,PCLAF,TUBA1B,TUBB,MKI67,BIRC5,AURKB,DLGAP5,HJURP,TYMS,HIST1H4C,PLK1,NUSAP1,ASPM,CCNB2,CCNA2,CDCA5,GTSE1,HMGB2,KIF2C,TPX2,CENPF,CDK1,SPC25,KIFC1,KIF15
15 HAVCR2,PRF1,AC069363.1,CTLA4,LAG3,VCAM1,CST7,SNAP47,HMOX1,LYST,AC243829.4,FAM3C,CADM1,SNX9,TNIP3,IGFLR1,PTMS,CBLB,RDH10,AD000671.6,DUSP4,TNFRSF9,RP11-492E3.2,CD7,TIGIT,PHLDA1,LAYN,SHFM1,ADGRG1,TGIF1
16 TMSB4XP4,ACTB,S100A4,PFN1,CD52,ACTG1,TMSB4X,SH3BGRL3,IL32,S100A6,VIM,S100A11,LGALS1,S100A10,GAPDH,CFL1,TMSB10,ARPC1B,MYL6,CORO1A,ANXA2,COTL1,CLIC1,LTB,CRIP1,EMP3,MYL12A,KRT84,RAC2,ARHGDIB
17 IGHV1-69-2,RP11-16E12.2,IGKV1OR2-108,IGHV5-10-1,IGHV1-69,IGHG1,IGKC,MZB1,DERL3,JCHAIN,IGHG3,IGHG4,IGLV2-14,IGHG2,IGKV1-39,IGHV4-59,IGHGP,IGKV1D-33,FCRL5,IGLC2,TNFRSF17,IGLV6-57,IGKV1-6,IGHA1,IGKV1D-39,IGKV1-16,IGKV3D-15,IGLV9-49,AC104971.3,AC104699.1
18 RACK1,ATP5F1E,ATP5MG,FYB1,NOP53,ATP5MC2,RIPOR2,TRIR,ELOB,ATP5MD,ATP5ME,ATP5IF1,ATP5MPL,ATP5MC3,MT-CYB,NSD3,PAXX,ATP5F1B,ATP5PF,ATP5MF,SELENOW,ATP5F1A,SELENOH,COPS9,ATP5PB,ATP5PD,TXNIP,MT-ND3,SELENOF,OGA
19 HLA-DQA1,HLA-DRB5,HLA-DRB1,CD74,HLA-DRA,AP003557.1,FXYD6,HLA-DQA2,HLA-DPA1,CXCL13,HLA-DQB1,CLDN16,PDLIM4,HLA-DPB1,CRTAM,RASSF4,UNQ6494,MIR155HG,PKM,TNFRSF9,LHFPL6,CAV1,MYOD1,PON3,MS4A6A,RP11-655C2.3,CD82,ZADH2,HOXB8,GUCY1B1
20 AC245427.1,NKG7,FCGR3A,PRF1,GPR56,FGFBP2,KLRF1,GNLY,TYROBP,SPON2,GZMB,KLRD1,FCER1G,CTSW,S1PR5,CST7,PLAC8,LOC101928429,CX3CR1,CLIC3,SH2D1B,ITGB2,FGR,AKR1C3,ADGRG1,CD247,PLEK,HOPX,LOC101060789,TRDC
21 FXYD2,TMEM155,TNFRSF9,CD27,CCL4L2,LOC100129931,CCL3L3,TRAV19,TNS3,GZMK,ETV1,CCL3,XCL1,CD82,HSPA12A,VCAM1,EMR1,MIR155HG,GEM,TTN,DSCAML1,NR5A2,CCL4,LOC101928983,EGR2,AL391056.1,LYST,DUSP4,XCL2,LINC00158
22 RPS15A,GZMK,RARRES3,RPL28,RPS27,RPL7A,RPL23A,ATP5E,RPS7,CMC1,CST7,RPS24,RPL30,RPS15,RPS25,AL627171.2,GNB2L1,RPL10,RPL13,NKG7,GIMAP4,RPS28,ATP5G2,RPS12,RPL35A,RPS14,ATP5L,RPL39,RPL36,CCL5
23 CYTB,ATP6,COX3,ND4L,COX2,ND1,ND5,ND2,ATP8,RPS14P3,ND3,MT-ND1,GAS5,MT-CO3,MT-CO2,ND4,HLA-H,MT-ND2,MT-ND3,MT-ATP6,LOC100507217,MT-CYB,MT-ND4,MT-ND4L,MT-ND5,MT-CO1,ND6,MT-RNR2,AC026366.1,CRISP3
24 ATP8,MALAT1,ATP6,ND4,ND4L,CYTB,ND2,COX1,ND3,RNR2,ND1,COX3,ND6,ND5,PTPRC,RNR1,RP11-463O12.5,NEAT1,MT-ATP6,MT-ND3,DDX17,SYNE2,NKTR,MT-RNR1,KIAA1551,MBNL1,RPL5P4,MT-ND5,COX2,MT-ND2
25 AIM1,IL7R,TXNIP,SMIM3,TSC22D3,ND5,AC007349.2,CRYBG1,CD97,GPR171,PARP8,FKBP5,PTGER4,ATP6,TNFAIP3,TPT1,RPLP1,PRDM1,ZFP36L2,PFKFB3,ZFP36,LOC101060038,ID2,RNR1,KLF6,NFKBIA,ITGA1,ND6,ND3,CD96
26 HLA-DRB4,LOC100996809,CD74,COTL1,TRBV11-3,HLA-DRB1,CD27,HLA-DRA,LOC101929876,LOC101928173,HLA-DPA1,TRBV5-5,ACTG1,ACTB,HLA-DPB1,HLA-DRB3,AC007993.3,GAPDH,GZMK,HLA-DQA1,FABP5,HLA-DQB1,TIGIT,ITM2A,PFN1,GZMA,HLA-DMA,PCAT29,TRAC,CXCL13
27 DUSP1,HSPA1B,DNAJB1,NR4A1,PPP1R15A,GADD45B,JUN,ACTB,NFKBIA,HSPA1A,TNF,CD69,JUNB,IFNG,DNAJB4,FOS,BTG2,SGK1,DDIT4,HSPA6,RHOB,FOSB,ATF3,IER3,IER2,TNFSF9,ACTG1,HSPA2,NR4A2,RGS16
28 8h.2,24h.2,BRE-AS1,RP11-631M6.2,FTH1P10,CREM,CXCR4,SRGN,ZFP36L2,RP11-463O12.5,YPEL5,BTG1,ZFP36,LOC101929876,ZNF331,EIF1,NR4A2,6h.2,TNFAIP3,FTH1,DUSP2,TUBA4A,COX7BP2,PIK3R1,FAM177A1,SARAF,H3F3B,SRSF2,MCL1,EZR
29 LAG3,CD27,GZMK,CMC1,CADM1,HMOX1,IFI6,ISG20,CST7,FXYD2,LINC01943,DUSP2,ISG15,MX1,TIMD4,RGS1,TIGIT,SIRPG,HLA-B,NKG7,DENND2D,DUSP4,ADTRP,CEMIP2,PRF1,HLA-A,SEM1,CNN2,PTPRCAP,HAVCR2
30 RPS2,RPL13,RPS12,RPS18,RPL10A,RPS14,RPL32,RPS4X,RPL10,RPS27A,RPLP1,EEF1A1,EEF1B2,RPS23,RPS3A,RPL18,RPL12,RPL29,RPS5,RPS8,RPL19,24h,RPSA,4h,8h,RPS6,6h,RPL30,RPS3,RPL11
⋮  ⋮
41 LMNA,VIM,MYADM,TAGLN2,S100A10,ADGRE5,S100A11,CRIP1,RGCC,ANXA1,RP11-124N14.3,CRIP2,AHNAK,ANXA2,CD44,GPAT3,EZR,MT-ND2,LRRFIP1,GPR183,CTD-3252C9.4,MT-ND1,AL022718.1,AAED1,RPL23AP42,IDS,AC016739.1,IL7R,AL590867.2,KLF6
42 COL1A1,MT-ATP6,MT-CYB,RARRES2,MT-CO3,MT-ND1,MT-CO1,MT-ND4,MT-CO2,TIMP3,BGN,LUM,MT-ND2,LGALS1,MT-ND3,COMP,MT-ND5,FN1,MYL9,MT-ND4L,DCN,SFRP2,COL1A2,CXCL14,INHBA,NNMT,UBE2L5P,CHRDL2,ATP5F1,MTRNR2L8
43 TFF2,CA9,FXYD4,DNAH3,AC106900.2,KRT13,KRT19,GP2,S100A6,AGR2,IFI27,WFDC2,SOX21-AS1,LINC01843,KRT8,CRYBA2,FXYD3,KISS1,CXCL17,LYZ,LINC00261,LGALS4,MAB21L4,CNNM1,EPCAM,S100A14,AC010745.1,CST3,TFF1,LINC02182
44 KLRB1,CTSH,S100A4,IL26,CCR6,S100A6,SPOCK2,LGALS3,FURIN,PTPN13,CAPG,JAML,ADAM12,CD40LG,SLC1A4,RORA,PKIG,TNFRSF25,OSTF1,ALOX5AP,CXCR6,AHR,LMO4,ADAM19,SH3BGRL3,NBAS,BATF,GNA15,KDSR,C10orf128
45 MT-ND4,MT-CO2,MT-CO3,MT-ATP6,MT-CYB,MT-CO1,MT-ND2,MT-ND1,MT-ND3,MT-ND5,SLIT1,PVRL4,MT-ND4L,MTATP6P1,MT-RNR1,TMPRSS11F,ANKRD30A,MTRNR2L10,RFX6,MT-TH,MT-RNR2,WARS2-IT1,PABPC4L,KCNN2,RNF225,SCGB1D2,MTRNR2L9,TMSB4XP8,MT-ATP8,MTRNR2L8
46 VIM,CRIP1,GATA3,S100A4,LTB,S100A10,ANXA1,HIST1H4C,LGALS1,PLP2,SEMA3G,ANXA2,LMNA,KRT1,RPL13AP20,SEMA5A,S100A6,BIRC3,SPC25,AHNAK,ANXA2P3,S100A11,MAP3K1,ARID5B,CCR10,TOB1,TSHR,IL7R,ITGB1,CRIP2
47 KRT7,LINC01681,SPATA22,SLPI,TMC5,PADI2,SALL2,S100A2,FXYD3,S100A9,LMO1,KRT17,MGST1,LCN2,MTND2P28,S100A11,MEI4,CP,SFN,TSPAN1,AGR2,PRSS2,TACSTD2,TFF3,AC139143.1,SERPINB3,SOWAHB,S100A16,SLC34A2,SFTPB
48 AC020916.1,HLA-DRB1,HLA-DRA,HLA-DRB5,PRMT9,CCL5,CD74,GZMA,GNLY,ZNF683,TMSB4X,HLA-DPA1,CYTOR,ITGB1,TRG-AS1,HLA-DPB1,HLA-DQA1,KRT86,ITGA1,KIR2DL1,CCL3,CCL4,KIR2DS4,CD63,AC114760.2,ITM2C,CCL3L1,CTSW,AL627171.1,TBCD
49 FTL,PSAP,CD68,SAT1,FTH1,TYROBP,LILRB2,FCER1G,PLAUR,APOE,S100A11,LST1,CXCL16,APOC1,SMIM25,NPC2,AIF1,C5AR1,CST3,CLEC7A,LRRC25,SPI1,TIMP1,ASAH1,FCN1,LILRA5,LGALS1,HLA-DRA,GRN,CTSD
50 FAM3B,CST3,LYZ,CPVL,HLA-DRA,HLA-DPB1,CLEC9A,HLA-DPA1,NAPSA,DCLK2,CD74,SPI1,AC096667.1,HLA-DQA1,HLA-DRB1,HLA-DRB5,HCK,LGALS2,C1orf54,IDO1,WDFY4,HLA-DQB1,ZNF366,MPEG1,DNASE1L3,RAB32,C15orf48,CDC25C,HIPK4,KIAA0226L
51 TRBV12-4,NRIP3,RASL10A,RP11-522I20.3,PTPN3,NPW,ATP5G3,HMGA1,ST8SIA3,CD81,FXYD2,CHAC1,CCNA2,SMCO4,FABP5,HN1,FST,ZNF704,KITLG,PLK1,SH3BP4,LGALS3,EFNA1,SKA1,HES1,ESPL1,STAC3,MYO7B,SGOL2,IL10
52 AC253572.1,CDC25C,KIF14,HN1,KIF15,MTFR2,KIAA0101,TUBA1B,FGGY,DEPDC1,HNRNPA1P48,UBE2C,HMGB2,CKS2,TPX2,TMSB4X,PTTG1,AC009299.3,ISG15,HMMR,MND1,TOP2A,PFN1,CFL1,BIRC5,CENPE,TUBB,CCNB2,CKS1B,SGOL1
53 MT-ATP6,MT-CO2,JUND,MT-CYB,MT-ND4,MT-CO3,MT-CO1,NEAT1,ARL4C,MT-ND3,MT-ND1,LINC00513,MT-ND5,TNFAIP3,CALM1,NCL,HSP90AB1,LCP1,KLK3,AC020916.1,DDX24,CD81,MT-ND4L,CRYBG1,KLK2,MBNL1,HNRNPAB,GRK2,METRNL,MT-ND6
54 AK4,DNTT,LDHA,ENO1,PKM,IL9R,MIF,PGK1,MYC,ALDOA,TAGLN2,IL32,RPLP0,LDHB,TPI1,PIM1,PABPC1,GAPDH,SOCS3,HSPA8,CISH,IL17RB,GPI,CSF2,TMEM123,EEF2,SELL,LTB,PIM2,PGAM1
55 GZMB,CD7,GNLY,CRX,SPINK2,KLRD1,CAPG,LGALS1,LRRC34,KLRC1,RP11-291B21.2,RP11-356J5.12,PGK1,LGALS3,CD63,PLEKHA6,PRF1,ADAMTS2,VIM,HOPX,GAPDH,IL12RB2,GPR25,IFITM2,LRAT,XCL1,CTSA,S100A6,GLUL,RP11-305L7.1
56 GAPDH,KRT86,GZMB,ENTPD1,TNFRSF9,TIGIT,TNFRSF18,CD7,LAYN,AC092580.4,LOC101929531,SNX9,ALOX5AP,TPI1,CXCL13,TNS3,PGAM1,PKM,HAVCR2,AC002331.1,RBPJ,PDLIM4,LAG3,CTSD,ITGAE,CTLA4,GOLIM4,IFITM10,MYO1E,CD82
57 AKR1B10,MRAP2,CXCL5,RAET1L,HOXC8,TLCD2,CRCT1,PLA2G4F,LCN2,VSTM5,S100P,KLK13,LINC00973,ESRP1,LINC01612,LY6K,EVA1A,TFF1,SPINK1,LINP1,KRT18,KRT8,KRT13,FRAS1,MT1G,SLPI,TSPAN8,GPX2,AL365356.5,SIX4
58 COL3A1,POSTN,COL1A1,COL1A2,COL6A1,COL6A3,CAPN6,LUM,SGCD,DCN,COL6A2,OAF,ANGPT1,BOC,ADGRA2,SEZ6L2,LHFPL2,EMILIN1,SPARC,DLK1,IGF2,RUNX1T1,EGFR,TMEM130,NR2F1,DCX,GAS1,PALM,COL4A1,MGP
59 CD7,KLRC2,KRT81,KRT86,KLRC3,LOC101060038,ZNF683,CD9,ND4L,CTSW,XCL1,TXK,KLRD1,CAPG,ND1,SRGAP3,LINC02446,AMICA1,KIR3DL2,CYTB,ND2,SPRY2,SPINT2,HOPX,IL2,NCR3,CD69,ND4,LILRP2,EPAS1
60 LINC01297,STON1,SLC52A3,FGFR3,MSMB,SLC2A5,PPARGC1A,AGR2,VANGL2,PDLIM3,RP11-115D19.1,MACROD2,ARHGAP6,WNT4,KLK2,ZNF350-AS1,MOGAT2,CDK14,CDC42EP5,ACPP,PRRG1,CCK,PLS3,CADPS2,VEGFA,IRX4,CLDN11,ORM1,ACSS3,KLK3
61 SFTPC,SFTPA2,SFTPA1,SCGB3A2,KRT8,FTH1,AL162511.1,KRT18,LINC01986,RPL7,RPS4X,NFKBIA,CXCL2,RPLP0,SFTPB,MMP7,RPL3,RPSA,ACTB,SPINT2,B2M,LCN2,MDK,RPS6,CD9,HLA-DRB1,JUNB,RACK1,ELF3,LDHB
62 TPSAB1,CNRIP1,GATA2,RP11-354E11.2,PRSS57,PNMT,HPGDS,MS4A2,CPA3,TPSB2,RUNDC3A,DPP10,RASGRP4,KRT1,SVOPL,TK1,KEL,EFHC2,GVQW1,KIAA0101,TYMS,TPSD1,LGALS12,DHRS9,GLUL,CXCL2,PDE6G,EXD3,PHACTR1,EMID1
63 MTRNR2L8,RPS4Y1,DDX3Y,H3F3B,MALAT1,CCNL1,NR4A2,SRSF7,CLK1,EIF1,RBM39,JUN,UTY,TTTY15,SBDS,SRSF5,AC245014.3,BTG1,HSPA5,DDX24,HLA-B,HIST1H1E,MIDN,SSBP3,H1FX,RPL27A,IFRD1,ITGAM,TRA2B,YPEL5
64 LINC01531,SEMA3B,PANK1,GPR37,ADSSL1,RP11-176H8.1,EMILIN1,LINC00839,S100A1,ZNF202,HSPB2,ADIRF,VN1R1,SMO,FABP3,ECHDC3,PPP1R3C,CKMT2-AS1,TM4SF4,PCSK4,PRDM5,GSTP1,RP11-172H24.4,GPX3,PPFIBP2,S100A16,SOD3,S100A14,GAS1,PKIB
65 HLA-H,CYTB,ND4,HLA-A,ND4L,ATP6,ATP8,ND2,ND1,NKG7,RNR2,FGFBP2,GZMH,COX2,ND3,S100A4,COX1,LGALS1,SH3BGRL3,ACTB,PFN1,CTSW,GZMB,CD8A,ITGB2,HLA-DRB5,COX3,ND5,FCGR3A,GNLY
66 IGHGP,ID4,LY6K,TUBB,RPS20,RPL29,RAB13,TM4SF1,EEF1A1,HES1,C1QB,TPPP3,RPL35A,MT-ND1,RPL8,HSP90AB1,RPS8,PSAT1,RPL7,PCP4,SNCG,RPL12,PART1,HSPA6,IGKC,RPS18,SELENBP1,IGLC7,RBP1,RPL31
67 RP11-1033A18.1,DNAJB1,HSP90AA1,HSPA1A,RP11-485G4.2,HSPA1B,HSPH1,HSP90AB1,HSPE1,HSPD1,HSPA8,DNAJA1,RP11-153M3.1,CACYBP,HSP90AA2P,GOT2P2,UBB,HSPB1,BAG3,ZFAND2A,TIMM8AP1,HSPA6,GGNBP1,PPP1R15A,UBC,RP11-142L4.2,HSP90AB3P,MIRLET7D,SERPINH1,LOC101928304
68 AFF3,ZFP41,MT.ND3,BEND6,EVI5,PLEKHG6,UBD,MT.ND2,C2orf88,BHLHB9,RNU12,CTSK,C16orf59,SLC44A3,MT.ND1,OSBPL10.AS1,RALY.AS1,COL17A1,CTA.221G9.12,RP11.344P13.6,MT.CO3,RP11.102N12.3,RP11.297B17.3,FCER2,SLC12A8,TM4SF1,MT.ATP6,ASAP3,ATP2A1,LA16c.306E5.2
69 GNLY,S100A4,TMSB10,TRBV7-6,IFITM2,RPL39,S100A6,TRAV8-1,ATP5E,SH3BGRL3,SERF2,FXYD5,MT-ND3,RPL41,MYL12A,S100A11,TMSB4X,RPS4Y1,GZMB,RPL36A,TMA7,HSPA1A,RPS18,OST4,RPS21,S100A10,TRAV10,HCST,PFN1,IFITM1
70 HBB,HBD,AHSP,SNCA,CA1,HBA2,ALAS2,HBA1,SLC4A1,SELENBP1,SLC25A37,PDZK1IP1,TRIM58,HBM,HBQ1,GMPR,HEMGN,KLHL33,KLF1,SLC25A39,HBG2,STRADB,EPB42,PLEK2,BLVRB,NFIX,NFE2,TNS1,BNIP3L,IGF2BP2

In [5]:
#OUT_FILE <- "./3.cGEP_topgene/3.3.CD8T_cGEP_Anno_Complete_With_Genes_filt.csv"
OUT_FILE <- '/sibcb1/bioinformatics/yangyue/project/immunotherapy/7.6.cNMF_menchmark/cGEP_signature/CD8T_cGEP70_signature.csv'
write.csv(final_combined_df, OUT_FILE, row.names = FALSE)