In [3]:
library(dplyr)
library(tidyr)
library(pheatmap)
library(viridis)
library(tools)
library(cluster)
library(igraph)
library(tibble)

library(clusterProfiler)
library(org.Hs.eg.db)
library(dplyr)

In [4]:
# 读入
signature_NK <- read.csv(
  "/sibcb1/bioinformatics/yangyue/project/immunotherapy/7.3.cNMF_NK/cnmf_NK_out_Sample_counts/NK_cGEP_Top30_Genes_spectra_normalized_fil.csv",row.names = 1,
  check.names = FALSE,
  stringsAsFactors = FALSE)
# 转成 list（核心）
cluster_genes <- lapply(signature_NK, function(x) {
  x[!is.na(x) & x != ""]
})


gene_df <- data.frame(
  cGEP_Cluster = names(cluster_genes),  # 确保这里是 cGEP1, cGEP2...
  cGEP_signature = sapply(cluster_genes, function(x) paste(x, collapse = ",")),
  stringsAsFactors = FALSE
)
gene_df

       cGEP_Cluster
cGEP1  cGEP1
cGEP2  cGEP2
cGEP3  cGEP3
cGEP4  cGEP4
cGEP5  cGEP5
cGEP6  cGEP6
cGEP7  cGEP7
cGEP8  cGEP8
cGEP9  cGEP9
cGEP10 cGEP10
cGEP11 cGEP11
cGEP12 cGEP12
cGEP13 cGEP13
cGEP14 cGEP14
cGEP15 cGEP15
cGEP16 cGEP16
cGEP17 cGEP17
cGEP18 cGEP18
cGEP19 cGEP19
cGEP20 cGEP20
cGEP21 cGEP21
cGEP22 cGEP22
cGEP23 cGEP23
cGEP24 cGEP24
cGEP25 cGEP25
cGEP26 cGEP26
cGEP27 cGEP27
cGEP28 cGEP28
cGEP29 cGEP29
cGEP30 cGEP30
cGEP31 cGEP31
cGEP32 cGEP32
cGEP33 cGEP33
cGEP34 cGEP34
cGEP35 cGEP35
cGEP36 cGEP36
cGEP37 cGEP37
cGEP38 cGEP38
cGEP39 cGEP39
cGEP40 cGEP40
cGEP41 cGEP41
       cGEP_signature
cGEP1  CYTB,COX2,ATP6,ND4L,COX3,ND1,EIF1,ND5,6h.2,ATP8,H3F3B,AC107241.1,HLA-H,4h.2,C20orf24,PTMA,0h.1,FTH1,24h.2,ND4,LITAF,RBM39,SRSF5,ND2,DNAJB6,TMEM56,CEMIP2,RPS14P3,PDE4D,ND3
cGEP2  PFN1,ACTB,FCER1G,HSPA1A,IFITM1,TMSB10,MYL12A,NKG7,SERF2,TMSB4X,GSTP1,ND3,PPIA,ATP5E,IFITM2,ALOX5AP,AC245427.1,CFL1,TYROBP,ATP5F1E,HSPA1B,DNAJB1,MTRNR2L2,CLIC1,ATP5MF,MIF,HCST,B2M,RAC2,RPL39
cGEP3  RPS12,RPS2,RPS3,RPS27,RPS18,RPS15A,RPS14,EEF1A1,RPL13,RPL3,RPS4X,RPS28,RPL32,RP11-761N21.2,RP11-864N7.2,RPL34,RPL10,RPL23A,RPS23,RPL18A,RPS6,RPL19,RPS27A,RPL26,RPS8,PLAAT4,RPL30,RPS19,RPS29,RPL11
cGEP4  DNAJB1,HSPA1A,HSP90AA1,HSPE1,HSPA1B,HSPH1,HSPD1,BAG3,HSPA6,CACYBP,ZFAND2A,HSPA8,COL21A1,HSP90AB1,HSPB1,HSP90AA2P,DNAJA1,SERPINH1,PPP1R15A,UBC,NR4A1,ATF3,FKBP4,DNAJB4,MRPL18,JUN,DOK2,TFF1,TNFSF14,DEDD2
cGEP5  ZFP36,BTG2,NR4A2,JUNB,NR4A1,CD69,TNFAIP3,LOC284454,CXCR4,FOSB,RP11-463O12.5,NFKBIA,MCL1,JUN,PPP1R15A,AREG,IER2,DUSP2,NFKBIZ,ZNF331,FOS,AC027290.2,KDM6B,TSC22D3,REL,CSRNP1,DNAJA1,DUSP1,EGR1,NR4A3
cGEP6  IGFBP1,ITIH3,AL158850.1,MT-ND4,MT-CO3,MT-CO2,MT-CYB,MT-ATP6,MT-ND1,MT-ND3,MT-ND2,LBP,MT-CO1,RHEX,PNCK,MT-ND5,FGL1,FGA,ORM1,IGHV4-34,MT-ND4L,APOB,AL445673.1,NTM,CRP,PLA2G2A,SAA1,ROR1,UGT2B7,F2
cGEP7  BTG1,ITM2C,RPL13A,KRT81,RPS20,CAPG,RPS26,GZMK,RPL27A,KRT86,MALAT1,RPS2,CXCR6,CD44,RPS29,RPL37A,TXNIP,CXCR4,LINC00996,CD9,APOBEC3G,PNRC1,SLFN5,CXCR3,VIM,EPHA1,AC026366.1,RPLP2,RPL10A,SRGAP3
cGEP8  RPS12,RPL13,RPLP1,TPT1,IL7R,CCR6,RPL32,NCR2,RPL30,EEF1A1,RPL10,RPS23,APOC4-APOC2,AL445686.2,RPL28,GPR183,RPL34,RPS8,RPL8,RPLP0,VIM,AMICA1,RPS18,U62317.3,RPS14,RPL11,RPL41,RPS5,RPS13,RPS25
cGEP9  NKG7,PRF1,SPON2,FGFBP2,GZMB,FCGR3A,SCGB1D2,B2M,ITGB2,CST7,PFN1,GZMA,ACTB,IGFBP7,GPR56,CX3CR1,CYBA,CFL1,AKR1C3,TMSB10,FCER1G,CD247,MT-COX1,PRSS23,MYL12A,LOC101060789,PLAC8,S100A4,EMP3,GZMH
cGEP10 TYMS,STMN1,TUBA1B,UBE2C,SPC25,MKI67,AURKB,TK1,DLGAP5,ASPM,TUBB,CDC20,CDK1,NUSAP1,TOP2A,PCLAF,ZWINT,CDC45,CCNB2,HMGB2,CENPF,UHRF1,CKAP2L,KIF15,BIRC5,KIF23,CENPW,CENPA,KIF2C,CDCA5
cGEP11 CD3D,CD3G,SIT1,CD8B,S100A6,TRGV11,LAG3,CD3E,S100A4,CD8A,CXCL13,TRGV2,CD5,TRBV14,TRAV8-1,TRBV6-1,TRBV11-3,TRAV38-1,TRBV27,SH3BGRL3,CD52,TMEM155,TRAC,TRAV9-2,VCAM1,TRAV8-2,CD27,LINC02446,THEMIS,F5
cGEP12 SCGB3A2,RP5-851M4.1,FABP4,PGC,RPS29,GS1-600G8.5,SLC4A10,RPL13A,RPS20,GS1-259H13.2,CUEDC1,RPLP2,LTB,RP11-1143G9.4,RNASE2,RP11-589M4.1,SCGB1A1,RPL27A,RPS17,PIFO,IL7R,RPL41,TREM1,TRAC,ALOX15B,RPL31,RPS18,RPL23A,RPS2,AL121845.1
cGEP13 MS4A2,HDC,TPSAB1,TPSB2,SLC18A2,HPGDS,MAOB,KIT,CTTNBP2,CPA3,SDPR,CCL2,CPM,MITF,ALDH1A1,RGS13,DHRS9,SPDYE1,ALOX5,LPCAT2,TMEM255B,GATA2,IL1RL1,VWA5A,DPP6,CRISPLD2,HPGD,PROS1,CLEC3B,CNRIP1
cGEP14 ISG15,IFIT3,IFI6,MX1,RSAD2,USP18,IFIT1,CMPK2,EPSTI1,OAS1,MX2,ISG20,IFI44L,IFI35,PLSCR1,LY6E,IRF7,IFITM1,TNFSF10,HERC5,EIF2AK2,LAMP3,IFI16,AC090377.1,ERICH3,IFIT2,OASL,OAS3,BST2,XAF1
cGEP15 AC026801.2,CXCL2,AC124242.1,AQP9,CCL20,CLEC4E,AIF1,LILRA5,FCN1,CST3,BASP1,LINC01272,CCDC149,C5AR1,HBEGF,IL1B,LST1,HCK,ANKRD30B,MS4A7,SMIM25,CSF1R,TNFAIP6,CLEC7A,ENHO,BLOC1S1-RDH5,HLA-DRA,LOC100130520,FTL,RAB31
cGEP16 CST3,C1QC,C1QB,HLA-DRA,C1QA,APOE,CD74,HLA-DRB1,HLA-DPA1,SELENOP,HLA-DRB5,HLA-DPB1,AIF1,HLA-DQA1,RNASE1,APOC1,HLA-DQB1,MS4A6A,CD68,LINC01736,FTL,CD209,FCGRT,CSF1R,LGMN,MS4A7,TREM2,CD1E,CTSB,CD5L
cGEP17 LINC01943,AC017002.3,IL2RA,CTLA4,TRAC,TNFRSF4,IL1R2,FOXP3,ICOS,CD4,ZBTB32,AC133644.2,IL32,BATF,TNFRSF9,CD27,F5,TBC1D4,CAVIN3,GADD45A,CD28,CD3D,TNFRSF18,PKM,DNPH1,RTKN2,ID3,KCNN4,DUSP4,SLAMF1
cGEP18 ACTB,ACTG1,PFN1,SH3BGRL3,GAPDH,TMSB4X,CFL1,CORO1A,CKLF,ENO1,S100A4,LGALS1,MYL6,PSME2,HLA-H,S100A6,RAC2,CLIC1,CALR,ALDOA,S100A11,LDHA,COTL1,ARPC1B,ANXA2,MYL12A,TPI1,MIF,GZMA,CD3D
cGEP19 CD3D,CD8B,CD8A,PTPRC,HLA-A,SARAF,GZMK,TRBC2,LEPROTL1,CXCR4,CXCR3,LDHA,TCEB2,CD3G,OASL,CD6,TUBA4A,BTG1,MALINC1,AL049780.2,CD3E,HLA-B,DUSP4,ATP5I,RESF1,ATP5J2,RGS1,CALM2,ATP1B3,EZR
cGEP20 IGLV1-44,HLA-DRA,IGHV4-34,CD79A,IGHV3-23,CD74,MS4A1,TIGD3,IGLL5,IGHM,FCER2,LINC01857,ARHGAP24,LOC100507616,POU2AF1,KIAA0226L,COL19A1,LINC00926,NAPSB,AL928742.1,VPREB3,PAX5,IGLC2,HLA-DQA1,FMOD,RUBCNL,MARCH1,FCRL1,CD24,ROR1
cGEP21 SDPR,CXCR2P1,AP001189.4,PPBP,PF4,TUBB1,RP3-324O17.8,KCNE3,GNG11,CD36,CLEC1B,GP1BA,ITGA2B,F13A1,CAVIN2,NRGN,CTTN,BEX3,C19orf33,CLU,MYL9,TGFB1I1,TREML1,C2orf88,SPARC,SH3BGRL2,GGTA1P,PARVB,RNU2-68P,0h.3
cGEP22 CD7,SPTSSB,FCER1G,GPR97,TNFRSF18,XCL1,RPLP1,CAPG,GSTP1,XCL2,EEF1A1,TPT1,CTSW,KLRF2,NCR2,RPS24,RPSA,HOPX,RPS18,AL157895.1,IL2RB,IFITM3,TYROBP,RPS23,TRDC,COTL1,RPL15,RP11-796E2.4,RPL37,RPS8
cGEP23 CRTAM,TNFRSF9,CCL4L2,XCL1,CCL4L1,XCL2,CCL4,EGR2,HBA2,AL031666.3,GAPDH,RILPL2,HBA1,CCL3,NFKBID,MIR155HG,CD82,ZFP36L1,SDC4,TNF,GEM,PDCD1,PKM,GHET1,VWDE,EPOP,EGR3,AL590326.2,FXYD2,LINC01686
cGEP24 VCAN,S100A8,RPS27,S100A9,RPL13,AC090498.1,RPL21,RPL34,RPS29,RPS12,RPS14,NRGN,RPS3,CSTA,CD300E,RPL3,FPR1,RPL32,RPS27A,RPL39,RP11-631N16.2,RPS18,MT-ND3,RPL13A,RPL35A,AC013264.2,RPS15A,MT-ND4,RPS3A,S100A12
cGEP25 GLTSCR2,AL627171.2,APOL4,RPS3A,TRBV11-2,CRYGD,AC079341.1,RPS28,TXNIP,LIMD2,AES,RPL37A,RPL18A,RPL7,FAM65B,RPS12,RPL28,RPL34,GNB2L1,EEF1A1,RPL31,GIMAP7,AL353593.1,RPL32,RPL35A,DAPL1,RPS4X,RPL9,AK8,RPL14
cGEP26 AC084033.3,KRT13,CHRM3,MYCT1,FCER1A,OCRL,KRT5,PRSS57,HOXA9,SOX4,IL1B,RACK1,BST1,GATA2,PTN,LY6D,GBP6,KRT15,GUCY1B1,ANK1,CAVIN1,CNRIP1,RP5-1158E12.3,ADGRE2,RPS8,TCTEX1D1,NPR3,KRT6A,CYTL1,RPS24
cGEP27 FCER1G,CD7,CD160,TYROBP,IL2RB,CLIC3,IRF8,NFKBIA,KLRF1,FOS,IER2,DUSP1,XCL2,CD247,KLRC1,EML2-AS1,TOX2,SLC15A4,ADGRE5,TIE1,B3GNT7,ITGA2B,LAT2,REL,IFITM3,ZBTB16,CMC1,CCL3,AL669831.1,MAFF
cGEP28 OGA,MALAT1,TUT4,MT-RNR1,CH17-189H20.1,SYNE2,NKTR,RPL5P4,PRRC2C,IGHV3-23,CCNL1,ZNF292,PRPF4B,BCLAF1,SRSF11,RP11-463O12.5,PTPRC,IGHV1-46,PIK3R1,SYNE1,MT-RNR2,RBM25,RNA28S,RP11-575L7.8,ANKRD12,SFPQ,NEAT1,GOLGA4,SON,CEMIP2
cGEP29 EZR,CREM,CD55,DNAJB6,PTGES3,CHORDC1,SELK,PABPC1,EIF1,DNAJA1,EIF5,OAZ1,CACYBP,SLC3A2,HSP90AB1,VPS37B,ELL2,CYSTM1,TXNRD1,BAZ1A,MIR22HG,JMJD6,RGCC,MTHFD2,FTL,CTD-2192J16.22,FOSL2,UBE2B,UBE2D3,YWHAZ
cGEP30 S100B,MT2A,KIR3DL1,AC022431.1,FTH1,AC008038.1,MCOLN3,EEF1A1,NCBP2-AS2,RPL12,RPL11,AC026979.3,AC024293.1,HLA-C,S100A6,RPS15AP1,SUSD4,EIF1,RPL8,RPL32,RPS10P3,RPL19,RPLP0,AL139100.1,RPL10,S100A4,AC078817.1,RPL18,RPL34,RPS8
cGEP31 RP11-796E2.4,GADD45B,RP11-727F15.9,RP11-467L13.7,CTA-29F11.1,RP11-596C23.2,RP11-318A15.2,RP5-821D11.7,RP11-307C12.13,FLJ21408,RP11-713P17.3,LINC00936,RP11-108M9.6,RP11-422P24.12,RP11-356I2.4,CTD-2035E11.3,AC061992.2,JUN,CMB9-22P13.1,JUNB,RP1-34B20.21,IER2,RP1-168L15.5,DUSP1,CD69,RHOB,RP13-516M14.4,RP11-380J14.4,RP11-290C10.1,RP11-61J19.5
cGEP32 HBB,HBA2,ALAS2,SLC25A37,SNCA,HBA1,TBC1D4,DMTN,GMPR,GLS2,BNIP3L,AHSP,DCAF12,MPP1,HBD,SLC25A39,BSG,FECH,BLVRB,AC022167.3,FAM210B,EIF1AY,NCOA4,CA1,THEM5,SPTA1,IFIT1B,RHAG,SLC1A5,GYPB
cGEP33 AZU1,MT-CO2,MT-ATP6,PRTN3,MT-ND3,MT-CO3,MT-ND4L,MT-CO1,MT-ND4,ELANE,MT-CYB,MT-ND1,MT-ND2,MPO,NPW,RPL41,CTSG,AC084033.3,KLRD1,TRBC2,IL7R,ATP5MPL,MT-ATP8,SRGN,MT-ND5,ATP5ME,RAB32,AC092580.4,PCLAF,IGFBP2
cGEP34 LOC101928173,MIR155HG,TNFRSF9,CD82,MT1L,LOC102724850,CD74,APOBEC3G,PGAM1,CD27,GZMH,PKM,CD8A,ZBED2,PDCD1,HLA-B,LAG3,IL2RA,GAPDH,GZMB,DUSP4,TIGIT,LOC100996809,VCAM1,NKG7,HLA-A,LYST,PARK7,FKBP1A,APOBEC3C
cGEP35 ACTB,CORO1A,IL32,CCL4,RP5-1028K7.2,POTEF,PFN1,CCL3,ACTG1,MYL12A,EVL,FCRL6,ITGB2,PSMB9,CD48,ARPC1B,CD69,ATP5F1E,HP,GIMAP4,FYB,TBC1D10C,AC006129.2,ALB,TRAV12-2,APOA2,TRG-AS1,RP11-386I14.4,CISD3,STAT1
cGEP36 IGHV4-39,TNFRSF17,JCHAIN,IGLL5,IGKV3-15,IGHV5-78,IGKV1-5,IGHG2,EBF1,AC021678.2,IGHG1,PNOC,POU2AF1,MZB1,IGHG4,IGKV3OR2-268,DERL3,IGKC,TXNDC5,IGHA1,ZNF860,IGLV3-21,IGHA2,CD79A,CHAD,BHLHE41,IGKV4-1,ITM2C,FCRLA,IGHV4-34
cGEP37 KRT86,KRT81,LDLRAD4,WIPF3,RBPJ,ITGA1,TNFRSF18,CSF1,KIR2DL4,NDFIP2,ENTPD1,SAMSN1,ZNF683,KLRC1,SRGAP3,CD9,CAPG,SLC16A3,DUSP4,CD7,KRT83,CEBPB,GZMA,SLC7A5,TBCD,ADGRG3,AFAP1L2,LILRP2,GNLY,COTL1
cGEP38 FCER1A,CRHBP,AL157895.1,TMEM98,GATA2,FAM19A2,PBX1,NFIA,CASC15,AVP,GATA1,CYTL1,LINC02573,TPTEP1,CFH,TIMP3,ZSCAN20,MS4A3,ALDH1A1,PCDH9,STON2,GSTO2,STOX1,IL7R,HTR1F,FHL1,RBPMS,SOCS2,MARCKSL1,OAZ2
cGEP39 GZMB,KLF2,LAIR2,SELL,FGFBP2,ORAI1,KIR3DL1,PXN,KLF3,PRSS23,ATXN8OS,TXNIP,ADGRG1,ARL4C,AKR1C3,CEP78,CD55,CX3CR1,PLAC8,PDE4D,IL7R,KIR3DX1,GNLY,MTRNR2L10,NKG7,IGFBP7,SYNE1,EFHD2,S1PR5,UCP2
cGEP40 XCL1,GPR183,CD44,SELL,TCF7,TNFRSF11A,ITGAX,MAFF,COTL1,FLNB,MAP3K8,CD82,HAPLN3,AC103591.3,AREG,IFITM3,NFKB1,HIF1A,TMEM123,XCL2,OTULIN,FOXC1,IL7R,DUSP4,GAB1,JAG1,KLRC1,SCML1,TIAM1,NCAM1
cGEP41 LYZ,FTL,VSIR,OLR1,TYROBP,ADA2,SRGN,S100A4,CYBA,S100A6,VCAN,CSTA,CCL3,FCER1G,CFD,EMP3,GRN,RNASE6,PDPN,S100A9,S100A10,MNDA,LGALS1,GPX1,TYMP,CTSB,AOC1,FOSL2,FTH1,C15orf48

In [6]:
#NK_gep_anno <- read.csv('./3.3.NK_cGEP_ALL_ANNO/3.3.NK_cGEP_Anno_final.csv')
NK_gep_anno <- read.csv('/sibcb1/bioinformatics/yangyue/project/immunotherapy/7.6.cNMF_menchmark/cGEP_signature/NK_cGEP41.csv')

NK_gep_anno

   cGEP_Cluster cGEP_Anno_Name           Category
1  cGEP1        Low_Quality_Mito         Artifact
2  cGEP10       NK_Cycling_G2M           Functional
3  cGEP11       Doublet_CD8_T            Doublet
4  cGEP12       Doublet_Club_Cell        Doublet
5  cGEP13       Doublet_Mast             Doublet
6  cGEP14       NK_ISG_Response          Functional
7  cGEP15       Inflammatory_Chemokine   Functional
8  cGEP16       Doublet_Macrophage       Doublet
9  cGEP17       Doublet_Treg             Doublet
10 cGEP18       Doublet_T_Cytoskeleton   Doublet
11 cGEP19       Doublet_CD8_T            Doublet
12 cGEP2        TaNK_Cytoskeleton_Stress Functional
13 cGEP20       Doublet_B_Cell           Doublet
14 cGEP21       Doublet_Platelet         Doublet
15 cGEP22       CD56bright_Regulatory    Lineage
16 cGEP23       NK_Activation_Chemokine  Functional
17 cGEP24       Doublet_Monocyte_S100    Doublet
18 cGEP25       Doublet_T_Clone          Doublet
19 cGEP26       Artifact_Epithelial      Artifact
20 cGEP27       NK_Activation_Signaling  Functional
21 cGEP28       RNA_Processing           Functional
22 cGEP29       Stress_HSP90             Functional
23 cGEP3        Translational_Activity   Functional
24 cGEP30       NK_KIR_Maturity          Lineage
25 cGEP31       trNK_Stress              Lineage
26 cGEP32       Artifact_RBC             Artifact
27 cGEP33       Doublet_Neutrophil       Doublet
28 cGEP34       NK_Exhaustion            Functional
29 cGEP35       NK_Motility_Cytoskeleton Functional
30 cGEP36       Doublet_Plasma_Cell      Doublet
31 cGEP37       Artifact_Keratinocyte    Artifact
32 cGEP38       Doublet_Mast_Cell        Doublet
33 cGEP39       NK_Cytotoxic_Circulating Functional
34 cGEP4        TaNK_HSP_Stress          Functional
35 cGEP40       CD56bright_Homing        Lineage
36 cGEP41       Doublet_Myeloid_LYZ      Doublet
37 cGEP5        NK_Activation_IEG        Functional
38 cGEP6        Acute_Inflammatory       Functional
39 cGEP7        trNK_Quiescence          Lineage
40 cGEP8        CD56bright_Translation   Lineage
41 cGEP9        CD56dim_Cytotoxic        Lineage

In [7]:
final_combined_df <- NK_gep_anno %>%
  left_join(gene_df, by = "cGEP_Cluster")
final_combined_df

   cGEP_Cluster cGEP_Anno_Name           Category
1  cGEP1        Low_Quality_Mito         Artifact
2  cGEP10       NK_Cycling_G2M           Functional
3  cGEP11       Doublet_CD8_T            Doublet
4  cGEP12       Doublet_Club_Cell        Doublet
5  cGEP13       Doublet_Mast             Doublet
6  cGEP14       NK_ISG_Response          Functional
7  cGEP15       Inflammatory_Chemokine   Functional
8  cGEP16       Doublet_Macrophage       Doublet
9  cGEP17       Doublet_Treg             Doublet
10 cGEP18       Doublet_T_Cytoskeleton   Doublet
11 cGEP19       Doublet_CD8_T            Doublet
12 cGEP2        TaNK_Cytoskeleton_Stress Functional
13 cGEP20       Doublet_B_Cell           Doublet
14 cGEP21       Doublet_Platelet         Doublet
15 cGEP22       CD56bright_Regulatory    Lineage
16 cGEP23       NK_Activation_Chemokine  Functional
17 cGEP24       Doublet_Monocyte_S100    Doublet
18 cGEP25       Doublet_T_Clone          Doublet
19 cGEP26       Artifact_Epithelial      Artifact
20 cGEP27       NK_Activation_Signaling  Functional
21 cGEP28       RNA_Processing           Functional
22 cGEP29       Stress_HSP90             Functional
23 cGEP3        Translational_Activity   Functional
24 cGEP30       NK_KIR_Maturity          Lineage
25 cGEP31       trNK_Stress              Lineage
26 cGEP32       Artifact_RBC             Artifact
27 cGEP33       Doublet_Neutrophil       Doublet
28 cGEP34       NK_Exhaustion            Functional
29 cGEP35       NK_Motility_Cytoskeleton Functional
30 cGEP36       Doublet_Plasma_Cell      Doublet
31 cGEP37       Artifact_Keratinocyte    Artifact
32 cGEP38       Doublet_Mast_Cell        Doublet
33 cGEP39       NK_Cytotoxic_Circulating Functional
34 cGEP4        TaNK_HSP_Stress          Functional
35 cGEP40       CD56bright_Homing        Lineage
36 cGEP41       Doublet_Myeloid_LYZ      Doublet
37 cGEP5        NK_Activation_IEG        Functional
38 cGEP6        Acute_Inflammatory       Functional
39 cGEP7        trNK_Quiescence          Lineage
40 cGEP8        CD56bright_Translation   Lineage
41 cGEP9        CD56dim_Cytotoxic        Lineage
   cGEP_signature
1  CYTB,COX2,ATP6,ND4L,COX3,ND1,EIF1,ND5,6h.2,ATP8,H3F3B,AC107241.1,HLA-H,4h.2,C20orf24,PTMA,0h.1,FTH1,24h.2,ND4,LITAF,RBM39,SRSF5,ND2,DNAJB6,TMEM56,CEMIP2,RPS14P3,PDE4D,ND3
2  TYMS,STMN1,TUBA1B,UBE2C,SPC25,MKI67,AURKB,TK1,DLGAP5,ASPM,TUBB,CDC20,CDK1,NUSAP1,TOP2A,PCLAF,ZWINT,CDC45,CCNB2,HMGB2,CENPF,UHRF1,CKAP2L,KIF15,BIRC5,KIF23,CENPW,CENPA,KIF2C,CDCA5
3  CD3D,CD3G,SIT1,CD8B,S100A6,TRGV11,LAG3,CD3E,S100A4,CD8A,CXCL13,TRGV2,CD5,TRBV14,TRAV8-1,TRBV6-1,TRBV11-3,TRAV38-1,TRBV27,SH3BGRL3,CD52,TMEM155,TRAC,TRAV9-2,VCAM1,TRAV8-2,CD27,LINC02446,THEMIS,F5
4  SCGB3A2,RP5-851M4.1,FABP4,PGC,RPS29,GS1-600G8.5,SLC4A10,RPL13A,RPS20,GS1-259H13.2,CUEDC1,RPLP2,LTB,RP11-1143G9.4,RNASE2,RP11-589M4.1,SCGB1A1,RPL27A,RPS17,PIFO,IL7R,RPL41,TREM1,TRAC,ALOX15B,RPL31,RPS18,RPL23A,RPS2,AL121845.1
5  MS4A2,HDC,TPSAB1,TPSB2,SLC18A2,HPGDS,MAOB,KIT,CTTNBP2,CPA3,SDPR,CCL2,CPM,MITF,ALDH1A1,RGS13,DHRS9,SPDYE1,ALOX5,LPCAT2,TMEM255B,GATA2,IL1RL1,VWA5A,DPP6,CRISPLD2,HPGD,PROS1,CLEC3B,CNRIP1
6  ISG15,IFIT3,IFI6,MX1,RSAD2,USP18,IFIT1,CMPK2,EPSTI1,OAS1,MX2,ISG20,IFI44L,IFI35,PLSCR1,LY6E,IRF7,IFITM1,TNFSF10,HERC5,EIF2AK2,LAMP3,IFI16,AC090377.1,ERICH3,IFIT2,OASL,OAS3,BST2,XAF1
7  AC026801.2,CXCL2,AC124242.1,AQP9,CCL20,CLEC4E,AIF1,LILRA5,FCN1,CST3,BASP1,LINC01272,CCDC149,C5AR1,HBEGF,IL1B,LST1,HCK,ANKRD30B,MS4A7,SMIM25,CSF1R,TNFAIP6,CLEC7A,ENHO,BLOC1S1-RDH5,HLA-DRA,LOC100130520,FTL,RAB31
8  CST3,C1QC,C1QB,HLA-DRA,C1QA,APOE,CD74,HLA-DRB1,HLA-DPA1,SELENOP,HLA-DRB5,HLA-DPB1,AIF1,HLA-DQA1,RNASE1,APOC1,HLA-DQB1,MS4A6A,CD68,LINC01736,FTL,CD209,FCGRT,CSF1R,LGMN,MS4A7,TREM2,CD1E,CTSB,CD5L
9  LINC01943,AC017002.3,IL2RA,CTLA4,TRAC,TNFRSF4,IL1R2,FOXP3,ICOS,CD4,ZBTB32,AC133644.2,IL32,BATF,TNFRSF9,CD27,F5,TBC1D4,CAVIN3,GADD45A,CD28,CD3D,TNFRSF18,PKM,DNPH1,RTKN2,ID3,KCNN4,DUSP4,SLAMF1
10 ACTB,ACTG1,PFN1,SH3BGRL3,GAPDH,TMSB4X,CFL1,CORO1A,CKLF,ENO1,S100A4,LGALS1,MYL6,PSME2,HLA-H,S100A6,RAC2,CLIC1,CALR,ALDOA,S100A11,LDHA,COTL1,ARPC1B,ANXA2,MYL12A,TPI1,MIF,GZMA,CD3D
11 CD3D,CD8B,CD8A,PTPRC,HLA-A,SARAF,GZMK,TRBC2,LEPROTL1,CXCR4,CXCR3,LDHA,TCEB2,CD3G,OASL,CD6,TUBA4A,BTG1,MALINC1,AL049780.2,CD3E,HLA-B,DUSP4,ATP5I,RESF1,ATP5J2,RGS1,CALM2,ATP1B3,EZR
12 PFN1,ACTB,FCER1G,HSPA1A,IFITM1,TMSB10,MYL12A,NKG7,SERF2,TMSB4X,GSTP1,ND3,PPIA,ATP5E,IFITM2,ALOX5AP,AC245427.1,CFL1,TYROBP,ATP5F1E,HSPA1B,DNAJB1,MTRNR2L2,CLIC1,ATP5MF,MIF,HCST,B2M,RAC2,RPL39
13 IGLV1-44,HLA-DRA,IGHV4-34,CD79A,IGHV3-23,CD74,MS4A1,TIGD3,IGLL5,IGHM,FCER2,LINC01857,ARHGAP24,LOC100507616,POU2AF1,KIAA0226L,COL19A1,LINC00926,NAPSB,AL928742.1,VPREB3,PAX5,IGLC2,HLA-DQA1,FMOD,RUBCNL,MARCH1,FCRL1,CD24,ROR1
14 SDPR,CXCR2P1,AP001189.4,PPBP,PF4,TUBB1,RP3-324O17.8,KCNE3,GNG11,CD36,CLEC1B,GP1BA,ITGA2B,F13A1,CAVIN2,NRGN,CTTN,BEX3,C19orf33,CLU,MYL9,TGFB1I1,TREML1,C2orf88,SPARC,SH3BGRL2,GGTA1P,PARVB,RNU2-68P,0h.3
15 CD7,SPTSSB,FCER1G,GPR97,TNFRSF18,XCL1,RPLP1,CAPG,GSTP1,XCL2,EEF1A1,TPT1,CTSW,KLRF2,NCR2,RPS24,RPSA,HOPX,RPS18,AL157895.1,IL2RB,IFITM3,TYROBP,RPS23,TRDC,COTL1,RPL15,RP11-796E2.4,RPL37,RPS8
16 CRTAM,TNFRSF9,CCL4L2,XCL1,CCL4L1,XCL2,CCL4,EGR2,HBA2,AL031666.3,GAPDH,RILPL2,HBA1,CCL3,NFKBID,MIR155HG,CD82,ZFP36L1,SDC4,TNF,GEM,PDCD1,PKM,GHET1,VWDE,EPOP,EGR3,AL590326.2,FXYD2,LINC01686
17 VCAN,S100A8,RPS27,S100A9,RPL13,AC090498.1,RPL21,RPL34,RPS29,RPS12,RPS14,NRGN,RPS3,CSTA,CD300E,RPL3,FPR1,RPL32,RPS27A,RPL39,RP11-631N16.2,RPS18,MT-ND3,RPL13A,RPL35A,AC013264.2,RPS15A,MT-ND4,RPS3A,S100A12
18 GLTSCR2,AL627171.2,APOL4,RPS3A,TRBV11-2,CRYGD,AC079341.1,RPS28,TXNIP,LIMD2,AES,RPL37A,RPL18A,RPL7,FAM65B,RPS12,RPL28,RPL34,GNB2L1,EEF1A1,RPL31,GIMAP7,AL353593.1,RPL32,RPL35A,DAPL1,RPS4X,RPL9,AK8,RPL14
19 AC084033.3,KRT13,CHRM3,MYCT1,FCER1A,OCRL,KRT5,PRSS57,HOXA9,SOX4,IL1B,RACK1,BST1,GATA2,PTN,LY6D,GBP6,KRT15,GUCY1B1,ANK1,CAVIN1,CNRIP1,RP5-1158E12.3,ADGRE2,RPS8,TCTEX1D1,NPR3,KRT6A,CYTL1,RPS24
20 FCER1G,CD7,CD160,TYROBP,IL2RB,CLIC3,IRF8,NFKBIA,KLRF1,FOS,IER2,DUSP1,XCL2,CD247,KLRC1,EML2-AS1,TOX2,SLC15A4,ADGRE5,TIE1,B3GNT7,ITGA2B,LAT2,REL,IFITM3,ZBTB16,CMC1,CCL3,AL669831.1,MAFF
21 OGA,MALAT1,TUT4,MT-RNR1,CH17-189H20.1,SYNE2,NKTR,RPL5P4,PRRC2C,IGHV3-23,CCNL1,ZNF292,PRPF4B,BCLAF1,SRSF11,RP11-463O12.5,PTPRC,IGHV1-46,PIK3R1,SYNE1,MT-RNR2,RBM25,RNA28S,RP11-575L7.8,ANKRD12,SFPQ,NEAT1,GOLGA4,SON,CEMIP2
22 EZR,CREM,CD55,DNAJB6,PTGES3,CHORDC1,SELK,PABPC1,EIF1,DNAJA1,EIF5,OAZ1,CACYBP,SLC3A2,HSP90AB1,VPS37B,ELL2,CYSTM1,TXNRD1,BAZ1A,MIR22HG,JMJD6,RGCC,MTHFD2,FTL,CTD-2192J16.22,FOSL2,UBE2B,UBE2D3,YWHAZ
23 RPS12,RPS2,RPS3,RPS27,RPS18,RPS15A,RPS14,EEF1A1,RPL13,RPL3,RPS4X,RPS28,RPL32,RP11-761N21.2,RP11-864N7.2,RPL34,RPL10,RPL23A,RPS23,RPL18A,RPS6,RPL19,RPS27A,RPL26,RPS8,PLAAT4,RPL30,RPS19,RPS29,RPL11
24 S100B,MT2A,KIR3DL1,AC022431.1,FTH1,AC008038.1,MCOLN3,EEF1A1,NCBP2-AS2,RPL12,RPL11,AC026979.3,AC024293.1,HLA-C,S100A6,RPS15AP1,SUSD4,EIF1,RPL8,RPL32,RPS10P3,RPL19,RPLP0,AL139100.1,RPL10,S100A4,AC078817.1,RPL18,RPL34,RPS8
25 RP11-796E2.4,GADD45B,RP11-727F15.9,RP11-467L13.7,CTA-29F11.1,RP11-596C23.2,RP11-318A15.2,RP5-821D11.7,RP11-307C12.13,FLJ21408,RP11-713P17.3,LINC00936,RP11-108M9.6,RP11-422P24.12,RP11-356I2.4,CTD-2035E11.3,AC061992.2,JUN,CMB9-22P13.1,JUNB,RP1-34B20.21,IER2,RP1-168L15.5,DUSP1,CD69,RHOB,RP13-516M14.4,RP11-380J14.4,RP11-290C10.1,RP11-61J19.5
26 HBB,HBA2,ALAS2,SLC25A37,SNCA,HBA1,TBC1D4,DMTN,GMPR,GLS2,BNIP3L,AHSP,DCAF12,MPP1,HBD,SLC25A39,BSG,FECH,BLVRB,AC022167.3,FAM210B,EIF1AY,NCOA4,CA1,THEM5,SPTA1,IFIT1B,RHAG,SLC1A5,GYPB
27 AZU1,MT-CO2,MT-ATP6,PRTN3,MT-ND3,MT-CO3,MT-ND4L,MT-CO1,MT-ND4,ELANE,MT-CYB,MT-ND1,MT-ND2,MPO,NPW,RPL41,CTSG,AC084033.3,KLRD1,TRBC2,IL7R,ATP5MPL,MT-ATP8,SRGN,MT-ND5,ATP5ME,RAB32,AC092580.4,PCLAF,IGFBP2
28 LOC101928173,MIR155HG,TNFRSF9,CD82,MT1L,LOC102724850,CD74,APOBEC3G,PGAM1,CD27,GZMH,PKM,CD8A,ZBED2,PDCD1,HLA-B,LAG3,IL2RA,GAPDH,GZMB,DUSP4,TIGIT,LOC100996809,VCAM1,NKG7,HLA-A,LYST,PARK7,FKBP1A,APOBEC3C
29 ACTB,CORO1A,IL32,CCL4,RP5-1028K7.2,POTEF,PFN1,CCL3,ACTG1,MYL12A,EVL,FCRL6,ITGB2,PSMB9,CD48,ARPC1B,CD69,ATP5F1E,HP,GIMAP4,FYB,TBC1D10C,AC006129.2,ALB,TRAV12-2,APOA2,TRG-AS1,RP11-386I14.4,CISD3,STAT1
30 IGHV4-39,TNFRSF17,JCHAIN,IGLL5,IGKV3-15,IGHV5-78,IGKV1-5,IGHG2,EBF1,AC021678.2,IGHG1,PNOC,POU2AF1,MZB1,IGHG4,IGKV3OR2-268,DERL3,IGKC,TXNDC5,IGHA1,ZNF860,IGLV3-21,IGHA2,CD79A,CHAD,BHLHE41,IGKV4-1,ITM2C,FCRLA,IGHV4-34
31 KRT86,KRT81,LDLRAD4,WIPF3,RBPJ,ITGA1,TNFRSF18,CSF1,KIR2DL4,NDFIP2,ENTPD1,SAMSN1,ZNF683,KLRC1,SRGAP3,CD9,CAPG,SLC16A3,DUSP4,CD7,KRT83,CEBPB,GZMA,SLC7A5,TBCD,ADGRG3,AFAP1L2,LILRP2,GNLY,COTL1
32 FCER1A,CRHBP,AL157895.1,TMEM98,GATA2,FAM19A2,PBX1,NFIA,CASC15,AVP,GATA1,CYTL1,LINC02573,TPTEP1,CFH,TIMP3,ZSCAN20,MS4A3,ALDH1A1,PCDH9,STON2,GSTO2,STOX1,IL7R,HTR1F,FHL1,RBPMS,SOCS2,MARCKSL1,OAZ2
33 GZMB,KLF2,LAIR2,SELL,FGFBP2,ORAI1,KIR3DL1,PXN,KLF3,PRSS23,ATXN8OS,TXNIP,ADGRG1,ARL4C,AKR1C3,CEP78,CD55,CX3CR1,PLAC8,PDE4D,IL7R,KIR3DX1,GNLY,MTRNR2L10,NKG7,IGFBP7,SYNE1,EFHD2,S1PR5,UCP2
34 DNAJB1,HSPA1A,HSP90AA1,HSPE1,HSPA1B,HSPH1,HSPD1,BAG3,HSPA6,CACYBP,ZFAND2A,HSPA8,COL21A1,HSP90AB1,HSPB1,HSP90AA2P,DNAJA1,SERPINH1,PPP1R15A,UBC,NR4A1,ATF3,FKBP4,DNAJB4,MRPL18,JUN,DOK2,TFF1,TNFSF14,DEDD2
35 XCL1,GPR183,CD44,SELL,TCF7,TNFRSF11A,ITGAX,MAFF,COTL1,FLNB,MAP3K8,CD82,HAPLN3,AC103591.3,AREG,IFITM3,NFKB1,HIF1A,TMEM123,XCL2,OTULIN,FOXC1,IL7R,DUSP4,GAB1,JAG1,KLRC1,SCML1,TIAM1,NCAM1
36 LYZ,FTL,VSIR,OLR1,TYROBP,ADA2,SRGN,S100A4,CYBA,S100A6,VCAN,CSTA,CCL3,FCER1G,CFD,EMP3,GRN,RNASE6,PDPN,S100A9,S100A10,MNDA,LGALS1,GPX1,TYMP,CTSB,AOC1,FOSL2,FTH1,C15orf48
37 ZFP36,BTG2,NR4A2,JUNB,NR4A1,CD69,TNFAIP3,LOC284454,CXCR4,FOSB,RP11-463O12.5,NFKBIA,MCL1,JUN,PPP1R15A,AREG,IER2,DUSP2,NFKBIZ,ZNF331,FOS,AC027290.2,KDM6B,TSC22D3,REL,CSRNP1,DNAJA1,DUSP1,EGR1,NR4A3
38 IGFBP1,ITIH3,AL158850.1,MT-ND4,MT-CO3,MT-CO2,MT-CYB,MT-ATP6,MT-ND1,MT-ND3,MT-ND2,LBP,MT-CO1,RHEX,PNCK,MT-ND5,FGL1,FGA,ORM1,IGHV4-34,MT-ND4L,APOB,AL445673.1,NTM,CRP,PLA2G2A,SAA1,ROR1,UGT2B7,F2
39 BTG1,ITM2C,RPL13A,KRT81,RPS20,CAPG,RPS26,GZMK,RPL27A,KRT86,MALAT1,RPS2,CXCR6,CD44,RPS29,RPL37A,TXNIP,CXCR4,LINC00996,CD9,APOBEC3G,PNRC1,SLFN5,CXCR3,VIM,EPHA1,AC026366.1,RPLP2,RPL10A,SRGAP3
40 RPS12,RPL13,RPLP1,TPT1,IL7R,CCR6,RPL32,NCR2,RPL30,EEF1A1,RPL10,RPS23,APOC4-APOC2,AL445686.2,RPL28,GPR183,RPL34,RPS8,RPL8,RPLP0,VIM,AMICA1,RPS18,U62317.3,RPS14,RPL11,RPL41,RPS5,RPS13,RPS25
41 NKG7,PRF1,SPON2,FGFBP2,GZMB,FCGR3A,SCGB1D2,B2M,ITGB2,CST7,PFN1,GZMA,ACTB,IGFBP7,GPR56,CX3CR1,CYBA,CFL1,AKR1C3,TMSB10,FCER1G,CD247,MT-COX1,PRSS23,MYL12A,LOC101060789,PLAC8,S100A4,EMP3,GZMH

In [9]:
#OUT_FILE <- "./3.3.NK_cGEP_ALL_ANNO/3.3.NK_cGEP_Anno_Complete_With_Genes.csv"
OUT_FILE <- '/sibcb1/bioinformatics/yangyue/project/immunotherapy/7.6.cNMF_menchmark/cGEP_signature/NK_cGEP41_signature.csv'

write.csv(final_combined_df, OUT_FILE, row.names = FALSE)