In [1]:
library(dplyr)
library(tidyr)
library(pheatmap)
library(viridis)
library(tools)
library(cluster)
library(igraph)
library(tibble)

Warning message:
“程辑包‘dplyr’是用R版本4.2.3 来建造的”

载入程辑包：‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“程辑包‘tidyr’是用R版本4.2.3 来建造的”
Warning message:
“程辑包‘viridis’是用R版本4.2.3 来建造的”
载入需要的程辑包：viridisLite

Warning message:
“程辑包‘viridisLite’是用R版本4.2.3 来建造的”
Warning message:
“程辑包‘cluster’是用R版本4.2.3 来建造的”

载入程辑包：‘igraph’


The following object is masked from ‘package:tidyr’:

    crossing


The following objects are masked from ‘package:dplyr’:

    as_data_frame, groups, union


The following objects are masked from ‘package:stats’:

    decompose, spectrum


The following object is masked from ‘package:base’:

    union



载入程辑包：‘tibble’


The following object is masked from ‘package:igraph’:

    as_data_frame

In [2]:
# 读入GEP30个，没有过滤
signature_Neutro <- read.csv(
  "Example_refbuilder_Neutrophils/ALL_cGEP_top_genes_Neutrophils_wide.csv",
  check.names = FALSE,
  stringsAsFactors = FALSE)
# 转成 list（核心）
cluster_genes <- lapply(signature_Neutro, function(x) {
  x[!is.na(x) & x != ""]
})


gene_df <- data.frame(
  cGEP_Cluster = names(cluster_genes),  # 确保这里是 cGEP1, cGEP2...
  cGEP_signature = sapply(cluster_genes, function(x) paste(x, collapse = ",")),
  stringsAsFactors = FALSE
)
gene_df

       cGEP_Cluster
cGEP1  cGEP1
cGEP2  cGEP2
cGEP3  cGEP3
cGEP4  cGEP4
cGEP5  cGEP5
cGEP6  cGEP6
cGEP7  cGEP7
cGEP8  cGEP8
cGEP9  cGEP9
cGEP10 cGEP10
cGEP11 cGEP11
cGEP12 cGEP12
cGEP13 cGEP13
cGEP14 cGEP14
cGEP15 cGEP15
cGEP16 cGEP16
cGEP17 cGEP17
cGEP18 cGEP18
cGEP19 cGEP19
cGEP20 cGEP20
cGEP21 cGEP21
cGEP22 cGEP22
cGEP23 cGEP23
cGEP24 cGEP24
cGEP25 cGEP25
cGEP26 cGEP26
cGEP27 cGEP27
cGEP28 cGEP28
cGEP29 cGEP29
cGEP30 cGEP30
       cGEP_signature
cGEP1  CD3G,IL32,LCK,CCL5,CD3E,GZMA,NKG7,CD2,TRBC2,ITM2A,CD3D,CD27,TRAC,IKZF3,GZMH,RASGRP1,TRAT1,CTLA4,ETS1,GZMK,CD8B,CD8A,SYNE2,TRBC1,CTSW,CST7,LINC00426,CD7,PRF1,SKAP1
cGEP2  CXCR5,LINC01641,GAS5,RPS8,RPS18,RPS2,RPL37A,RPLP2,RPL23A,RPS23,RPS12,RPL18A,RPL10A,RPL3,RPS27,RPS29,RPL13,RPL13A,EEF1A1,RPS6,RPL41,RPL10,TRBC1,RPS3,RPL4,RPS17,SNHG6,RPS20,RPS14,RPL19
cGEP3  S100A9,S100A12,S100A8,VCAN,LYZ,PLBD1,VIM,SERPINB1,METTL9,HP,TKT,MNDA,PADI4,GCA,GAPDH,APLP2,SLC2A3,ITGAM,IRS2,IVNS1ABP,CKAP4,HMGB2,MXD1,CES1,TSPO,GM2A,TALDO1,ANXA1,SELL,RBP7
cGEP4  IER3,IL1B,NFKBIA,NLRP3,AC095055.1,TNFAIP3,VEGFA,KDM6B,ZNF331,INSIG1,GPR183,MAP3K8,AC092368.3,EREG,CXCL2,GRASP,CXCL8,AC016831.7,RASGEF1B,PLAUR,NR4A1,THBS1,NAMPT,CD83,ARF4-AS1,CLHC1,HLA-DQB2,PIM3,MRPS24,CSRNP1
cGEP5  IFIT1,RSAD2,IFIT3,ISG15,MX1,HERC5,IFIT2,GBP1,CMPK2,SPDEF,AC010501.1,OAS2,AC138907.8,IFI44L,SERPING1,IFITM3,GBP5,GBP4,IFI6,AC007362.1,EPSTI1,RNF213,DDX58,AC148477.3,UBE2L6,XAF1,STAT1,AC113189.2,LINC02453,TNFSF13B
cGEP6  FCGR3A,RYR3,AIF1,C1QA,LST1,IFITM3,RHOC,SMIM25,CDKN1C,C1QB,FCER1G,CLIC2,CD79B,ABI3,CSF1R,AC007038.1,TCF7L2,ATP8B1,FMNL2,CEBPB,TRNP1,LINC02449,DRAP1,AC124045.1,COTL1,MTSS1,LRRC25,L1TD1,RPS19,C1QC
cGEP7  HLA-DQA1,FCER1A,HLA-DRA,HLA-DPA1,HLA-DQA2,RGS1,HLA-DPB1,HLA-DQB1,HLA-DRB1,HLA-DRB5,CLEC10A,CD74,HIST1H3A,HLA-DMA,CD1C,CCSER1,AC102953.2,AL390728.5,ZNF697,MRC1,ZNF790,HLA-DOA,TNFRSF21,LINC01970,AC124068.2,CST7,SH3BP4,ZNF597,TNFRSF12A,RGL1
cGEP8  BCL2,AL049840.1,LOH12CR2,AC092368.3,RILPL1,CCNH,CDKN2A,SNX24,AL117339.5,YES1,ACVRL1,AL450326.1,POLR3B,CDKL3,AL138820.1,TUBGCP5,AC119428.2,AL590617.2,ZNF517,NPM3,HOXB3,CAMK4,CNTNAP2,HYPK,AC124242.1,TFRC,IKZF4,AC114490.2,TMEM236,AC005838.2
cGEP9  PLK2,MSR1,C3,ACVRL1,ACKR3,APOC1,ZNF707,SPARC,PHLDA1,AC011043.1,CD81,LTC4S,TBX6,ZBED3-AS1,AC005076.1,LINC01431,NRP1,OSM,AL357060.1,SLC2A5,PSD,MARCO,WDR76,AL450326.1,GPT2,OLR1,UBE3D,FN1,LINC01678,EPS8L1
cGEP10 ZNF521,STMN2,RBFOX1,KCNIP4,CDCA5,ZNF462,PKIA,BEX3,SYN1,MPP3,SYT4,NEUROD1,IGSF21,SH3PXD2A,RNF144A,TRPM3,BEX1,NCS1,PTHLH,NRN1,AL158835.1,AC004540.2,ST18,ZBTB18,SGIP1,DYNC1I1,CCND2,MAGI3,DTNA,NNAT
cGEP11 MGP,SFRP1,FAM19A5,KIF21A,PDLIM3,LINC01315,BAIAP2L2,KHDRBS3,NTRK3,SLIT1,EXOC3L1,KIF26A,BOC,ELAVL4,INSM1,RHOBTB3,FOXS1,CDH15,ANK3,RGMB,MIR99AHG,ZNF681,FAM57B,FAM161B,APBB2,SP5,ACVR2B,PAK3,ZIC2,PCNT
cGEP12 CENPV,TMSB15A,CCDC34,MYBL2,CENPF,RAI14,GJC1,FANCG,FAM84A,TMEM108,UBE2T,DHCR24,CPLX1,ABCA3,PAX6,MAP1B,PHF21B,BDH1,PHGDH,ZIC2,NAT8L,SPAG16,NSD2,E2F1,TMCC1-AS1,GTSE1,FARP1,FRRS1L,DCHS1,SLC29A4
cGEP13 CXCR2,B2M,TAGLN2,TXNIP,NEAT1,TSC22D3,CPPED1,SEC14L1,MALAT1,NCOA4,SOD2,ITM2B,RNASET2,TNFAIP2,VMP1,HLA-B,P2RY13,SLC25A37,LYN,HLA-C,IFITM2,H3F3A,GNG10,ADGRE5,OAZ2,KCTD21-AS1,PTPRC,FAM129A,LRRC25,LRRFIP1
cGEP14 S100A9,S100A12,MMP9,S100A8,RFLNB,PADI4,S100A6,ACTB,HMGB2,ALOX5AP,FCN1,TSPO,GAPDH,APMAP,CST7,S100A4,CDA,TXN,CKAP4,PGLYRP1,GRN,NCF1,CTSD,CAP1,PGD,GNG2,VIM,PYGL,FOLR3,QPCT
cGEP15 G0S2,PLAUR,SAMSN1,JOSD1,AC245128.3,PFKFB3,CXCL8,OSM,PTGS2,TRIB1,SRGN,FTH1,NR4A3,SOCS3,IVNS1ABP,CSRNP1,IER3,SYAP1,CD55,SAT1,ACTG1,FRMD4B,PLEK,SLC2A3,BCL2A1,MCL1,ETS2,CREM,DDIT4,ELL2
cGEP16 MT-ATP6,MT-CO1,MT-ND4,MT-CO3,MT-CYB,MT-ND1,MT-ND3,MT-ATP8,MT-CO2,MT-ND5,MT-ND2,MT-ND4L,MIAT,VCAN,SPINK4,MUC5AC,MT-RNR2,PSCA,KRTAP4-8,CDC42BPG,PHF10,PLXNB2,ADO,MARCH1,SH3BP4,MT-RNR1,MALAT1,RNF217,TMEM190,LINC00315
cGEP17 PF4,PPBP,NRGN,F13A1,CAVIN2,MPIG6B,PRKAR2B,TUBB1,CTDSPL,SCFD2,GRAP2,TSC22D1,GP9,CLU,CMTM5,SPARC,ITGA2B,ITGB5,MYL9,PTCRA,SH3BGRL2,CLDN5,CDKN1A,CCL5,PDLIM1,HIST1H2AE,GPX1,PF4V1,ALOX12,BEX3
cGEP18 LCN2,RETN,LTF,CD24,CEACAM8,BPI,CAMP,CEACAM6,CRISP3,LYZ,OLFM4,RNASE2,TCN1,RNASE3,STOM,MS4A3,CEBPE,HTRA3,COL17A1,DEFA4,TFF3,LINC02009,ABCA13,CTSG,MMP8,ERG,AZU1,PRTN3,BEX1,C20orf27
cGEP19 IGKC,IGHG2,IGHG1,HSPB1,IGHG3,C10orf10,BAG3,HSPA1B,MTRR,JUN,IGHG4,XBP1,ARID5B,ROR2,EEF1E1,HSPA1A,SIL1,NUDT13,PLA2G16,DNAJB1,TPRN,GS1-124K5.4,LINC00689,PPM1N,RHEBL1,LINC02487,GLO1,GPR39,BHLHE41,YIF1A
cGEP20 TGFA,RASSF6,GLIS3,MET,LPIN3,CDH4,CCND1,ATP1B1,LINC01320,ANGPTL4,LINC02532,PKHD1,BHLHE41,CLDN2,CP,TMEM67,CGNL1,UGT2A3,SLC3A1,MT-ND4,HSF4,MEST,OSGEPL1,LINC00665,SBF2-AS1,IRX3,CLDN3,PLEKHH2,MYEF2,CHPF
cGEP21 CD9,SLC16A10,FN1,FPR3,CARMIL1,VSIG4,SH3D19,HS3ST1,OLR1,TNFRSF4,CRACR2B,FAN1,ZGRF1,GSDME,PMEPA1,RAMP3,PARM1,C3,JAG1,CLEC5A,EIF5AL1,THBD,DOLK,SLC16A1-AS1,POP1,CD81,P2RY6,LRIF1,AC009812.1,NLE1
cGEP22 APOE,TREM2,C1QC,UNC5B,SCIN,SDS,LIF,C1QB,APOC1,RASSF8,HTR7,NAV2,A2M,ZNF205,SLC38A1,CD74,ACOT11,SLC24A1,KCNMA1,AL391069.3,PPM1H,DKK3,NEXN,ABHD5,TSPYL2,SLC1A3,HLA-DPA1,HLTF,KIAA0355,HLA-DQB1
cGEP23 RGS5,PDGFRB,MYO1B,WEE1,ZNF793,TNS2,EBF1,BGN,IGFBP7,RBMS3,NR2F2,SNCG,SPARC,TSHZ2,TNS1,CALD1,MYLK,CASC15,COL4A2,KLF8,ITGA3,CAV1,PRUNE2,COL6A2,MGP,SLC16A1-AS1,MOK,COL4A1,TPM1,MTUS1
cGEP24 SPRY1,ESM1,TM4SF18,MEIS2,KDR,GJA1,DOCK9,PBX1,IGFBP5,NOSTRIN,WWTR1,PDGFD,CA4,EPN2,PIK3R3,ARHGAP29,AKAP12,COL8A1,RBP5,KANK3,PTPRB,EMCN,ZNF79,CAVIN2,ZNF704,AFAP1L1,SPARCL1,FCN3,VWF,CRIM1
cGEP25 C1QB,C1QC,C1QA,TMEM176B,MS4A6A,MS4A4A,ITM2B,NPC2,FCGRT,IL2RA,FUCA1,PLTP,FOLR2,TSPAN4,CD74,HLA-C,CST3,CTSC,HLA-DMB,VSIG4,TMEM176A,GPR34,HLA-DMA,APOE,MGST2,SLC40A1,GRN,ADAMDEC1,CTSZ,DNASE2
cGEP26 GPNMB,RNASE1,FTL,CTSD,LIPA,NUPR1,SPP1,SCD,APLP2,TREM2,TGFBI,CD68,TIMP2,CD109,SLC2A1,ADAM8,CSTB,CTSB,DAB2,AHNAK,FCGR2A,RNF145,ECM1,VAT1,IQGAP2,LGALS3,LGMN,VIM,MSR1,OTOA
cGEP27 HSPA1A,JUN,KLF2,DNAJA4,IER5,HSPD1,HSPA8,BAG3,HSP90AA1,DNAJB1,HSP90AB1,RHOB,HSPH1,DNAJA1,KLF4,PPP1R15A,CLK1,HSPE1,UBC,TRA2B,ZFAND2A,EIF4A3,HSPA6,CHORDC1,KLF6,GADD45B,JUND,DNAJB6,BTG2,HSPA1B
cGEP28 CHI3L1,FBP1,GPC4,RGCC,FAIM2,USP2,CA2,TM4SF19,CSTB,VIM,LILRB4,MATK,HRK,MARCO,SLC28A3,FN1,LPL,GOLGA7B,CAMP,CP,EFNA5,FABP3,EVL,MREG,CYP27B1,GAL,FAH,CYP19A1,LGALS2,ARL4D
cGEP29 MKI67,UBE2C,CDK1,HMMR,BIRC5,NUSAP1,GTSE1,CCNA2,AURKB,H2AFZ,TUBB,STMN1,TOP2A,TPX2,CCNB2,HIST1H4C,CDC20,TUBA1B,CKS1B,CCNB1,CENPM,CENPF,PTTG1,CEP55,SMC2,ANLN,TK1,PLK1,CDKN3,RRM2
cGEP30 COL6A3,COL6A2,PAPPA,COL1A1,COL6A1,TRIML2,FAM171B,SYT7,SLC22A17,NTN4,SV2A,TPBG,COL3A1,SNAP25,AEBP1,ADAMTS6,COL5A3,COL18A1,THBS2,ZNF66,TET1,TFPI,AC020688.1,SGIP1,C1R,PRRX1,ITGA10,ITGB3,PKP3,HIF3A

In [4]:
#Neu_gep_anno <- read.csv('./3.Neutrophils_GEP_Anno/3.3.Neutrophils_GEP30_Anno_final.csv')
Neu_gep_anno <- read.csv('/sibcb1/bioinformatics/yangyue/project/immunotherapy/7.6.cNMF_menchmark/cGEP_signature/Neutrophils_cGEP30.csv')
Neu_gep_anno

   cGEP_Cluster cGEP_Anno_Name     Category
1  cGEP5        Neu-IFN            Functional
2  cGEP18       Neu-Degranulation  Functional
3  cGEP16       Art-Mito           Artifact
4  cGEP4        Neu-Inflammation   Functional
5  cGEP6        Doublet-Mono       Doublet
6  cGEP27       Art-Stress         Artifact
7  cGEP3        Doublet-Mono       Doublet
8  cGEP2        Art-Ribo           Artifact
9  cGEP25       Doublet-Mono       Doublet
10 cGEP14       Neu-Core           Lineage
11 cGEP26       Doublet-Macrophage Doublet
12 cGEP19       Art-IG_Stress      Artifact
13 cGEP28       Neu-Immature       Lineage
14 cGEP15       Neu-G0S2           Functional
15 cGEP29       Neu-Cycle          Lineage
16 cGEP7        Doublet-DC         Doublet
17 cGEP22       Doublet-TAM        Doublet
18 cGEP13       Neu-Mature         Lineage
19 cGEP9        Neu-MDSC_MSR1      Functional
20 cGEP21       Neu-MDSC_FN1       Functional
21 cGEP23       Stromal-Pericyte   Doublet
22 cGEP24       Stromal-Endo       Doublet
23 cGEP1        Doublet-T_Cell     Doublet
24 cGEP20       Contam-Tumor       Doublet
25 cGEP17       Contam-Platelet    Doublet
26 cGEP12       Neu-Cycle_G2M      Functional
27 cGEP11       Stromal-Fibroblast Doublet
28 cGEP10       Contam-Tumor       Doublet
29 cGEP8        Doublet-Lymph_BCL  Doublet
30 cGEP30       Doublet-ECM        Doublet

In [5]:
final_combined_df <- Neu_gep_anno %>%
  left_join(gene_df, by = "cGEP_Cluster")
final_combined_df

   cGEP_Cluster cGEP_Anno_Name     Category
1  cGEP5        Neu-IFN            Functional
2  cGEP18       Neu-Degranulation  Functional
3  cGEP16       Art-Mito           Artifact
4  cGEP4        Neu-Inflammation   Functional
5  cGEP6        Doublet-Mono       Doublet
6  cGEP27       Art-Stress         Artifact
7  cGEP3        Doublet-Mono       Doublet
8  cGEP2        Art-Ribo           Artifact
9  cGEP25       Doublet-Mono       Doublet
10 cGEP14       Neu-Core           Lineage
11 cGEP26       Doublet-Macrophage Doublet
12 cGEP19       Art-IG_Stress      Artifact
13 cGEP28       Neu-Immature       Lineage
14 cGEP15       Neu-G0S2           Functional
15 cGEP29       Neu-Cycle          Lineage
16 cGEP7        Doublet-DC         Doublet
17 cGEP22       Doublet-TAM        Doublet
18 cGEP13       Neu-Mature         Lineage
19 cGEP9        Neu-MDSC_MSR1      Functional
20 cGEP21       Neu-MDSC_FN1       Functional
21 cGEP23       Stromal-Pericyte   Doublet
22 cGEP24       Stromal-Endo       Doublet
23 cGEP1        Doublet-T_Cell     Doublet
24 cGEP20       Contam-Tumor       Doublet
25 cGEP17       Contam-Platelet    Doublet
26 cGEP12       Neu-Cycle_G2M      Functional
27 cGEP11       Stromal-Fibroblast Doublet
28 cGEP10       Contam-Tumor       Doublet
29 cGEP8        Doublet-Lymph_BCL  Doublet
30 cGEP30       Doublet-ECM        Doublet
   cGEP_signature
1  IFIT1,RSAD2,IFIT3,ISG15,MX1,HERC5,IFIT2,GBP1,CMPK2,SPDEF,AC010501.1,OAS2,AC138907.8,IFI44L,SERPING1,IFITM3,GBP5,GBP4,IFI6,AC007362.1,EPSTI1,RNF213,DDX58,AC148477.3,UBE2L6,XAF1,STAT1,AC113189.2,LINC02453,TNFSF13B
2  LCN2,RETN,LTF,CD24,CEACAM8,BPI,CAMP,CEACAM6,CRISP3,LYZ,OLFM4,RNASE2,TCN1,RNASE3,STOM,MS4A3,CEBPE,HTRA3,COL17A1,DEFA4,TFF3,LINC02009,ABCA13,CTSG,MMP8,ERG,AZU1,PRTN3,BEX1,C20orf27
3  MT-ATP6,MT-CO1,MT-ND4,MT-CO3,MT-CYB,MT-ND1,MT-ND3,MT-ATP8,MT-CO2,MT-ND5,MT-ND2,MT-ND4L,MIAT,VCAN,SPINK4,MUC5AC,MT-RNR2,PSCA,KRTAP4-8,CDC42BPG,PHF10,PLXNB2,ADO,MARCH1,SH3BP4,MT-RNR1,MALAT1,RNF217,TMEM190,LINC00315
4  IER3,IL1B,NFKBIA,NLRP3,AC095055.1,TNFAIP3,VEGFA,KDM6B,ZNF331,INSIG1,GPR183,MAP3K8,AC092368.3,EREG,CXCL2,GRASP,CXCL8,AC016831.7,RASGEF1B,PLAUR,NR4A1,THBS1,NAMPT,CD83,ARF4-AS1,CLHC1,HLA-DQB2,PIM3,MRPS24,CSRNP1
5  FCGR3A,RYR3,AIF1,C1QA,LST1,IFITM3,RHOC,SMIM25,CDKN1C,C1QB,FCER1G,CLIC2,CD79B,ABI3,CSF1R,AC007038.1,TCF7L2,ATP8B1,FMNL2,CEBPB,TRNP1,LINC02449,DRAP1,AC124045.1,COTL1,MTSS1,LRRC25,L1TD1,RPS19,C1QC
6  HSPA1A,JUN,KLF2,DNAJA4,IER5,HSPD1,HSPA8,BAG3,HSP90AA1,DNAJB1,HSP90AB1,RHOB,HSPH1,DNAJA1,KLF4,PPP1R15A,CLK1,HSPE1,UBC,TRA2B,ZFAND2A,EIF4A3,HSPA6,CHORDC1,KLF6,GADD45B,JUND,DNAJB6,BTG2,HSPA1B
7  S100A9,S100A12,S100A8,VCAN,LYZ,PLBD1,VIM,SERPINB1,METTL9,HP,TKT,MNDA,PADI4,GCA,GAPDH,APLP2,SLC2A3,ITGAM,IRS2,IVNS1ABP,CKAP4,HMGB2,MXD1,CES1,TSPO,GM2A,TALDO1,ANXA1,SELL,RBP7
8  CXCR5,LINC01641,GAS5,RPS8,RPS18,RPS2,RPL37A,RPLP2,RPL23A,RPS23,RPS12,RPL18A,RPL10A,RPL3,RPS27,RPS29,RPL13,RPL13A,EEF1A1,RPS6,RPL41,RPL10,TRBC1,RPS3,RPL4,RPS17,SNHG6,RPS20,RPS14,RPL19
9  C1QB,C1QC,C1QA,TMEM176B,MS4A6A,MS4A4A,ITM2B,NPC2,FCGRT,IL2RA,FUCA1,PLTP,FOLR2,TSPAN4,CD74,HLA-C,CST3,CTSC,HLA-DMB,VSIG4,TMEM176A,GPR34,HLA-DMA,APOE,MGST2,SLC40A1,GRN,ADAMDEC1,CTSZ,DNASE2
10 S100A9,S100A12,MMP9,S100A8,RFLNB,PADI4,S100A6,ACTB,HMGB2,ALOX5AP,FCN1,TSPO,GAPDH,APMAP,CST7,S100A4,CDA,TXN,CKAP4,PGLYRP1,GRN,NCF1,CTSD,CAP1,PGD,GNG2,VIM,PYGL,FOLR3,QPCT
11 GPNMB,RNASE1,FTL,CTSD,LIPA,NUPR1,SPP1,SCD,APLP2,TREM2,TGFBI,CD68,TIMP2,CD109,SLC2A1,ADAM8,CSTB,CTSB,DAB2,AHNAK,FCGR2A,RNF145,ECM1,VAT1,IQGAP2,LGALS3,LGMN,VIM,MSR1,OTOA
12 IGKC,IGHG2,IGHG1,HSPB1,IGHG3,C10orf10,BAG3,HSPA1B,MTRR,JUN,IGHG4,XBP1,ARID5B,ROR2,EEF1E1,HSPA1A,SIL1,NUDT13,PLA2G16,DNAJB1,TPRN,GS1-124K5.4,LINC00689,PPM1N,RHEBL1,LINC02487,GLO1,GPR39,BHLHE41,YIF1A
13 CHI3L1,FBP1,GPC4,RGCC,FAIM2,USP2,CA2,TM4SF19,CSTB,VIM,LILRB4,MATK,HRK,MARCO,SLC28A3,FN1,LPL,GOLGA7B,CAMP,CP,EFNA5,FABP3,EVL,MREG,CYP27B1,GAL,FAH,CYP19A1,LGALS2,ARL4D
14 G0S2,PLAUR,SAMSN1,JOSD1,AC245128.3,PFKFB3,CXCL8,OSM,PTGS2,TRIB1,SRGN,FTH1,NR4A3,SOCS3,IVNS1ABP,CSRNP1,IER3,SYAP1,CD55,SAT1,ACTG1,FRMD4B,PLEK,SLC2A3,BCL2A1,MCL1,ETS2,CREM,DDIT4,ELL2
15 MKI67,UBE2C,CDK1,HMMR,BIRC5,NUSAP1,GTSE1,CCNA2,AURKB,H2AFZ,TUBB,STMN1,TOP2A,TPX2,CCNB2,HIST1H4C,CDC20,TUBA1B,CKS1B,CCNB1,CENPM,CENPF,PTTG1,CEP55,SMC2,ANLN,TK1,PLK1,CDKN3,RRM2
16 HLA-DQA1,FCER1A,HLA-DRA,HLA-DPA1,HLA-DQA2,RGS1,HLA-DPB1,HLA-DQB1,HLA-DRB1,HLA-DRB5,CLEC10A,CD74,HIST1H3A,HLA-DMA,CD1C,CCSER1,AC102953.2,AL390728.5,ZNF697,MRC1,ZNF790,HLA-DOA,TNFRSF21,LINC01970,AC124068.2,CST7,SH3BP4,ZNF597,TNFRSF12A,RGL1
17 APOE,TREM2,C1QC,UNC5B,SCIN,SDS,LIF,C1QB,APOC1,RASSF8,HTR7,NAV2,A2M,ZNF205,SLC38A1,CD74,ACOT11,SLC24A1,KCNMA1,AL391069.3,PPM1H,DKK3,NEXN,ABHD5,TSPYL2,SLC1A3,HLA-DPA1,HLTF,KIAA0355,HLA-DQB1
18 CXCR2,B2M,TAGLN2,TXNIP,NEAT1,TSC22D3,CPPED1,SEC14L1,MALAT1,NCOA4,SOD2,ITM2B,RNASET2,TNFAIP2,VMP1,HLA-B,P2RY13,SLC25A37,LYN,HLA-C,IFITM2,H3F3A,GNG10,ADGRE5,OAZ2,KCTD21-AS1,PTPRC,FAM129A,LRRC25,LRRFIP1
19 PLK2,MSR1,C3,ACVRL1,ACKR3,APOC1,ZNF707,SPARC,PHLDA1,AC011043.1,CD81,LTC4S,TBX6,ZBED3-AS1,AC005076.1,LINC01431,NRP1,OSM,AL357060.1,SLC2A5,PSD,MARCO,WDR76,AL450326.1,GPT2,OLR1,UBE3D,FN1,LINC01678,EPS8L1
20 CD9,SLC16A10,FN1,FPR3,CARMIL1,VSIG4,SH3D19,HS3ST1,OLR1,TNFRSF4,CRACR2B,FAN1,ZGRF1,GSDME,PMEPA1,RAMP3,PARM1,C3,JAG1,CLEC5A,EIF5AL1,THBD,DOLK,SLC16A1-AS1,POP1,CD81,P2RY6,LRIF1,AC009812.1,NLE1
21 RGS5,PDGFRB,MYO1B,WEE1,ZNF793,TNS2,EBF1,BGN,IGFBP7,RBMS3,NR2F2,SNCG,SPARC,TSHZ2,TNS1,CALD1,MYLK,CASC15,COL4A2,KLF8,ITGA3,CAV1,PRUNE2,COL6A2,MGP,SLC16A1-AS1,MOK,COL4A1,TPM1,MTUS1
22 SPRY1,ESM1,TM4SF18,MEIS2,KDR,GJA1,DOCK9,PBX1,IGFBP5,NOSTRIN,WWTR1,PDGFD,CA4,EPN2,PIK3R3,ARHGAP29,AKAP12,COL8A1,RBP5,KANK3,PTPRB,EMCN,ZNF79,CAVIN2,ZNF704,AFAP1L1,SPARCL1,FCN3,VWF,CRIM1
23 CD3G,IL32,LCK,CCL5,CD3E,GZMA,NKG7,CD2,TRBC2,ITM2A,CD3D,CD27,TRAC,IKZF3,GZMH,RASGRP1,TRAT1,CTLA4,ETS1,GZMK,CD8B,CD8A,SYNE2,TRBC1,CTSW,CST7,LINC00426,CD7,PRF1,SKAP1
24 TGFA,RASSF6,GLIS3,MET,LPIN3,CDH4,CCND1,ATP1B1,LINC01320,ANGPTL4,LINC02532,PKHD1,BHLHE41,CLDN2,CP,TMEM67,CGNL1,UGT2A3,SLC3A1,MT-ND4,HSF4,MEST,OSGEPL1,LINC00665,SBF2-AS1,IRX3,CLDN3,PLEKHH2,MYEF2,CHPF
25 PF4,PPBP,NRGN,F13A1,CAVIN2,MPIG6B,PRKAR2B,TUBB1,CTDSPL,SCFD2,GRAP2,TSC22D1,GP9,CLU,CMTM5,SPARC,ITGA2B,ITGB5,MYL9,PTCRA,SH3BGRL2,CLDN5,CDKN1A,CCL5,PDLIM1,HIST1H2AE,GPX1,PF4V1,ALOX12,BEX3
26 CENPV,TMSB15A,CCDC34,MYBL2,CENPF,RAI14,GJC1,FANCG,FAM84A,TMEM108,UBE2T,DHCR24,CPLX1,ABCA3,PAX6,MAP1B,PHF21B,BDH1,PHGDH,ZIC2,NAT8L,SPAG16,NSD2,E2F1,TMCC1-AS1,GTSE1,FARP1,FRRS1L,DCHS1,SLC29A4
27 MGP,SFRP1,FAM19A5,KIF21A,PDLIM3,LINC01315,BAIAP2L2,KHDRBS3,NTRK3,SLIT1,EXOC3L1,KIF26A,BOC,ELAVL4,INSM1,RHOBTB3,FOXS1,CDH15,ANK3,RGMB,MIR99AHG,ZNF681,FAM57B,FAM161B,APBB2,SP5,ACVR2B,PAK3,ZIC2,PCNT
28 ZNF521,STMN2,RBFOX1,KCNIP4,CDCA5,ZNF462,PKIA,BEX3,SYN1,MPP3,SYT4,NEUROD1,IGSF21,SH3PXD2A,RNF144A,TRPM3,BEX1,NCS1,PTHLH,NRN1,AL158835.1,AC004540.2,ST18,ZBTB18,SGIP1,DYNC1I1,CCND2,MAGI3,DTNA,NNAT
29 BCL2,AL049840.1,LOH12CR2,AC092368.3,RILPL1,CCNH,CDKN2A,SNX24,AL117339.5,YES1,ACVRL1,AL450326.1,POLR3B,CDKL3,AL138820.1,TUBGCP5,AC119428.2,AL590617.2,ZNF517,NPM3,HOXB3,CAMK4,CNTNAP2,HYPK,AC124242.1,TFRC,IKZF4,AC114490.2,TMEM236,AC005838.2
30 COL6A3,COL6A2,PAPPA,COL1A1,COL6A1,TRIML2,FAM171B,SYT7,SLC22A17,NTN4,SV2A,TPBG,COL3A1,SNAP25,AEBP1,ADAMTS6,COL5A3,COL18A1,THBS2,ZNF66,TET1,TFPI,AC020688.1,SGIP1,C1R,PRRX1,ITGA10,ITGB3,PKP3,HIF3A

In [8]:
#OUT_FILE <- "./3.Neutrophils_GEP_Anno/3.3.Neutrophil_cGEP30_Anno_Complete_With_Genes.csv"
OUT_FILE <- '/sibcb1/bioinformatics/yangyue/project/immunotherapy/7.6.cNMF_menchmark/cGEP_signature/Neutrophils_cGEP30_signature.csv'

write.csv(final_combined_df, OUT_FILE, row.names = FALSE)